// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

module AXI4UserYanker(
  input         clock,
                reset,
                auto_in_aw_valid,
  input  [3:0]  auto_in_aw_bits_id,
  input  [31:0] auto_in_aw_bits_addr,
  input  [7:0]  auto_in_aw_bits_len,
  input  [2:0]  auto_in_aw_bits_size,
  input  [1:0]  auto_in_aw_bits_burst,
  input         auto_in_aw_bits_lock,
  input  [3:0]  auto_in_aw_bits_cache,
  input  [2:0]  auto_in_aw_bits_prot,
  input  [3:0]  auto_in_aw_bits_qos,
                auto_in_aw_bits_echo_tl_state_size,
  input  [7:0]  auto_in_aw_bits_echo_tl_state_source,
  input  [3:0]  auto_in_aw_bits_echo_extra_id,
  input         auto_in_w_valid,
  input  [63:0] auto_in_w_bits_data,
  input  [7:0]  auto_in_w_bits_strb,
  input         auto_in_w_bits_last,
                auto_in_b_ready,
                auto_in_ar_valid,
  input  [3:0]  auto_in_ar_bits_id,
  input  [31:0] auto_in_ar_bits_addr,
  input  [7:0]  auto_in_ar_bits_len,
  input  [2:0]  auto_in_ar_bits_size,
  input  [1:0]  auto_in_ar_bits_burst,
  input         auto_in_ar_bits_lock,
  input  [3:0]  auto_in_ar_bits_cache,
  input  [2:0]  auto_in_ar_bits_prot,
  input  [3:0]  auto_in_ar_bits_qos,
                auto_in_ar_bits_echo_tl_state_size,
  input  [7:0]  auto_in_ar_bits_echo_tl_state_source,
  input  [3:0]  auto_in_ar_bits_echo_extra_id,
  input         auto_in_r_ready,
                auto_out_aw_ready,
                auto_out_w_ready,
                auto_out_b_valid,
  input  [3:0]  auto_out_b_bits_id,
  input  [1:0]  auto_out_b_bits_resp,
  input         auto_out_ar_ready,
                auto_out_r_valid,
  input  [3:0]  auto_out_r_bits_id,
  input  [63:0] auto_out_r_bits_data,
  input  [1:0]  auto_out_r_bits_resp,
  input         auto_out_r_bits_last,
  output        auto_in_aw_ready,
                auto_in_w_ready,
                auto_in_b_valid,
  output [3:0]  auto_in_b_bits_id,
  output [1:0]  auto_in_b_bits_resp,
  output [3:0]  auto_in_b_bits_echo_tl_state_size,
  output [7:0]  auto_in_b_bits_echo_tl_state_source,
  output [3:0]  auto_in_b_bits_echo_extra_id,
  output        auto_in_ar_ready,
                auto_in_r_valid,
  output [3:0]  auto_in_r_bits_id,
  output [63:0] auto_in_r_bits_data,
  output [1:0]  auto_in_r_bits_resp,
  output [3:0]  auto_in_r_bits_echo_tl_state_size,
  output [7:0]  auto_in_r_bits_echo_tl_state_source,
  output [3:0]  auto_in_r_bits_echo_extra_id,
  output        auto_in_r_bits_last,
                auto_out_aw_valid,
  output [3:0]  auto_out_aw_bits_id,
  output [31:0] auto_out_aw_bits_addr,
  output [7:0]  auto_out_aw_bits_len,
  output [2:0]  auto_out_aw_bits_size,
  output [1:0]  auto_out_aw_bits_burst,
  output        auto_out_aw_bits_lock,
  output [3:0]  auto_out_aw_bits_cache,
  output [2:0]  auto_out_aw_bits_prot,
  output [3:0]  auto_out_aw_bits_qos,
  output        auto_out_w_valid,
  output [63:0] auto_out_w_bits_data,
  output [7:0]  auto_out_w_bits_strb,
  output        auto_out_w_bits_last,
                auto_out_b_ready,
                auto_out_ar_valid,
  output [3:0]  auto_out_ar_bits_id,
  output [31:0] auto_out_ar_bits_addr,
  output [7:0]  auto_out_ar_bits_len,
  output [2:0]  auto_out_ar_bits_size,
  output [1:0]  auto_out_ar_bits_burst,
  output        auto_out_ar_bits_lock,
  output [3:0]  auto_out_ar_bits_cache,
  output [2:0]  auto_out_ar_bits_prot,
  output [3:0]  auto_out_ar_bits_qos,
  output        auto_out_r_ready
);

  wire             _QueueCompatibility_31_io_enq_ready;	// @[UserYanker.scala:48:17]
  wire             _QueueCompatibility_31_io_deq_valid;	// @[UserYanker.scala:48:17]
  wire [3:0]       _QueueCompatibility_31_io_deq_bits_tl_state_size;	// @[UserYanker.scala:48:17]
  wire [7:0]       _QueueCompatibility_31_io_deq_bits_tl_state_source;	// @[UserYanker.scala:48:17]
  wire [3:0]       _QueueCompatibility_31_io_deq_bits_extra_id;	// @[UserYanker.scala:48:17]
  wire             _QueueCompatibility_30_io_enq_ready;	// @[UserYanker.scala:48:17]
  wire             _QueueCompatibility_30_io_deq_valid;	// @[UserYanker.scala:48:17]
  wire [3:0]       _QueueCompatibility_30_io_deq_bits_tl_state_size;	// @[UserYanker.scala:48:17]
  wire [7:0]       _QueueCompatibility_30_io_deq_bits_tl_state_source;	// @[UserYanker.scala:48:17]
  wire [3:0]       _QueueCompatibility_30_io_deq_bits_extra_id;	// @[UserYanker.scala:48:17]
  wire             _QueueCompatibility_29_io_enq_ready;	// @[UserYanker.scala:48:17]
  wire             _QueueCompatibility_29_io_deq_valid;	// @[UserYanker.scala:48:17]
  wire [3:0]       _QueueCompatibility_29_io_deq_bits_tl_state_size;	// @[UserYanker.scala:48:17]
  wire [7:0]       _QueueCompatibility_29_io_deq_bits_tl_state_source;	// @[UserYanker.scala:48:17]
  wire [3:0]       _QueueCompatibility_29_io_deq_bits_extra_id;	// @[UserYanker.scala:48:17]
  wire             _QueueCompatibility_28_io_enq_ready;	// @[UserYanker.scala:48:17]
  wire             _QueueCompatibility_28_io_deq_valid;	// @[UserYanker.scala:48:17]
  wire [3:0]       _QueueCompatibility_28_io_deq_bits_tl_state_size;	// @[UserYanker.scala:48:17]
  wire [7:0]       _QueueCompatibility_28_io_deq_bits_tl_state_source;	// @[UserYanker.scala:48:17]
  wire [3:0]       _QueueCompatibility_28_io_deq_bits_extra_id;	// @[UserYanker.scala:48:17]
  wire             _QueueCompatibility_27_io_enq_ready;	// @[UserYanker.scala:48:17]
  wire             _QueueCompatibility_27_io_deq_valid;	// @[UserYanker.scala:48:17]
  wire [3:0]       _QueueCompatibility_27_io_deq_bits_tl_state_size;	// @[UserYanker.scala:48:17]
  wire [7:0]       _QueueCompatibility_27_io_deq_bits_tl_state_source;	// @[UserYanker.scala:48:17]
  wire [3:0]       _QueueCompatibility_27_io_deq_bits_extra_id;	// @[UserYanker.scala:48:17]
  wire             _QueueCompatibility_26_io_enq_ready;	// @[UserYanker.scala:48:17]
  wire             _QueueCompatibility_26_io_deq_valid;	// @[UserYanker.scala:48:17]
  wire [3:0]       _QueueCompatibility_26_io_deq_bits_tl_state_size;	// @[UserYanker.scala:48:17]
  wire [7:0]       _QueueCompatibility_26_io_deq_bits_tl_state_source;	// @[UserYanker.scala:48:17]
  wire [3:0]       _QueueCompatibility_26_io_deq_bits_extra_id;	// @[UserYanker.scala:48:17]
  wire             _QueueCompatibility_25_io_enq_ready;	// @[UserYanker.scala:48:17]
  wire             _QueueCompatibility_25_io_deq_valid;	// @[UserYanker.scala:48:17]
  wire [3:0]       _QueueCompatibility_25_io_deq_bits_tl_state_size;	// @[UserYanker.scala:48:17]
  wire [7:0]       _QueueCompatibility_25_io_deq_bits_tl_state_source;	// @[UserYanker.scala:48:17]
  wire [3:0]       _QueueCompatibility_25_io_deq_bits_extra_id;	// @[UserYanker.scala:48:17]
  wire             _QueueCompatibility_24_io_enq_ready;	// @[UserYanker.scala:48:17]
  wire             _QueueCompatibility_24_io_deq_valid;	// @[UserYanker.scala:48:17]
  wire [3:0]       _QueueCompatibility_24_io_deq_bits_tl_state_size;	// @[UserYanker.scala:48:17]
  wire [7:0]       _QueueCompatibility_24_io_deq_bits_tl_state_source;	// @[UserYanker.scala:48:17]
  wire [3:0]       _QueueCompatibility_24_io_deq_bits_extra_id;	// @[UserYanker.scala:48:17]
  wire             _QueueCompatibility_23_io_enq_ready;	// @[UserYanker.scala:48:17]
  wire             _QueueCompatibility_23_io_deq_valid;	// @[UserYanker.scala:48:17]
  wire [3:0]       _QueueCompatibility_23_io_deq_bits_tl_state_size;	// @[UserYanker.scala:48:17]
  wire [7:0]       _QueueCompatibility_23_io_deq_bits_tl_state_source;	// @[UserYanker.scala:48:17]
  wire [3:0]       _QueueCompatibility_23_io_deq_bits_extra_id;	// @[UserYanker.scala:48:17]
  wire             _QueueCompatibility_22_io_enq_ready;	// @[UserYanker.scala:48:17]
  wire             _QueueCompatibility_22_io_deq_valid;	// @[UserYanker.scala:48:17]
  wire [3:0]       _QueueCompatibility_22_io_deq_bits_tl_state_size;	// @[UserYanker.scala:48:17]
  wire [7:0]       _QueueCompatibility_22_io_deq_bits_tl_state_source;	// @[UserYanker.scala:48:17]
  wire [3:0]       _QueueCompatibility_22_io_deq_bits_extra_id;	// @[UserYanker.scala:48:17]
  wire             _QueueCompatibility_21_io_enq_ready;	// @[UserYanker.scala:48:17]
  wire             _QueueCompatibility_21_io_deq_valid;	// @[UserYanker.scala:48:17]
  wire [3:0]       _QueueCompatibility_21_io_deq_bits_tl_state_size;	// @[UserYanker.scala:48:17]
  wire [7:0]       _QueueCompatibility_21_io_deq_bits_tl_state_source;	// @[UserYanker.scala:48:17]
  wire [3:0]       _QueueCompatibility_21_io_deq_bits_extra_id;	// @[UserYanker.scala:48:17]
  wire             _QueueCompatibility_20_io_enq_ready;	// @[UserYanker.scala:48:17]
  wire             _QueueCompatibility_20_io_deq_valid;	// @[UserYanker.scala:48:17]
  wire [3:0]       _QueueCompatibility_20_io_deq_bits_tl_state_size;	// @[UserYanker.scala:48:17]
  wire [7:0]       _QueueCompatibility_20_io_deq_bits_tl_state_source;	// @[UserYanker.scala:48:17]
  wire [3:0]       _QueueCompatibility_20_io_deq_bits_extra_id;	// @[UserYanker.scala:48:17]
  wire             _QueueCompatibility_19_io_enq_ready;	// @[UserYanker.scala:48:17]
  wire             _QueueCompatibility_19_io_deq_valid;	// @[UserYanker.scala:48:17]
  wire [3:0]       _QueueCompatibility_19_io_deq_bits_tl_state_size;	// @[UserYanker.scala:48:17]
  wire [7:0]       _QueueCompatibility_19_io_deq_bits_tl_state_source;	// @[UserYanker.scala:48:17]
  wire [3:0]       _QueueCompatibility_19_io_deq_bits_extra_id;	// @[UserYanker.scala:48:17]
  wire             _QueueCompatibility_18_io_enq_ready;	// @[UserYanker.scala:48:17]
  wire             _QueueCompatibility_18_io_deq_valid;	// @[UserYanker.scala:48:17]
  wire [3:0]       _QueueCompatibility_18_io_deq_bits_tl_state_size;	// @[UserYanker.scala:48:17]
  wire [7:0]       _QueueCompatibility_18_io_deq_bits_tl_state_source;	// @[UserYanker.scala:48:17]
  wire [3:0]       _QueueCompatibility_18_io_deq_bits_extra_id;	// @[UserYanker.scala:48:17]
  wire             _QueueCompatibility_17_io_enq_ready;	// @[UserYanker.scala:48:17]
  wire             _QueueCompatibility_17_io_deq_valid;	// @[UserYanker.scala:48:17]
  wire [3:0]       _QueueCompatibility_17_io_deq_bits_tl_state_size;	// @[UserYanker.scala:48:17]
  wire [7:0]       _QueueCompatibility_17_io_deq_bits_tl_state_source;	// @[UserYanker.scala:48:17]
  wire [3:0]       _QueueCompatibility_17_io_deq_bits_extra_id;	// @[UserYanker.scala:48:17]
  wire             _QueueCompatibility_16_io_enq_ready;	// @[UserYanker.scala:48:17]
  wire             _QueueCompatibility_16_io_deq_valid;	// @[UserYanker.scala:48:17]
  wire [3:0]       _QueueCompatibility_16_io_deq_bits_tl_state_size;	// @[UserYanker.scala:48:17]
  wire [7:0]       _QueueCompatibility_16_io_deq_bits_tl_state_source;	// @[UserYanker.scala:48:17]
  wire [3:0]       _QueueCompatibility_16_io_deq_bits_extra_id;	// @[UserYanker.scala:48:17]
  wire             _QueueCompatibility_15_io_enq_ready;	// @[UserYanker.scala:48:17]
  wire             _QueueCompatibility_15_io_deq_valid;	// @[UserYanker.scala:48:17]
  wire [3:0]       _QueueCompatibility_15_io_deq_bits_tl_state_size;	// @[UserYanker.scala:48:17]
  wire [7:0]       _QueueCompatibility_15_io_deq_bits_tl_state_source;	// @[UserYanker.scala:48:17]
  wire [3:0]       _QueueCompatibility_15_io_deq_bits_extra_id;	// @[UserYanker.scala:48:17]
  wire             _QueueCompatibility_14_io_enq_ready;	// @[UserYanker.scala:48:17]
  wire             _QueueCompatibility_14_io_deq_valid;	// @[UserYanker.scala:48:17]
  wire [3:0]       _QueueCompatibility_14_io_deq_bits_tl_state_size;	// @[UserYanker.scala:48:17]
  wire [7:0]       _QueueCompatibility_14_io_deq_bits_tl_state_source;	// @[UserYanker.scala:48:17]
  wire [3:0]       _QueueCompatibility_14_io_deq_bits_extra_id;	// @[UserYanker.scala:48:17]
  wire             _QueueCompatibility_13_io_enq_ready;	// @[UserYanker.scala:48:17]
  wire             _QueueCompatibility_13_io_deq_valid;	// @[UserYanker.scala:48:17]
  wire [3:0]       _QueueCompatibility_13_io_deq_bits_tl_state_size;	// @[UserYanker.scala:48:17]
  wire [7:0]       _QueueCompatibility_13_io_deq_bits_tl_state_source;	// @[UserYanker.scala:48:17]
  wire [3:0]       _QueueCompatibility_13_io_deq_bits_extra_id;	// @[UserYanker.scala:48:17]
  wire             _QueueCompatibility_12_io_enq_ready;	// @[UserYanker.scala:48:17]
  wire             _QueueCompatibility_12_io_deq_valid;	// @[UserYanker.scala:48:17]
  wire [3:0]       _QueueCompatibility_12_io_deq_bits_tl_state_size;	// @[UserYanker.scala:48:17]
  wire [7:0]       _QueueCompatibility_12_io_deq_bits_tl_state_source;	// @[UserYanker.scala:48:17]
  wire [3:0]       _QueueCompatibility_12_io_deq_bits_extra_id;	// @[UserYanker.scala:48:17]
  wire             _QueueCompatibility_11_io_enq_ready;	// @[UserYanker.scala:48:17]
  wire             _QueueCompatibility_11_io_deq_valid;	// @[UserYanker.scala:48:17]
  wire [3:0]       _QueueCompatibility_11_io_deq_bits_tl_state_size;	// @[UserYanker.scala:48:17]
  wire [7:0]       _QueueCompatibility_11_io_deq_bits_tl_state_source;	// @[UserYanker.scala:48:17]
  wire [3:0]       _QueueCompatibility_11_io_deq_bits_extra_id;	// @[UserYanker.scala:48:17]
  wire             _QueueCompatibility_10_io_enq_ready;	// @[UserYanker.scala:48:17]
  wire             _QueueCompatibility_10_io_deq_valid;	// @[UserYanker.scala:48:17]
  wire [3:0]       _QueueCompatibility_10_io_deq_bits_tl_state_size;	// @[UserYanker.scala:48:17]
  wire [7:0]       _QueueCompatibility_10_io_deq_bits_tl_state_source;	// @[UserYanker.scala:48:17]
  wire [3:0]       _QueueCompatibility_10_io_deq_bits_extra_id;	// @[UserYanker.scala:48:17]
  wire             _QueueCompatibility_9_io_enq_ready;	// @[UserYanker.scala:48:17]
  wire             _QueueCompatibility_9_io_deq_valid;	// @[UserYanker.scala:48:17]
  wire [3:0]       _QueueCompatibility_9_io_deq_bits_tl_state_size;	// @[UserYanker.scala:48:17]
  wire [7:0]       _QueueCompatibility_9_io_deq_bits_tl_state_source;	// @[UserYanker.scala:48:17]
  wire [3:0]       _QueueCompatibility_9_io_deq_bits_extra_id;	// @[UserYanker.scala:48:17]
  wire             _QueueCompatibility_8_io_enq_ready;	// @[UserYanker.scala:48:17]
  wire             _QueueCompatibility_8_io_deq_valid;	// @[UserYanker.scala:48:17]
  wire [3:0]       _QueueCompatibility_8_io_deq_bits_tl_state_size;	// @[UserYanker.scala:48:17]
  wire [7:0]       _QueueCompatibility_8_io_deq_bits_tl_state_source;	// @[UserYanker.scala:48:17]
  wire [3:0]       _QueueCompatibility_8_io_deq_bits_extra_id;	// @[UserYanker.scala:48:17]
  wire             _QueueCompatibility_7_io_enq_ready;	// @[UserYanker.scala:48:17]
  wire             _QueueCompatibility_7_io_deq_valid;	// @[UserYanker.scala:48:17]
  wire [3:0]       _QueueCompatibility_7_io_deq_bits_tl_state_size;	// @[UserYanker.scala:48:17]
  wire [7:0]       _QueueCompatibility_7_io_deq_bits_tl_state_source;	// @[UserYanker.scala:48:17]
  wire [3:0]       _QueueCompatibility_7_io_deq_bits_extra_id;	// @[UserYanker.scala:48:17]
  wire             _QueueCompatibility_6_io_enq_ready;	// @[UserYanker.scala:48:17]
  wire             _QueueCompatibility_6_io_deq_valid;	// @[UserYanker.scala:48:17]
  wire [3:0]       _QueueCompatibility_6_io_deq_bits_tl_state_size;	// @[UserYanker.scala:48:17]
  wire [7:0]       _QueueCompatibility_6_io_deq_bits_tl_state_source;	// @[UserYanker.scala:48:17]
  wire [3:0]       _QueueCompatibility_6_io_deq_bits_extra_id;	// @[UserYanker.scala:48:17]
  wire             _QueueCompatibility_5_io_enq_ready;	// @[UserYanker.scala:48:17]
  wire             _QueueCompatibility_5_io_deq_valid;	// @[UserYanker.scala:48:17]
  wire [3:0]       _QueueCompatibility_5_io_deq_bits_tl_state_size;	// @[UserYanker.scala:48:17]
  wire [7:0]       _QueueCompatibility_5_io_deq_bits_tl_state_source;	// @[UserYanker.scala:48:17]
  wire [3:0]       _QueueCompatibility_5_io_deq_bits_extra_id;	// @[UserYanker.scala:48:17]
  wire             _QueueCompatibility_4_io_enq_ready;	// @[UserYanker.scala:48:17]
  wire             _QueueCompatibility_4_io_deq_valid;	// @[UserYanker.scala:48:17]
  wire [3:0]       _QueueCompatibility_4_io_deq_bits_tl_state_size;	// @[UserYanker.scala:48:17]
  wire [7:0]       _QueueCompatibility_4_io_deq_bits_tl_state_source;	// @[UserYanker.scala:48:17]
  wire [3:0]       _QueueCompatibility_4_io_deq_bits_extra_id;	// @[UserYanker.scala:48:17]
  wire             _QueueCompatibility_3_io_enq_ready;	// @[UserYanker.scala:48:17]
  wire             _QueueCompatibility_3_io_deq_valid;	// @[UserYanker.scala:48:17]
  wire [3:0]       _QueueCompatibility_3_io_deq_bits_tl_state_size;	// @[UserYanker.scala:48:17]
  wire [7:0]       _QueueCompatibility_3_io_deq_bits_tl_state_source;	// @[UserYanker.scala:48:17]
  wire [3:0]       _QueueCompatibility_3_io_deq_bits_extra_id;	// @[UserYanker.scala:48:17]
  wire             _QueueCompatibility_2_io_enq_ready;	// @[UserYanker.scala:48:17]
  wire             _QueueCompatibility_2_io_deq_valid;	// @[UserYanker.scala:48:17]
  wire [3:0]       _QueueCompatibility_2_io_deq_bits_tl_state_size;	// @[UserYanker.scala:48:17]
  wire [7:0]       _QueueCompatibility_2_io_deq_bits_tl_state_source;	// @[UserYanker.scala:48:17]
  wire [3:0]       _QueueCompatibility_2_io_deq_bits_extra_id;	// @[UserYanker.scala:48:17]
  wire             _QueueCompatibility_1_io_enq_ready;	// @[UserYanker.scala:48:17]
  wire             _QueueCompatibility_1_io_deq_valid;	// @[UserYanker.scala:48:17]
  wire [3:0]       _QueueCompatibility_1_io_deq_bits_tl_state_size;	// @[UserYanker.scala:48:17]
  wire [7:0]       _QueueCompatibility_1_io_deq_bits_tl_state_source;	// @[UserYanker.scala:48:17]
  wire [3:0]       _QueueCompatibility_1_io_deq_bits_extra_id;	// @[UserYanker.scala:48:17]
  wire             _QueueCompatibility_io_enq_ready;	// @[UserYanker.scala:48:17]
  wire             _QueueCompatibility_io_deq_valid;	// @[UserYanker.scala:48:17]
  wire [3:0]       _QueueCompatibility_io_deq_bits_tl_state_size;	// @[UserYanker.scala:48:17]
  wire [7:0]       _QueueCompatibility_io_deq_bits_tl_state_source;	// @[UserYanker.scala:48:17]
  wire [3:0]       _QueueCompatibility_io_deq_bits_extra_id;	// @[UserYanker.scala:48:17]
  wire [15:0]      _GEN = {{_QueueCompatibility_15_io_enq_ready}, {_QueueCompatibility_14_io_enq_ready}, {_QueueCompatibility_13_io_enq_ready}, {_QueueCompatibility_12_io_enq_ready}, {_QueueCompatibility_11_io_enq_ready}, {_QueueCompatibility_10_io_enq_ready}, {_QueueCompatibility_9_io_enq_ready}, {_QueueCompatibility_8_io_enq_ready}, {_QueueCompatibility_7_io_enq_ready}, {_QueueCompatibility_6_io_enq_ready}, {_QueueCompatibility_5_io_enq_ready}, {_QueueCompatibility_4_io_enq_ready}, {_QueueCompatibility_3_io_enq_ready}, {_QueueCompatibility_2_io_enq_ready}, {_QueueCompatibility_1_io_enq_ready}, {_QueueCompatibility_io_enq_ready}};	// @[UserYanker.scala:48:17, :57:36]
  wire             _GEN_0 = _GEN[auto_in_ar_bits_id];	// @[UserYanker.scala:57:36]
  wire [15:0][3:0] _GEN_1 = {{_QueueCompatibility_15_io_deq_bits_tl_state_size}, {_QueueCompatibility_14_io_deq_bits_tl_state_size}, {_QueueCompatibility_13_io_deq_bits_tl_state_size}, {_QueueCompatibility_12_io_deq_bits_tl_state_size}, {_QueueCompatibility_11_io_deq_bits_tl_state_size}, {_QueueCompatibility_10_io_deq_bits_tl_state_size}, {_QueueCompatibility_9_io_deq_bits_tl_state_size}, {_QueueCompatibility_8_io_deq_bits_tl_state_size}, {_QueueCompatibility_7_io_deq_bits_tl_state_size}, {_QueueCompatibility_6_io_deq_bits_tl_state_size}, {_QueueCompatibility_5_io_deq_bits_tl_state_size}, {_QueueCompatibility_4_io_deq_bits_tl_state_size}, {_QueueCompatibility_3_io_deq_bits_tl_state_size}, {_QueueCompatibility_2_io_deq_bits_tl_state_size}, {_QueueCompatibility_1_io_deq_bits_tl_state_size}, {_QueueCompatibility_io_deq_bits_tl_state_size}};	// @[BundleMap.scala:247:19, UserYanker.scala:48:17]
  wire [15:0][7:0] _GEN_2 = {{_QueueCompatibility_15_io_deq_bits_tl_state_source}, {_QueueCompatibility_14_io_deq_bits_tl_state_source}, {_QueueCompatibility_13_io_deq_bits_tl_state_source}, {_QueueCompatibility_12_io_deq_bits_tl_state_source}, {_QueueCompatibility_11_io_deq_bits_tl_state_source}, {_QueueCompatibility_10_io_deq_bits_tl_state_source}, {_QueueCompatibility_9_io_deq_bits_tl_state_source}, {_QueueCompatibility_8_io_deq_bits_tl_state_source}, {_QueueCompatibility_7_io_deq_bits_tl_state_source}, {_QueueCompatibility_6_io_deq_bits_tl_state_source}, {_QueueCompatibility_5_io_deq_bits_tl_state_source}, {_QueueCompatibility_4_io_deq_bits_tl_state_source}, {_QueueCompatibility_3_io_deq_bits_tl_state_source}, {_QueueCompatibility_2_io_deq_bits_tl_state_source}, {_QueueCompatibility_1_io_deq_bits_tl_state_source}, {_QueueCompatibility_io_deq_bits_tl_state_source}};	// @[BundleMap.scala:247:19, UserYanker.scala:48:17]
  wire [15:0][3:0] _GEN_3 = {{_QueueCompatibility_15_io_deq_bits_extra_id}, {_QueueCompatibility_14_io_deq_bits_extra_id}, {_QueueCompatibility_13_io_deq_bits_extra_id}, {_QueueCompatibility_12_io_deq_bits_extra_id}, {_QueueCompatibility_11_io_deq_bits_extra_id}, {_QueueCompatibility_10_io_deq_bits_extra_id}, {_QueueCompatibility_9_io_deq_bits_extra_id}, {_QueueCompatibility_8_io_deq_bits_extra_id}, {_QueueCompatibility_7_io_deq_bits_extra_id}, {_QueueCompatibility_6_io_deq_bits_extra_id}, {_QueueCompatibility_5_io_deq_bits_extra_id}, {_QueueCompatibility_4_io_deq_bits_extra_id}, {_QueueCompatibility_3_io_deq_bits_extra_id}, {_QueueCompatibility_2_io_deq_bits_extra_id}, {_QueueCompatibility_1_io_deq_bits_extra_id}, {_QueueCompatibility_io_deq_bits_extra_id}};	// @[BundleMap.scala:247:19, UserYanker.scala:48:17]
  wire             _T_80 = auto_out_r_valid & auto_in_r_ready;	// @[UserYanker.scala:71:37]
  wire             _T_83 = auto_in_ar_valid & auto_out_ar_ready;	// @[UserYanker.scala:72:37]
  wire [15:0]      _GEN_4 = {{_QueueCompatibility_31_io_enq_ready}, {_QueueCompatibility_30_io_enq_ready}, {_QueueCompatibility_29_io_enq_ready}, {_QueueCompatibility_28_io_enq_ready}, {_QueueCompatibility_27_io_enq_ready}, {_QueueCompatibility_26_io_enq_ready}, {_QueueCompatibility_25_io_enq_ready}, {_QueueCompatibility_24_io_enq_ready}, {_QueueCompatibility_23_io_enq_ready}, {_QueueCompatibility_22_io_enq_ready}, {_QueueCompatibility_21_io_enq_ready}, {_QueueCompatibility_20_io_enq_ready}, {_QueueCompatibility_19_io_enq_ready}, {_QueueCompatibility_18_io_enq_ready}, {_QueueCompatibility_17_io_enq_ready}, {_QueueCompatibility_16_io_enq_ready}};	// @[UserYanker.scala:48:17, :78:36]
  wire             _GEN_5 = _GEN_4[auto_in_aw_bits_id];	// @[UserYanker.scala:78:36]
  `ifndef SYNTHESIS	// @[UserYanker.scala:64:14]
    wire [15:0] _GEN_6 = {{_QueueCompatibility_15_io_deq_valid}, {_QueueCompatibility_14_io_deq_valid}, {_QueueCompatibility_13_io_deq_valid}, {_QueueCompatibility_12_io_deq_valid}, {_QueueCompatibility_11_io_deq_valid}, {_QueueCompatibility_10_io_deq_valid}, {_QueueCompatibility_9_io_deq_valid}, {_QueueCompatibility_8_io_deq_valid}, {_QueueCompatibility_7_io_deq_valid}, {_QueueCompatibility_6_io_deq_valid}, {_QueueCompatibility_5_io_deq_valid}, {_QueueCompatibility_4_io_deq_valid}, {_QueueCompatibility_3_io_deq_valid}, {_QueueCompatibility_2_io_deq_valid}, {_QueueCompatibility_1_io_deq_valid}, {_QueueCompatibility_io_deq_valid}};	// @[UserYanker.scala:48:17, :64:28]
    wire [15:0] _GEN_7 = {{_QueueCompatibility_31_io_deq_valid}, {_QueueCompatibility_30_io_deq_valid}, {_QueueCompatibility_29_io_deq_valid}, {_QueueCompatibility_28_io_deq_valid}, {_QueueCompatibility_27_io_deq_valid}, {_QueueCompatibility_26_io_deq_valid}, {_QueueCompatibility_25_io_deq_valid}, {_QueueCompatibility_24_io_deq_valid}, {_QueueCompatibility_23_io_deq_valid}, {_QueueCompatibility_22_io_deq_valid}, {_QueueCompatibility_21_io_deq_valid}, {_QueueCompatibility_20_io_deq_valid}, {_QueueCompatibility_19_io_deq_valid}, {_QueueCompatibility_18_io_deq_valid}, {_QueueCompatibility_17_io_deq_valid}, {_QueueCompatibility_16_io_deq_valid}};	// @[UserYanker.scala:48:17, :85:28]
    always @(posedge clock) begin	// @[UserYanker.scala:64:14]
      if (~reset & ~(~auto_out_r_valid | _GEN_6[auto_out_r_bits_id])) begin	// @[UserYanker.scala:64:{14,15,28}]
        if (`ASSERT_VERBOSE_COND_)	// @[UserYanker.scala:64:14]
          $error("Assertion failed\n    at UserYanker.scala:64 assert (!out.r.valid || r_valid) // Q must be ready faster than the response\n");	// @[UserYanker.scala:64:14]
        if (`STOP_COND_)	// @[UserYanker.scala:64:14]
          $fatal;	// @[UserYanker.scala:64:14]
      end
      if (~reset & ~(~auto_out_b_valid | _GEN_7[auto_out_b_bits_id])) begin	// @[UserYanker.scala:85:{14,15,28}]
        if (`ASSERT_VERBOSE_COND_)	// @[UserYanker.scala:85:14]
          $error("Assertion failed\n    at UserYanker.scala:85 assert (!out.b.valid || b_valid) // Q must be ready faster than the response\n");	// @[UserYanker.scala:85:14]
        if (`STOP_COND_)	// @[UserYanker.scala:85:14]
          $fatal;	// @[UserYanker.scala:85:14]
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  wire [15:0][3:0] _GEN_8 = {{_QueueCompatibility_31_io_deq_bits_tl_state_size}, {_QueueCompatibility_30_io_deq_bits_tl_state_size}, {_QueueCompatibility_29_io_deq_bits_tl_state_size}, {_QueueCompatibility_28_io_deq_bits_tl_state_size}, {_QueueCompatibility_27_io_deq_bits_tl_state_size}, {_QueueCompatibility_26_io_deq_bits_tl_state_size}, {_QueueCompatibility_25_io_deq_bits_tl_state_size}, {_QueueCompatibility_24_io_deq_bits_tl_state_size}, {_QueueCompatibility_23_io_deq_bits_tl_state_size}, {_QueueCompatibility_22_io_deq_bits_tl_state_size}, {_QueueCompatibility_21_io_deq_bits_tl_state_size}, {_QueueCompatibility_20_io_deq_bits_tl_state_size}, {_QueueCompatibility_19_io_deq_bits_tl_state_size}, {_QueueCompatibility_18_io_deq_bits_tl_state_size}, {_QueueCompatibility_17_io_deq_bits_tl_state_size}, {_QueueCompatibility_16_io_deq_bits_tl_state_size}};	// @[BundleMap.scala:247:19, UserYanker.scala:48:17]
  wire [15:0][7:0] _GEN_9 = {{_QueueCompatibility_31_io_deq_bits_tl_state_source}, {_QueueCompatibility_30_io_deq_bits_tl_state_source}, {_QueueCompatibility_29_io_deq_bits_tl_state_source}, {_QueueCompatibility_28_io_deq_bits_tl_state_source}, {_QueueCompatibility_27_io_deq_bits_tl_state_source}, {_QueueCompatibility_26_io_deq_bits_tl_state_source}, {_QueueCompatibility_25_io_deq_bits_tl_state_source}, {_QueueCompatibility_24_io_deq_bits_tl_state_source}, {_QueueCompatibility_23_io_deq_bits_tl_state_source}, {_QueueCompatibility_22_io_deq_bits_tl_state_source}, {_QueueCompatibility_21_io_deq_bits_tl_state_source}, {_QueueCompatibility_20_io_deq_bits_tl_state_source}, {_QueueCompatibility_19_io_deq_bits_tl_state_source}, {_QueueCompatibility_18_io_deq_bits_tl_state_source}, {_QueueCompatibility_17_io_deq_bits_tl_state_source}, {_QueueCompatibility_16_io_deq_bits_tl_state_source}};	// @[BundleMap.scala:247:19, UserYanker.scala:48:17]
  wire [15:0][3:0] _GEN_10 = {{_QueueCompatibility_31_io_deq_bits_extra_id}, {_QueueCompatibility_30_io_deq_bits_extra_id}, {_QueueCompatibility_29_io_deq_bits_extra_id}, {_QueueCompatibility_28_io_deq_bits_extra_id}, {_QueueCompatibility_27_io_deq_bits_extra_id}, {_QueueCompatibility_26_io_deq_bits_extra_id}, {_QueueCompatibility_25_io_deq_bits_extra_id}, {_QueueCompatibility_24_io_deq_bits_extra_id}, {_QueueCompatibility_23_io_deq_bits_extra_id}, {_QueueCompatibility_22_io_deq_bits_extra_id}, {_QueueCompatibility_21_io_deq_bits_extra_id}, {_QueueCompatibility_20_io_deq_bits_extra_id}, {_QueueCompatibility_19_io_deq_bits_extra_id}, {_QueueCompatibility_18_io_deq_bits_extra_id}, {_QueueCompatibility_17_io_deq_bits_extra_id}, {_QueueCompatibility_16_io_deq_bits_extra_id}};	// @[BundleMap.scala:247:19, UserYanker.scala:48:17]
  wire             _T_150 = auto_out_b_valid & auto_in_b_ready;	// @[UserYanker.scala:92:37]
  wire             _T_152 = auto_in_aw_valid & auto_out_aw_ready;	// @[UserYanker.scala:93:37]
  QueueCompatibility QueueCompatibility (	// @[UserYanker.scala:48:17]
    .clock                       (clock),
    .reset                       (reset),
    .io_enq_valid                (_T_83 & auto_in_ar_bits_id == 4'h0),	// @[OneHot.scala:64:12, UserYanker.scala:68:55, :72:{37,53}]
    .io_enq_bits_tl_state_size   (auto_in_ar_bits_echo_tl_state_size),
    .io_enq_bits_tl_state_source (auto_in_ar_bits_echo_tl_state_source),
    .io_enq_bits_extra_id        (auto_in_ar_bits_echo_extra_id),
    .io_deq_ready                (_T_80 & auto_out_r_bits_id == 4'h0 & auto_out_r_bits_last),	// @[OneHot.scala:64:12, UserYanker.scala:69:55, :71:{37,58}]
    .io_enq_ready                (_QueueCompatibility_io_enq_ready),
    .io_deq_valid                (_QueueCompatibility_io_deq_valid),
    .io_deq_bits_tl_state_size   (_QueueCompatibility_io_deq_bits_tl_state_size),
    .io_deq_bits_tl_state_source (_QueueCompatibility_io_deq_bits_tl_state_source),
    .io_deq_bits_extra_id        (_QueueCompatibility_io_deq_bits_extra_id)
  );
  QueueCompatibility QueueCompatibility_1 (	// @[UserYanker.scala:48:17]
    .clock                       (clock),
    .reset                       (reset),
    .io_enq_valid                (_T_83 & auto_in_ar_bits_id == 4'h1),	// @[OneHot.scala:64:12, UserYanker.scala:68:55, :72:{37,53}]
    .io_enq_bits_tl_state_size   (auto_in_ar_bits_echo_tl_state_size),
    .io_enq_bits_tl_state_source (auto_in_ar_bits_echo_tl_state_source),
    .io_enq_bits_extra_id        (auto_in_ar_bits_echo_extra_id),
    .io_deq_ready                (_T_80 & auto_out_r_bits_id == 4'h1 & auto_out_r_bits_last),	// @[OneHot.scala:64:12, UserYanker.scala:69:55, :71:{37,58}]
    .io_enq_ready                (_QueueCompatibility_1_io_enq_ready),
    .io_deq_valid                (_QueueCompatibility_1_io_deq_valid),
    .io_deq_bits_tl_state_size   (_QueueCompatibility_1_io_deq_bits_tl_state_size),
    .io_deq_bits_tl_state_source (_QueueCompatibility_1_io_deq_bits_tl_state_source),
    .io_deq_bits_extra_id        (_QueueCompatibility_1_io_deq_bits_extra_id)
  );
  QueueCompatibility QueueCompatibility_2 (	// @[UserYanker.scala:48:17]
    .clock                       (clock),
    .reset                       (reset),
    .io_enq_valid                (_T_83 & auto_in_ar_bits_id == 4'h2),	// @[OneHot.scala:64:12, UserYanker.scala:68:55, :72:{37,53}]
    .io_enq_bits_tl_state_size   (auto_in_ar_bits_echo_tl_state_size),
    .io_enq_bits_tl_state_source (auto_in_ar_bits_echo_tl_state_source),
    .io_enq_bits_extra_id        (auto_in_ar_bits_echo_extra_id),
    .io_deq_ready                (_T_80 & auto_out_r_bits_id == 4'h2 & auto_out_r_bits_last),	// @[OneHot.scala:64:12, UserYanker.scala:69:55, :71:{37,58}]
    .io_enq_ready                (_QueueCompatibility_2_io_enq_ready),
    .io_deq_valid                (_QueueCompatibility_2_io_deq_valid),
    .io_deq_bits_tl_state_size   (_QueueCompatibility_2_io_deq_bits_tl_state_size),
    .io_deq_bits_tl_state_source (_QueueCompatibility_2_io_deq_bits_tl_state_source),
    .io_deq_bits_extra_id        (_QueueCompatibility_2_io_deq_bits_extra_id)
  );
  QueueCompatibility QueueCompatibility_3 (	// @[UserYanker.scala:48:17]
    .clock                       (clock),
    .reset                       (reset),
    .io_enq_valid                (_T_83 & auto_in_ar_bits_id == 4'h3),	// @[OneHot.scala:64:12, UserYanker.scala:68:55, :72:{37,53}]
    .io_enq_bits_tl_state_size   (auto_in_ar_bits_echo_tl_state_size),
    .io_enq_bits_tl_state_source (auto_in_ar_bits_echo_tl_state_source),
    .io_enq_bits_extra_id        (auto_in_ar_bits_echo_extra_id),
    .io_deq_ready                (_T_80 & auto_out_r_bits_id == 4'h3 & auto_out_r_bits_last),	// @[OneHot.scala:64:12, UserYanker.scala:69:55, :71:{37,58}]
    .io_enq_ready                (_QueueCompatibility_3_io_enq_ready),
    .io_deq_valid                (_QueueCompatibility_3_io_deq_valid),
    .io_deq_bits_tl_state_size   (_QueueCompatibility_3_io_deq_bits_tl_state_size),
    .io_deq_bits_tl_state_source (_QueueCompatibility_3_io_deq_bits_tl_state_source),
    .io_deq_bits_extra_id        (_QueueCompatibility_3_io_deq_bits_extra_id)
  );
  QueueCompatibility QueueCompatibility_4 (	// @[UserYanker.scala:48:17]
    .clock                       (clock),
    .reset                       (reset),
    .io_enq_valid                (_T_83 & auto_in_ar_bits_id == 4'h4),	// @[OneHot.scala:64:12, UserYanker.scala:68:55, :72:{37,53}]
    .io_enq_bits_tl_state_size   (auto_in_ar_bits_echo_tl_state_size),
    .io_enq_bits_tl_state_source (auto_in_ar_bits_echo_tl_state_source),
    .io_enq_bits_extra_id        (auto_in_ar_bits_echo_extra_id),
    .io_deq_ready                (_T_80 & auto_out_r_bits_id == 4'h4 & auto_out_r_bits_last),	// @[OneHot.scala:64:12, UserYanker.scala:69:55, :71:{37,58}]
    .io_enq_ready                (_QueueCompatibility_4_io_enq_ready),
    .io_deq_valid                (_QueueCompatibility_4_io_deq_valid),
    .io_deq_bits_tl_state_size   (_QueueCompatibility_4_io_deq_bits_tl_state_size),
    .io_deq_bits_tl_state_source (_QueueCompatibility_4_io_deq_bits_tl_state_source),
    .io_deq_bits_extra_id        (_QueueCompatibility_4_io_deq_bits_extra_id)
  );
  QueueCompatibility QueueCompatibility_5 (	// @[UserYanker.scala:48:17]
    .clock                       (clock),
    .reset                       (reset),
    .io_enq_valid                (_T_83 & auto_in_ar_bits_id == 4'h5),	// @[OneHot.scala:64:12, UserYanker.scala:68:55, :72:{37,53}]
    .io_enq_bits_tl_state_size   (auto_in_ar_bits_echo_tl_state_size),
    .io_enq_bits_tl_state_source (auto_in_ar_bits_echo_tl_state_source),
    .io_enq_bits_extra_id        (auto_in_ar_bits_echo_extra_id),
    .io_deq_ready                (_T_80 & auto_out_r_bits_id == 4'h5 & auto_out_r_bits_last),	// @[OneHot.scala:64:12, UserYanker.scala:69:55, :71:{37,58}]
    .io_enq_ready                (_QueueCompatibility_5_io_enq_ready),
    .io_deq_valid                (_QueueCompatibility_5_io_deq_valid),
    .io_deq_bits_tl_state_size   (_QueueCompatibility_5_io_deq_bits_tl_state_size),
    .io_deq_bits_tl_state_source (_QueueCompatibility_5_io_deq_bits_tl_state_source),
    .io_deq_bits_extra_id        (_QueueCompatibility_5_io_deq_bits_extra_id)
  );
  QueueCompatibility QueueCompatibility_6 (	// @[UserYanker.scala:48:17]
    .clock                       (clock),
    .reset                       (reset),
    .io_enq_valid                (_T_83 & auto_in_ar_bits_id == 4'h6),	// @[OneHot.scala:64:12, UserYanker.scala:68:55, :72:{37,53}]
    .io_enq_bits_tl_state_size   (auto_in_ar_bits_echo_tl_state_size),
    .io_enq_bits_tl_state_source (auto_in_ar_bits_echo_tl_state_source),
    .io_enq_bits_extra_id        (auto_in_ar_bits_echo_extra_id),
    .io_deq_ready                (_T_80 & auto_out_r_bits_id == 4'h6 & auto_out_r_bits_last),	// @[OneHot.scala:64:12, UserYanker.scala:69:55, :71:{37,58}]
    .io_enq_ready                (_QueueCompatibility_6_io_enq_ready),
    .io_deq_valid                (_QueueCompatibility_6_io_deq_valid),
    .io_deq_bits_tl_state_size   (_QueueCompatibility_6_io_deq_bits_tl_state_size),
    .io_deq_bits_tl_state_source (_QueueCompatibility_6_io_deq_bits_tl_state_source),
    .io_deq_bits_extra_id        (_QueueCompatibility_6_io_deq_bits_extra_id)
  );
  QueueCompatibility QueueCompatibility_7 (	// @[UserYanker.scala:48:17]
    .clock                       (clock),
    .reset                       (reset),
    .io_enq_valid                (_T_83 & auto_in_ar_bits_id == 4'h7),	// @[OneHot.scala:64:12, UserYanker.scala:68:55, :72:{37,53}]
    .io_enq_bits_tl_state_size   (auto_in_ar_bits_echo_tl_state_size),
    .io_enq_bits_tl_state_source (auto_in_ar_bits_echo_tl_state_source),
    .io_enq_bits_extra_id        (auto_in_ar_bits_echo_extra_id),
    .io_deq_ready                (_T_80 & auto_out_r_bits_id == 4'h7 & auto_out_r_bits_last),	// @[OneHot.scala:64:12, UserYanker.scala:69:55, :71:{37,58}]
    .io_enq_ready                (_QueueCompatibility_7_io_enq_ready),
    .io_deq_valid                (_QueueCompatibility_7_io_deq_valid),
    .io_deq_bits_tl_state_size   (_QueueCompatibility_7_io_deq_bits_tl_state_size),
    .io_deq_bits_tl_state_source (_QueueCompatibility_7_io_deq_bits_tl_state_source),
    .io_deq_bits_extra_id        (_QueueCompatibility_7_io_deq_bits_extra_id)
  );
  QueueCompatibility QueueCompatibility_8 (	// @[UserYanker.scala:48:17]
    .clock                       (clock),
    .reset                       (reset),
    .io_enq_valid                (_T_83 & auto_in_ar_bits_id == 4'h8),	// @[OneHot.scala:64:12, UserYanker.scala:68:55, :72:{37,53}]
    .io_enq_bits_tl_state_size   (auto_in_ar_bits_echo_tl_state_size),
    .io_enq_bits_tl_state_source (auto_in_ar_bits_echo_tl_state_source),
    .io_enq_bits_extra_id        (auto_in_ar_bits_echo_extra_id),
    .io_deq_ready                (_T_80 & auto_out_r_bits_id == 4'h8 & auto_out_r_bits_last),	// @[OneHot.scala:64:12, UserYanker.scala:69:55, :71:{37,58}]
    .io_enq_ready                (_QueueCompatibility_8_io_enq_ready),
    .io_deq_valid                (_QueueCompatibility_8_io_deq_valid),
    .io_deq_bits_tl_state_size   (_QueueCompatibility_8_io_deq_bits_tl_state_size),
    .io_deq_bits_tl_state_source (_QueueCompatibility_8_io_deq_bits_tl_state_source),
    .io_deq_bits_extra_id        (_QueueCompatibility_8_io_deq_bits_extra_id)
  );
  QueueCompatibility QueueCompatibility_9 (	// @[UserYanker.scala:48:17]
    .clock                       (clock),
    .reset                       (reset),
    .io_enq_valid                (_T_83 & auto_in_ar_bits_id == 4'h9),	// @[OneHot.scala:64:12, UserYanker.scala:68:55, :72:{37,53}]
    .io_enq_bits_tl_state_size   (auto_in_ar_bits_echo_tl_state_size),
    .io_enq_bits_tl_state_source (auto_in_ar_bits_echo_tl_state_source),
    .io_enq_bits_extra_id        (auto_in_ar_bits_echo_extra_id),
    .io_deq_ready                (_T_80 & auto_out_r_bits_id == 4'h9 & auto_out_r_bits_last),	// @[OneHot.scala:64:12, UserYanker.scala:69:55, :71:{37,58}]
    .io_enq_ready                (_QueueCompatibility_9_io_enq_ready),
    .io_deq_valid                (_QueueCompatibility_9_io_deq_valid),
    .io_deq_bits_tl_state_size   (_QueueCompatibility_9_io_deq_bits_tl_state_size),
    .io_deq_bits_tl_state_source (_QueueCompatibility_9_io_deq_bits_tl_state_source),
    .io_deq_bits_extra_id        (_QueueCompatibility_9_io_deq_bits_extra_id)
  );
  QueueCompatibility QueueCompatibility_10 (	// @[UserYanker.scala:48:17]
    .clock                       (clock),
    .reset                       (reset),
    .io_enq_valid                (_T_83 & auto_in_ar_bits_id == 4'hA),	// @[OneHot.scala:64:12, UserYanker.scala:68:55, :72:{37,53}]
    .io_enq_bits_tl_state_size   (auto_in_ar_bits_echo_tl_state_size),
    .io_enq_bits_tl_state_source (auto_in_ar_bits_echo_tl_state_source),
    .io_enq_bits_extra_id        (auto_in_ar_bits_echo_extra_id),
    .io_deq_ready                (_T_80 & auto_out_r_bits_id == 4'hA & auto_out_r_bits_last),	// @[OneHot.scala:64:12, UserYanker.scala:69:55, :71:{37,58}]
    .io_enq_ready                (_QueueCompatibility_10_io_enq_ready),
    .io_deq_valid                (_QueueCompatibility_10_io_deq_valid),
    .io_deq_bits_tl_state_size   (_QueueCompatibility_10_io_deq_bits_tl_state_size),
    .io_deq_bits_tl_state_source (_QueueCompatibility_10_io_deq_bits_tl_state_source),
    .io_deq_bits_extra_id        (_QueueCompatibility_10_io_deq_bits_extra_id)
  );
  QueueCompatibility QueueCompatibility_11 (	// @[UserYanker.scala:48:17]
    .clock                       (clock),
    .reset                       (reset),
    .io_enq_valid                (_T_83 & auto_in_ar_bits_id == 4'hB),	// @[OneHot.scala:64:12, UserYanker.scala:68:55, :72:{37,53}]
    .io_enq_bits_tl_state_size   (auto_in_ar_bits_echo_tl_state_size),
    .io_enq_bits_tl_state_source (auto_in_ar_bits_echo_tl_state_source),
    .io_enq_bits_extra_id        (auto_in_ar_bits_echo_extra_id),
    .io_deq_ready                (_T_80 & auto_out_r_bits_id == 4'hB & auto_out_r_bits_last),	// @[OneHot.scala:64:12, UserYanker.scala:69:55, :71:{37,58}]
    .io_enq_ready                (_QueueCompatibility_11_io_enq_ready),
    .io_deq_valid                (_QueueCompatibility_11_io_deq_valid),
    .io_deq_bits_tl_state_size   (_QueueCompatibility_11_io_deq_bits_tl_state_size),
    .io_deq_bits_tl_state_source (_QueueCompatibility_11_io_deq_bits_tl_state_source),
    .io_deq_bits_extra_id        (_QueueCompatibility_11_io_deq_bits_extra_id)
  );
  QueueCompatibility QueueCompatibility_12 (	// @[UserYanker.scala:48:17]
    .clock                       (clock),
    .reset                       (reset),
    .io_enq_valid                (_T_83 & auto_in_ar_bits_id == 4'hC),	// @[OneHot.scala:64:12, UserYanker.scala:68:55, :72:{37,53}]
    .io_enq_bits_tl_state_size   (auto_in_ar_bits_echo_tl_state_size),
    .io_enq_bits_tl_state_source (auto_in_ar_bits_echo_tl_state_source),
    .io_enq_bits_extra_id        (auto_in_ar_bits_echo_extra_id),
    .io_deq_ready                (_T_80 & auto_out_r_bits_id == 4'hC & auto_out_r_bits_last),	// @[OneHot.scala:64:12, UserYanker.scala:69:55, :71:{37,58}]
    .io_enq_ready                (_QueueCompatibility_12_io_enq_ready),
    .io_deq_valid                (_QueueCompatibility_12_io_deq_valid),
    .io_deq_bits_tl_state_size   (_QueueCompatibility_12_io_deq_bits_tl_state_size),
    .io_deq_bits_tl_state_source (_QueueCompatibility_12_io_deq_bits_tl_state_source),
    .io_deq_bits_extra_id        (_QueueCompatibility_12_io_deq_bits_extra_id)
  );
  QueueCompatibility QueueCompatibility_13 (	// @[UserYanker.scala:48:17]
    .clock                       (clock),
    .reset                       (reset),
    .io_enq_valid                (_T_83 & auto_in_ar_bits_id == 4'hD),	// @[OneHot.scala:64:12, UserYanker.scala:68:55, :72:{37,53}]
    .io_enq_bits_tl_state_size   (auto_in_ar_bits_echo_tl_state_size),
    .io_enq_bits_tl_state_source (auto_in_ar_bits_echo_tl_state_source),
    .io_enq_bits_extra_id        (auto_in_ar_bits_echo_extra_id),
    .io_deq_ready                (_T_80 & auto_out_r_bits_id == 4'hD & auto_out_r_bits_last),	// @[OneHot.scala:64:12, UserYanker.scala:69:55, :71:{37,58}]
    .io_enq_ready                (_QueueCompatibility_13_io_enq_ready),
    .io_deq_valid                (_QueueCompatibility_13_io_deq_valid),
    .io_deq_bits_tl_state_size   (_QueueCompatibility_13_io_deq_bits_tl_state_size),
    .io_deq_bits_tl_state_source (_QueueCompatibility_13_io_deq_bits_tl_state_source),
    .io_deq_bits_extra_id        (_QueueCompatibility_13_io_deq_bits_extra_id)
  );
  QueueCompatibility QueueCompatibility_14 (	// @[UserYanker.scala:48:17]
    .clock                       (clock),
    .reset                       (reset),
    .io_enq_valid                (_T_83 & auto_in_ar_bits_id == 4'hE),	// @[OneHot.scala:64:12, UserYanker.scala:68:55, :72:{37,53}]
    .io_enq_bits_tl_state_size   (auto_in_ar_bits_echo_tl_state_size),
    .io_enq_bits_tl_state_source (auto_in_ar_bits_echo_tl_state_source),
    .io_enq_bits_extra_id        (auto_in_ar_bits_echo_extra_id),
    .io_deq_ready                (_T_80 & auto_out_r_bits_id == 4'hE & auto_out_r_bits_last),	// @[OneHot.scala:64:12, UserYanker.scala:69:55, :71:{37,58}]
    .io_enq_ready                (_QueueCompatibility_14_io_enq_ready),
    .io_deq_valid                (_QueueCompatibility_14_io_deq_valid),
    .io_deq_bits_tl_state_size   (_QueueCompatibility_14_io_deq_bits_tl_state_size),
    .io_deq_bits_tl_state_source (_QueueCompatibility_14_io_deq_bits_tl_state_source),
    .io_deq_bits_extra_id        (_QueueCompatibility_14_io_deq_bits_extra_id)
  );
  QueueCompatibility QueueCompatibility_15 (	// @[UserYanker.scala:48:17]
    .clock                       (clock),
    .reset                       (reset),
    .io_enq_valid                (_T_83 & (&auto_in_ar_bits_id)),	// @[UserYanker.scala:68:55, :72:{37,53}]
    .io_enq_bits_tl_state_size   (auto_in_ar_bits_echo_tl_state_size),
    .io_enq_bits_tl_state_source (auto_in_ar_bits_echo_tl_state_source),
    .io_enq_bits_extra_id        (auto_in_ar_bits_echo_extra_id),
    .io_deq_ready                (_T_80 & (&auto_out_r_bits_id) & auto_out_r_bits_last),	// @[UserYanker.scala:69:55, :71:{37,58}]
    .io_enq_ready                (_QueueCompatibility_15_io_enq_ready),
    .io_deq_valid                (_QueueCompatibility_15_io_deq_valid),
    .io_deq_bits_tl_state_size   (_QueueCompatibility_15_io_deq_bits_tl_state_size),
    .io_deq_bits_tl_state_source (_QueueCompatibility_15_io_deq_bits_tl_state_source),
    .io_deq_bits_extra_id        (_QueueCompatibility_15_io_deq_bits_extra_id)
  );
  QueueCompatibility QueueCompatibility_16 (	// @[UserYanker.scala:48:17]
    .clock                       (clock),
    .reset                       (reset),
    .io_enq_valid                (_T_152 & auto_in_aw_bits_id == 4'h0),	// @[OneHot.scala:64:12, UserYanker.scala:89:55, :93:{37,53}]
    .io_enq_bits_tl_state_size   (auto_in_aw_bits_echo_tl_state_size),
    .io_enq_bits_tl_state_source (auto_in_aw_bits_echo_tl_state_source),
    .io_enq_bits_extra_id        (auto_in_aw_bits_echo_extra_id),
    .io_deq_ready                (_T_150 & auto_out_b_bits_id == 4'h0),	// @[OneHot.scala:64:12, UserYanker.scala:90:55, :92:{37,53}]
    .io_enq_ready                (_QueueCompatibility_16_io_enq_ready),
    .io_deq_valid                (_QueueCompatibility_16_io_deq_valid),
    .io_deq_bits_tl_state_size   (_QueueCompatibility_16_io_deq_bits_tl_state_size),
    .io_deq_bits_tl_state_source (_QueueCompatibility_16_io_deq_bits_tl_state_source),
    .io_deq_bits_extra_id        (_QueueCompatibility_16_io_deq_bits_extra_id)
  );
  QueueCompatibility QueueCompatibility_17 (	// @[UserYanker.scala:48:17]
    .clock                       (clock),
    .reset                       (reset),
    .io_enq_valid                (_T_152 & auto_in_aw_bits_id == 4'h1),	// @[OneHot.scala:64:12, UserYanker.scala:89:55, :93:{37,53}]
    .io_enq_bits_tl_state_size   (auto_in_aw_bits_echo_tl_state_size),
    .io_enq_bits_tl_state_source (auto_in_aw_bits_echo_tl_state_source),
    .io_enq_bits_extra_id        (auto_in_aw_bits_echo_extra_id),
    .io_deq_ready                (_T_150 & auto_out_b_bits_id == 4'h1),	// @[OneHot.scala:64:12, UserYanker.scala:90:55, :92:{37,53}]
    .io_enq_ready                (_QueueCompatibility_17_io_enq_ready),
    .io_deq_valid                (_QueueCompatibility_17_io_deq_valid),
    .io_deq_bits_tl_state_size   (_QueueCompatibility_17_io_deq_bits_tl_state_size),
    .io_deq_bits_tl_state_source (_QueueCompatibility_17_io_deq_bits_tl_state_source),
    .io_deq_bits_extra_id        (_QueueCompatibility_17_io_deq_bits_extra_id)
  );
  QueueCompatibility QueueCompatibility_18 (	// @[UserYanker.scala:48:17]
    .clock                       (clock),
    .reset                       (reset),
    .io_enq_valid                (_T_152 & auto_in_aw_bits_id == 4'h2),	// @[OneHot.scala:64:12, UserYanker.scala:89:55, :93:{37,53}]
    .io_enq_bits_tl_state_size   (auto_in_aw_bits_echo_tl_state_size),
    .io_enq_bits_tl_state_source (auto_in_aw_bits_echo_tl_state_source),
    .io_enq_bits_extra_id        (auto_in_aw_bits_echo_extra_id),
    .io_deq_ready                (_T_150 & auto_out_b_bits_id == 4'h2),	// @[OneHot.scala:64:12, UserYanker.scala:90:55, :92:{37,53}]
    .io_enq_ready                (_QueueCompatibility_18_io_enq_ready),
    .io_deq_valid                (_QueueCompatibility_18_io_deq_valid),
    .io_deq_bits_tl_state_size   (_QueueCompatibility_18_io_deq_bits_tl_state_size),
    .io_deq_bits_tl_state_source (_QueueCompatibility_18_io_deq_bits_tl_state_source),
    .io_deq_bits_extra_id        (_QueueCompatibility_18_io_deq_bits_extra_id)
  );
  QueueCompatibility QueueCompatibility_19 (	// @[UserYanker.scala:48:17]
    .clock                       (clock),
    .reset                       (reset),
    .io_enq_valid                (_T_152 & auto_in_aw_bits_id == 4'h3),	// @[OneHot.scala:64:12, UserYanker.scala:89:55, :93:{37,53}]
    .io_enq_bits_tl_state_size   (auto_in_aw_bits_echo_tl_state_size),
    .io_enq_bits_tl_state_source (auto_in_aw_bits_echo_tl_state_source),
    .io_enq_bits_extra_id        (auto_in_aw_bits_echo_extra_id),
    .io_deq_ready                (_T_150 & auto_out_b_bits_id == 4'h3),	// @[OneHot.scala:64:12, UserYanker.scala:90:55, :92:{37,53}]
    .io_enq_ready                (_QueueCompatibility_19_io_enq_ready),
    .io_deq_valid                (_QueueCompatibility_19_io_deq_valid),
    .io_deq_bits_tl_state_size   (_QueueCompatibility_19_io_deq_bits_tl_state_size),
    .io_deq_bits_tl_state_source (_QueueCompatibility_19_io_deq_bits_tl_state_source),
    .io_deq_bits_extra_id        (_QueueCompatibility_19_io_deq_bits_extra_id)
  );
  QueueCompatibility QueueCompatibility_20 (	// @[UserYanker.scala:48:17]
    .clock                       (clock),
    .reset                       (reset),
    .io_enq_valid                (_T_152 & auto_in_aw_bits_id == 4'h4),	// @[OneHot.scala:64:12, UserYanker.scala:89:55, :93:{37,53}]
    .io_enq_bits_tl_state_size   (auto_in_aw_bits_echo_tl_state_size),
    .io_enq_bits_tl_state_source (auto_in_aw_bits_echo_tl_state_source),
    .io_enq_bits_extra_id        (auto_in_aw_bits_echo_extra_id),
    .io_deq_ready                (_T_150 & auto_out_b_bits_id == 4'h4),	// @[OneHot.scala:64:12, UserYanker.scala:90:55, :92:{37,53}]
    .io_enq_ready                (_QueueCompatibility_20_io_enq_ready),
    .io_deq_valid                (_QueueCompatibility_20_io_deq_valid),
    .io_deq_bits_tl_state_size   (_QueueCompatibility_20_io_deq_bits_tl_state_size),
    .io_deq_bits_tl_state_source (_QueueCompatibility_20_io_deq_bits_tl_state_source),
    .io_deq_bits_extra_id        (_QueueCompatibility_20_io_deq_bits_extra_id)
  );
  QueueCompatibility QueueCompatibility_21 (	// @[UserYanker.scala:48:17]
    .clock                       (clock),
    .reset                       (reset),
    .io_enq_valid                (_T_152 & auto_in_aw_bits_id == 4'h5),	// @[OneHot.scala:64:12, UserYanker.scala:89:55, :93:{37,53}]
    .io_enq_bits_tl_state_size   (auto_in_aw_bits_echo_tl_state_size),
    .io_enq_bits_tl_state_source (auto_in_aw_bits_echo_tl_state_source),
    .io_enq_bits_extra_id        (auto_in_aw_bits_echo_extra_id),
    .io_deq_ready                (_T_150 & auto_out_b_bits_id == 4'h5),	// @[OneHot.scala:64:12, UserYanker.scala:90:55, :92:{37,53}]
    .io_enq_ready                (_QueueCompatibility_21_io_enq_ready),
    .io_deq_valid                (_QueueCompatibility_21_io_deq_valid),
    .io_deq_bits_tl_state_size   (_QueueCompatibility_21_io_deq_bits_tl_state_size),
    .io_deq_bits_tl_state_source (_QueueCompatibility_21_io_deq_bits_tl_state_source),
    .io_deq_bits_extra_id        (_QueueCompatibility_21_io_deq_bits_extra_id)
  );
  QueueCompatibility QueueCompatibility_22 (	// @[UserYanker.scala:48:17]
    .clock                       (clock),
    .reset                       (reset),
    .io_enq_valid                (_T_152 & auto_in_aw_bits_id == 4'h6),	// @[OneHot.scala:64:12, UserYanker.scala:89:55, :93:{37,53}]
    .io_enq_bits_tl_state_size   (auto_in_aw_bits_echo_tl_state_size),
    .io_enq_bits_tl_state_source (auto_in_aw_bits_echo_tl_state_source),
    .io_enq_bits_extra_id        (auto_in_aw_bits_echo_extra_id),
    .io_deq_ready                (_T_150 & auto_out_b_bits_id == 4'h6),	// @[OneHot.scala:64:12, UserYanker.scala:90:55, :92:{37,53}]
    .io_enq_ready                (_QueueCompatibility_22_io_enq_ready),
    .io_deq_valid                (_QueueCompatibility_22_io_deq_valid),
    .io_deq_bits_tl_state_size   (_QueueCompatibility_22_io_deq_bits_tl_state_size),
    .io_deq_bits_tl_state_source (_QueueCompatibility_22_io_deq_bits_tl_state_source),
    .io_deq_bits_extra_id        (_QueueCompatibility_22_io_deq_bits_extra_id)
  );
  QueueCompatibility QueueCompatibility_23 (	// @[UserYanker.scala:48:17]
    .clock                       (clock),
    .reset                       (reset),
    .io_enq_valid                (_T_152 & auto_in_aw_bits_id == 4'h7),	// @[OneHot.scala:64:12, UserYanker.scala:89:55, :93:{37,53}]
    .io_enq_bits_tl_state_size   (auto_in_aw_bits_echo_tl_state_size),
    .io_enq_bits_tl_state_source (auto_in_aw_bits_echo_tl_state_source),
    .io_enq_bits_extra_id        (auto_in_aw_bits_echo_extra_id),
    .io_deq_ready                (_T_150 & auto_out_b_bits_id == 4'h7),	// @[OneHot.scala:64:12, UserYanker.scala:90:55, :92:{37,53}]
    .io_enq_ready                (_QueueCompatibility_23_io_enq_ready),
    .io_deq_valid                (_QueueCompatibility_23_io_deq_valid),
    .io_deq_bits_tl_state_size   (_QueueCompatibility_23_io_deq_bits_tl_state_size),
    .io_deq_bits_tl_state_source (_QueueCompatibility_23_io_deq_bits_tl_state_source),
    .io_deq_bits_extra_id        (_QueueCompatibility_23_io_deq_bits_extra_id)
  );
  QueueCompatibility QueueCompatibility_24 (	// @[UserYanker.scala:48:17]
    .clock                       (clock),
    .reset                       (reset),
    .io_enq_valid                (_T_152 & auto_in_aw_bits_id == 4'h8),	// @[OneHot.scala:64:12, UserYanker.scala:89:55, :93:{37,53}]
    .io_enq_bits_tl_state_size   (auto_in_aw_bits_echo_tl_state_size),
    .io_enq_bits_tl_state_source (auto_in_aw_bits_echo_tl_state_source),
    .io_enq_bits_extra_id        (auto_in_aw_bits_echo_extra_id),
    .io_deq_ready                (_T_150 & auto_out_b_bits_id == 4'h8),	// @[OneHot.scala:64:12, UserYanker.scala:90:55, :92:{37,53}]
    .io_enq_ready                (_QueueCompatibility_24_io_enq_ready),
    .io_deq_valid                (_QueueCompatibility_24_io_deq_valid),
    .io_deq_bits_tl_state_size   (_QueueCompatibility_24_io_deq_bits_tl_state_size),
    .io_deq_bits_tl_state_source (_QueueCompatibility_24_io_deq_bits_tl_state_source),
    .io_deq_bits_extra_id        (_QueueCompatibility_24_io_deq_bits_extra_id)
  );
  QueueCompatibility QueueCompatibility_25 (	// @[UserYanker.scala:48:17]
    .clock                       (clock),
    .reset                       (reset),
    .io_enq_valid                (_T_152 & auto_in_aw_bits_id == 4'h9),	// @[OneHot.scala:64:12, UserYanker.scala:89:55, :93:{37,53}]
    .io_enq_bits_tl_state_size   (auto_in_aw_bits_echo_tl_state_size),
    .io_enq_bits_tl_state_source (auto_in_aw_bits_echo_tl_state_source),
    .io_enq_bits_extra_id        (auto_in_aw_bits_echo_extra_id),
    .io_deq_ready                (_T_150 & auto_out_b_bits_id == 4'h9),	// @[OneHot.scala:64:12, UserYanker.scala:90:55, :92:{37,53}]
    .io_enq_ready                (_QueueCompatibility_25_io_enq_ready),
    .io_deq_valid                (_QueueCompatibility_25_io_deq_valid),
    .io_deq_bits_tl_state_size   (_QueueCompatibility_25_io_deq_bits_tl_state_size),
    .io_deq_bits_tl_state_source (_QueueCompatibility_25_io_deq_bits_tl_state_source),
    .io_deq_bits_extra_id        (_QueueCompatibility_25_io_deq_bits_extra_id)
  );
  QueueCompatibility QueueCompatibility_26 (	// @[UserYanker.scala:48:17]
    .clock                       (clock),
    .reset                       (reset),
    .io_enq_valid                (_T_152 & auto_in_aw_bits_id == 4'hA),	// @[OneHot.scala:64:12, UserYanker.scala:89:55, :93:{37,53}]
    .io_enq_bits_tl_state_size   (auto_in_aw_bits_echo_tl_state_size),
    .io_enq_bits_tl_state_source (auto_in_aw_bits_echo_tl_state_source),
    .io_enq_bits_extra_id        (auto_in_aw_bits_echo_extra_id),
    .io_deq_ready                (_T_150 & auto_out_b_bits_id == 4'hA),	// @[OneHot.scala:64:12, UserYanker.scala:90:55, :92:{37,53}]
    .io_enq_ready                (_QueueCompatibility_26_io_enq_ready),
    .io_deq_valid                (_QueueCompatibility_26_io_deq_valid),
    .io_deq_bits_tl_state_size   (_QueueCompatibility_26_io_deq_bits_tl_state_size),
    .io_deq_bits_tl_state_source (_QueueCompatibility_26_io_deq_bits_tl_state_source),
    .io_deq_bits_extra_id        (_QueueCompatibility_26_io_deq_bits_extra_id)
  );
  QueueCompatibility QueueCompatibility_27 (	// @[UserYanker.scala:48:17]
    .clock                       (clock),
    .reset                       (reset),
    .io_enq_valid                (_T_152 & auto_in_aw_bits_id == 4'hB),	// @[OneHot.scala:64:12, UserYanker.scala:89:55, :93:{37,53}]
    .io_enq_bits_tl_state_size   (auto_in_aw_bits_echo_tl_state_size),
    .io_enq_bits_tl_state_source (auto_in_aw_bits_echo_tl_state_source),
    .io_enq_bits_extra_id        (auto_in_aw_bits_echo_extra_id),
    .io_deq_ready                (_T_150 & auto_out_b_bits_id == 4'hB),	// @[OneHot.scala:64:12, UserYanker.scala:90:55, :92:{37,53}]
    .io_enq_ready                (_QueueCompatibility_27_io_enq_ready),
    .io_deq_valid                (_QueueCompatibility_27_io_deq_valid),
    .io_deq_bits_tl_state_size   (_QueueCompatibility_27_io_deq_bits_tl_state_size),
    .io_deq_bits_tl_state_source (_QueueCompatibility_27_io_deq_bits_tl_state_source),
    .io_deq_bits_extra_id        (_QueueCompatibility_27_io_deq_bits_extra_id)
  );
  QueueCompatibility QueueCompatibility_28 (	// @[UserYanker.scala:48:17]
    .clock                       (clock),
    .reset                       (reset),
    .io_enq_valid                (_T_152 & auto_in_aw_bits_id == 4'hC),	// @[OneHot.scala:64:12, UserYanker.scala:89:55, :93:{37,53}]
    .io_enq_bits_tl_state_size   (auto_in_aw_bits_echo_tl_state_size),
    .io_enq_bits_tl_state_source (auto_in_aw_bits_echo_tl_state_source),
    .io_enq_bits_extra_id        (auto_in_aw_bits_echo_extra_id),
    .io_deq_ready                (_T_150 & auto_out_b_bits_id == 4'hC),	// @[OneHot.scala:64:12, UserYanker.scala:90:55, :92:{37,53}]
    .io_enq_ready                (_QueueCompatibility_28_io_enq_ready),
    .io_deq_valid                (_QueueCompatibility_28_io_deq_valid),
    .io_deq_bits_tl_state_size   (_QueueCompatibility_28_io_deq_bits_tl_state_size),
    .io_deq_bits_tl_state_source (_QueueCompatibility_28_io_deq_bits_tl_state_source),
    .io_deq_bits_extra_id        (_QueueCompatibility_28_io_deq_bits_extra_id)
  );
  QueueCompatibility QueueCompatibility_29 (	// @[UserYanker.scala:48:17]
    .clock                       (clock),
    .reset                       (reset),
    .io_enq_valid                (_T_152 & auto_in_aw_bits_id == 4'hD),	// @[OneHot.scala:64:12, UserYanker.scala:89:55, :93:{37,53}]
    .io_enq_bits_tl_state_size   (auto_in_aw_bits_echo_tl_state_size),
    .io_enq_bits_tl_state_source (auto_in_aw_bits_echo_tl_state_source),
    .io_enq_bits_extra_id        (auto_in_aw_bits_echo_extra_id),
    .io_deq_ready                (_T_150 & auto_out_b_bits_id == 4'hD),	// @[OneHot.scala:64:12, UserYanker.scala:90:55, :92:{37,53}]
    .io_enq_ready                (_QueueCompatibility_29_io_enq_ready),
    .io_deq_valid                (_QueueCompatibility_29_io_deq_valid),
    .io_deq_bits_tl_state_size   (_QueueCompatibility_29_io_deq_bits_tl_state_size),
    .io_deq_bits_tl_state_source (_QueueCompatibility_29_io_deq_bits_tl_state_source),
    .io_deq_bits_extra_id        (_QueueCompatibility_29_io_deq_bits_extra_id)
  );
  QueueCompatibility QueueCompatibility_30 (	// @[UserYanker.scala:48:17]
    .clock                       (clock),
    .reset                       (reset),
    .io_enq_valid                (_T_152 & auto_in_aw_bits_id == 4'hE),	// @[OneHot.scala:64:12, UserYanker.scala:89:55, :93:{37,53}]
    .io_enq_bits_tl_state_size   (auto_in_aw_bits_echo_tl_state_size),
    .io_enq_bits_tl_state_source (auto_in_aw_bits_echo_tl_state_source),
    .io_enq_bits_extra_id        (auto_in_aw_bits_echo_extra_id),
    .io_deq_ready                (_T_150 & auto_out_b_bits_id == 4'hE),	// @[OneHot.scala:64:12, UserYanker.scala:90:55, :92:{37,53}]
    .io_enq_ready                (_QueueCompatibility_30_io_enq_ready),
    .io_deq_valid                (_QueueCompatibility_30_io_deq_valid),
    .io_deq_bits_tl_state_size   (_QueueCompatibility_30_io_deq_bits_tl_state_size),
    .io_deq_bits_tl_state_source (_QueueCompatibility_30_io_deq_bits_tl_state_source),
    .io_deq_bits_extra_id        (_QueueCompatibility_30_io_deq_bits_extra_id)
  );
  QueueCompatibility QueueCompatibility_31 (	// @[UserYanker.scala:48:17]
    .clock                       (clock),
    .reset                       (reset),
    .io_enq_valid                (_T_152 & (&auto_in_aw_bits_id)),	// @[UserYanker.scala:89:55, :93:{37,53}]
    .io_enq_bits_tl_state_size   (auto_in_aw_bits_echo_tl_state_size),
    .io_enq_bits_tl_state_source (auto_in_aw_bits_echo_tl_state_source),
    .io_enq_bits_extra_id        (auto_in_aw_bits_echo_extra_id),
    .io_deq_ready                (_T_150 & (&auto_out_b_bits_id)),	// @[UserYanker.scala:90:55, :92:{37,53}]
    .io_enq_ready                (_QueueCompatibility_31_io_enq_ready),
    .io_deq_valid                (_QueueCompatibility_31_io_deq_valid),
    .io_deq_bits_tl_state_size   (_QueueCompatibility_31_io_deq_bits_tl_state_size),
    .io_deq_bits_tl_state_source (_QueueCompatibility_31_io_deq_bits_tl_state_source),
    .io_deq_bits_extra_id        (_QueueCompatibility_31_io_deq_bits_extra_id)
  );
  assign auto_in_aw_ready = auto_out_aw_ready & _GEN_5;	// @[UserYanker.scala:78:36]
  assign auto_in_w_ready = auto_out_w_ready;
  assign auto_in_b_valid = auto_out_b_valid;
  assign auto_in_b_bits_id = auto_out_b_bits_id;
  assign auto_in_b_bits_resp = auto_out_b_bits_resp;
  assign auto_in_b_bits_echo_tl_state_size = _GEN_8[auto_out_b_bits_id];	// @[BundleMap.scala:247:19]
  assign auto_in_b_bits_echo_tl_state_source = _GEN_9[auto_out_b_bits_id];	// @[BundleMap.scala:247:19]
  assign auto_in_b_bits_echo_extra_id = _GEN_10[auto_out_b_bits_id];	// @[BundleMap.scala:247:19]
  assign auto_in_ar_ready = auto_out_ar_ready & _GEN_0;	// @[UserYanker.scala:57:36]
  assign auto_in_r_valid = auto_out_r_valid;
  assign auto_in_r_bits_id = auto_out_r_bits_id;
  assign auto_in_r_bits_data = auto_out_r_bits_data;
  assign auto_in_r_bits_resp = auto_out_r_bits_resp;
  assign auto_in_r_bits_echo_tl_state_size = _GEN_1[auto_out_r_bits_id];	// @[BundleMap.scala:247:19]
  assign auto_in_r_bits_echo_tl_state_source = _GEN_2[auto_out_r_bits_id];	// @[BundleMap.scala:247:19]
  assign auto_in_r_bits_echo_extra_id = _GEN_3[auto_out_r_bits_id];	// @[BundleMap.scala:247:19]
  assign auto_in_r_bits_last = auto_out_r_bits_last;
  assign auto_out_aw_valid = auto_in_aw_valid & _GEN_5;	// @[UserYanker.scala:78:36, :79:36]
  assign auto_out_aw_bits_id = auto_in_aw_bits_id;
  assign auto_out_aw_bits_addr = auto_in_aw_bits_addr;
  assign auto_out_aw_bits_len = auto_in_aw_bits_len;
  assign auto_out_aw_bits_size = auto_in_aw_bits_size;
  assign auto_out_aw_bits_burst = auto_in_aw_bits_burst;
  assign auto_out_aw_bits_lock = auto_in_aw_bits_lock;
  assign auto_out_aw_bits_cache = auto_in_aw_bits_cache;
  assign auto_out_aw_bits_prot = auto_in_aw_bits_prot;
  assign auto_out_aw_bits_qos = auto_in_aw_bits_qos;
  assign auto_out_w_valid = auto_in_w_valid;
  assign auto_out_w_bits_data = auto_in_w_bits_data;
  assign auto_out_w_bits_strb = auto_in_w_bits_strb;
  assign auto_out_w_bits_last = auto_in_w_bits_last;
  assign auto_out_b_ready = auto_in_b_ready;
  assign auto_out_ar_valid = auto_in_ar_valid & _GEN_0;	// @[UserYanker.scala:57:36, :58:36]
  assign auto_out_ar_bits_id = auto_in_ar_bits_id;
  assign auto_out_ar_bits_addr = auto_in_ar_bits_addr;
  assign auto_out_ar_bits_len = auto_in_ar_bits_len;
  assign auto_out_ar_bits_size = auto_in_ar_bits_size;
  assign auto_out_ar_bits_burst = auto_in_ar_bits_burst;
  assign auto_out_ar_bits_lock = auto_in_ar_bits_lock;
  assign auto_out_ar_bits_cache = auto_in_ar_bits_cache;
  assign auto_out_ar_bits_prot = auto_in_ar_bits_prot;
  assign auto_out_ar_bits_qos = auto_in_ar_bits_qos;
  assign auto_out_r_ready = auto_in_r_ready;
endmodule

