// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

module BoomDuplicatedDataArray(
  input          clock,
                 io_read_0_valid,
  input  [7:0]   io_read_0_bits_way_en,
  input  [11:0]  io_read_0_bits_addr,
  input          io_write_valid,
  input  [7:0]   io_write_bits_way_en,
  input  [11:0]  io_write_bits_addr,
  input  [1:0]   io_write_bits_wmask,
  input  [127:0] io_write_bits_data,
  output [127:0] io_resp_0_0,
                 io_resp_0_1,
                 io_resp_0_2,
                 io_resp_0_3,
                 io_resp_0_4,
                 io_resp_0_5,
                 io_resp_0_6,
                 io_resp_0_7
);

  wire [127:0] _array_7_0_R0_data;	// @[DescribedSRAM.scala:17:26]
  wire [127:0] _array_6_0_R0_data;	// @[DescribedSRAM.scala:17:26]
  wire [127:0] _array_5_0_R0_data;	// @[DescribedSRAM.scala:17:26]
  wire [127:0] _array_4_0_R0_data;	// @[DescribedSRAM.scala:17:26]
  wire [127:0] _array_3_0_R0_data;	// @[DescribedSRAM.scala:17:26]
  wire [127:0] _array_2_0_R0_data;	// @[DescribedSRAM.scala:17:26]
  wire [127:0] _array_1_0_R0_data;	// @[DescribedSRAM.scala:17:26]
  wire [127:0] _array_0_0_R0_data;	// @[DescribedSRAM.scala:17:26]
  reg  [127:0] io_resp_0_0_REG;	// @[dcache.scala:299:31]
  reg  [127:0] io_resp_0_1_REG;	// @[dcache.scala:299:31]
  reg  [127:0] io_resp_0_2_REG;	// @[dcache.scala:299:31]
  reg  [127:0] io_resp_0_3_REG;	// @[dcache.scala:299:31]
  reg  [127:0] io_resp_0_4_REG;	// @[dcache.scala:299:31]
  reg  [127:0] io_resp_0_5_REG;	// @[dcache.scala:299:31]
  reg  [127:0] io_resp_0_6_REG;	// @[dcache.scala:299:31]
  reg  [127:0] io_resp_0_7_REG;	// @[dcache.scala:299:31]
  always @(posedge clock) begin
    io_resp_0_0_REG <= _array_0_0_R0_data;	// @[DescribedSRAM.scala:17:26, dcache.scala:299:31]
    io_resp_0_1_REG <= _array_1_0_R0_data;	// @[DescribedSRAM.scala:17:26, dcache.scala:299:31]
    io_resp_0_2_REG <= _array_2_0_R0_data;	// @[DescribedSRAM.scala:17:26, dcache.scala:299:31]
    io_resp_0_3_REG <= _array_3_0_R0_data;	// @[DescribedSRAM.scala:17:26, dcache.scala:299:31]
    io_resp_0_4_REG <= _array_4_0_R0_data;	// @[DescribedSRAM.scala:17:26, dcache.scala:299:31]
    io_resp_0_5_REG <= _array_5_0_R0_data;	// @[DescribedSRAM.scala:17:26, dcache.scala:299:31]
    io_resp_0_6_REG <= _array_6_0_R0_data;	// @[DescribedSRAM.scala:17:26, dcache.scala:299:31]
    io_resp_0_7_REG <= _array_7_0_R0_data;	// @[DescribedSRAM.scala:17:26, dcache.scala:299:31]
  end // always @(posedge)
  `ifndef SYNTHESIS
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM_0;
    logic [31:0] _RANDOM_1;
    logic [31:0] _RANDOM_2;
    logic [31:0] _RANDOM_3;
    logic [31:0] _RANDOM_4;
    logic [31:0] _RANDOM_5;
    logic [31:0] _RANDOM_6;
    logic [31:0] _RANDOM_7;
    logic [31:0] _RANDOM_8;
    logic [31:0] _RANDOM_9;
    logic [31:0] _RANDOM_10;
    logic [31:0] _RANDOM_11;
    logic [31:0] _RANDOM_12;
    logic [31:0] _RANDOM_13;
    logic [31:0] _RANDOM_14;
    logic [31:0] _RANDOM_15;
    logic [31:0] _RANDOM_16;
    logic [31:0] _RANDOM_17;
    logic [31:0] _RANDOM_18;
    logic [31:0] _RANDOM_19;
    logic [31:0] _RANDOM_20;
    logic [31:0] _RANDOM_21;
    logic [31:0] _RANDOM_22;
    logic [31:0] _RANDOM_23;
    logic [31:0] _RANDOM_24;
    logic [31:0] _RANDOM_25;
    logic [31:0] _RANDOM_26;
    logic [31:0] _RANDOM_27;
    logic [31:0] _RANDOM_28;
    logic [31:0] _RANDOM_29;
    logic [31:0] _RANDOM_30;
    logic [31:0] _RANDOM_31;
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        _RANDOM_0 = `RANDOM;
        _RANDOM_1 = `RANDOM;
        _RANDOM_2 = `RANDOM;
        _RANDOM_3 = `RANDOM;
        _RANDOM_4 = `RANDOM;
        _RANDOM_5 = `RANDOM;
        _RANDOM_6 = `RANDOM;
        _RANDOM_7 = `RANDOM;
        _RANDOM_8 = `RANDOM;
        _RANDOM_9 = `RANDOM;
        _RANDOM_10 = `RANDOM;
        _RANDOM_11 = `RANDOM;
        _RANDOM_12 = `RANDOM;
        _RANDOM_13 = `RANDOM;
        _RANDOM_14 = `RANDOM;
        _RANDOM_15 = `RANDOM;
        _RANDOM_16 = `RANDOM;
        _RANDOM_17 = `RANDOM;
        _RANDOM_18 = `RANDOM;
        _RANDOM_19 = `RANDOM;
        _RANDOM_20 = `RANDOM;
        _RANDOM_21 = `RANDOM;
        _RANDOM_22 = `RANDOM;
        _RANDOM_23 = `RANDOM;
        _RANDOM_24 = `RANDOM;
        _RANDOM_25 = `RANDOM;
        _RANDOM_26 = `RANDOM;
        _RANDOM_27 = `RANDOM;
        _RANDOM_28 = `RANDOM;
        _RANDOM_29 = `RANDOM;
        _RANDOM_30 = `RANDOM;
        _RANDOM_31 = `RANDOM;
        io_resp_0_0_REG = {_RANDOM_0, _RANDOM_1, _RANDOM_2, _RANDOM_3};	// @[dcache.scala:299:31]
        io_resp_0_1_REG = {_RANDOM_4, _RANDOM_5, _RANDOM_6, _RANDOM_7};	// @[dcache.scala:299:31]
        io_resp_0_2_REG = {_RANDOM_8, _RANDOM_9, _RANDOM_10, _RANDOM_11};	// @[dcache.scala:299:31]
        io_resp_0_3_REG = {_RANDOM_12, _RANDOM_13, _RANDOM_14, _RANDOM_15};	// @[dcache.scala:299:31]
        io_resp_0_4_REG = {_RANDOM_16, _RANDOM_17, _RANDOM_18, _RANDOM_19};	// @[dcache.scala:299:31]
        io_resp_0_5_REG = {_RANDOM_20, _RANDOM_21, _RANDOM_22, _RANDOM_23};	// @[dcache.scala:299:31]
        io_resp_0_6_REG = {_RANDOM_24, _RANDOM_25, _RANDOM_26, _RANDOM_27};	// @[dcache.scala:299:31]
        io_resp_0_7_REG = {_RANDOM_28, _RANDOM_29, _RANDOM_30, _RANDOM_31};	// @[dcache.scala:299:31]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // not def SYNTHESIS
  array_0_0 array_0_0 (	// @[DescribedSRAM.scala:17:26]
    .R0_addr (io_read_0_bits_addr[11:4]),	// @[dcache.scala:287:38]
    .R0_en   (io_read_0_bits_way_en[0] & io_read_0_valid),	// @[dcache.scala:299:{72,76}]
    .R0_clk  (clock),
    .W0_addr (io_write_bits_addr[11:4]),	// @[dcache.scala:284:34]
    .W0_en   (io_write_bits_way_en[0] & io_write_valid),	// @[dcache.scala:295:{33,37}]
    .W0_clk  (clock),
    .W0_data (io_write_bits_data),
    .W0_mask (io_write_bits_wmask),
    .R0_data (_array_0_0_R0_data)
  );
  array_1_0 array_1_0 (	// @[DescribedSRAM.scala:17:26]
    .R0_addr (io_read_0_bits_addr[11:4]),	// @[dcache.scala:287:38]
    .R0_en   (io_read_0_bits_way_en[1] & io_read_0_valid),	// @[dcache.scala:299:{72,76}]
    .R0_clk  (clock),
    .W0_addr (io_write_bits_addr[11:4]),	// @[dcache.scala:284:34]
    .W0_en   (io_write_bits_way_en[1] & io_write_valid),	// @[dcache.scala:295:{33,37}]
    .W0_clk  (clock),
    .W0_data (io_write_bits_data),
    .W0_mask (io_write_bits_wmask),
    .R0_data (_array_1_0_R0_data)
  );
  array_2_0 array_2_0 (	// @[DescribedSRAM.scala:17:26]
    .R0_addr (io_read_0_bits_addr[11:4]),	// @[dcache.scala:287:38]
    .R0_en   (io_read_0_bits_way_en[2] & io_read_0_valid),	// @[dcache.scala:299:{72,76}]
    .R0_clk  (clock),
    .W0_addr (io_write_bits_addr[11:4]),	// @[dcache.scala:284:34]
    .W0_en   (io_write_bits_way_en[2] & io_write_valid),	// @[dcache.scala:295:{33,37}]
    .W0_clk  (clock),
    .W0_data (io_write_bits_data),
    .W0_mask (io_write_bits_wmask),
    .R0_data (_array_2_0_R0_data)
  );
  array_3_0 array_3_0 (	// @[DescribedSRAM.scala:17:26]
    .R0_addr (io_read_0_bits_addr[11:4]),	// @[dcache.scala:287:38]
    .R0_en   (io_read_0_bits_way_en[3] & io_read_0_valid),	// @[dcache.scala:299:{72,76}]
    .R0_clk  (clock),
    .W0_addr (io_write_bits_addr[11:4]),	// @[dcache.scala:284:34]
    .W0_en   (io_write_bits_way_en[3] & io_write_valid),	// @[dcache.scala:295:{33,37}]
    .W0_clk  (clock),
    .W0_data (io_write_bits_data),
    .W0_mask (io_write_bits_wmask),
    .R0_data (_array_3_0_R0_data)
  );
  array_4_0 array_4_0 (	// @[DescribedSRAM.scala:17:26]
    .R0_addr (io_read_0_bits_addr[11:4]),	// @[dcache.scala:287:38]
    .R0_en   (io_read_0_bits_way_en[4] & io_read_0_valid),	// @[dcache.scala:299:{72,76}]
    .R0_clk  (clock),
    .W0_addr (io_write_bits_addr[11:4]),	// @[dcache.scala:284:34]
    .W0_en   (io_write_bits_way_en[4] & io_write_valid),	// @[dcache.scala:295:{33,37}]
    .W0_clk  (clock),
    .W0_data (io_write_bits_data),
    .W0_mask (io_write_bits_wmask),
    .R0_data (_array_4_0_R0_data)
  );
  array_5_0 array_5_0 (	// @[DescribedSRAM.scala:17:26]
    .R0_addr (io_read_0_bits_addr[11:4]),	// @[dcache.scala:287:38]
    .R0_en   (io_read_0_bits_way_en[5] & io_read_0_valid),	// @[dcache.scala:299:{72,76}]
    .R0_clk  (clock),
    .W0_addr (io_write_bits_addr[11:4]),	// @[dcache.scala:284:34]
    .W0_en   (io_write_bits_way_en[5] & io_write_valid),	// @[dcache.scala:295:{33,37}]
    .W0_clk  (clock),
    .W0_data (io_write_bits_data),
    .W0_mask (io_write_bits_wmask),
    .R0_data (_array_5_0_R0_data)
  );
  array_6_0 array_6_0 (	// @[DescribedSRAM.scala:17:26]
    .R0_addr (io_read_0_bits_addr[11:4]),	// @[dcache.scala:287:38]
    .R0_en   (io_read_0_bits_way_en[6] & io_read_0_valid),	// @[dcache.scala:299:{72,76}]
    .R0_clk  (clock),
    .W0_addr (io_write_bits_addr[11:4]),	// @[dcache.scala:284:34]
    .W0_en   (io_write_bits_way_en[6] & io_write_valid),	// @[dcache.scala:295:{33,37}]
    .W0_clk  (clock),
    .W0_data (io_write_bits_data),
    .W0_mask (io_write_bits_wmask),
    .R0_data (_array_6_0_R0_data)
  );
  array_7_0 array_7_0 (	// @[DescribedSRAM.scala:17:26]
    .R0_addr (io_read_0_bits_addr[11:4]),	// @[dcache.scala:287:38]
    .R0_en   (io_read_0_bits_way_en[7] & io_read_0_valid),	// @[dcache.scala:299:{72,76}]
    .R0_clk  (clock),
    .W0_addr (io_write_bits_addr[11:4]),	// @[dcache.scala:284:34]
    .W0_en   (io_write_bits_way_en[7] & io_write_valid),	// @[dcache.scala:295:{33,37}]
    .W0_clk  (clock),
    .W0_data (io_write_bits_data),
    .W0_mask (io_write_bits_wmask),
    .R0_data (_array_7_0_R0_data)
  );
  assign io_resp_0_0 = io_resp_0_0_REG;	// @[dcache.scala:299:31]
  assign io_resp_0_1 = io_resp_0_1_REG;	// @[dcache.scala:299:31]
  assign io_resp_0_2 = io_resp_0_2_REG;	// @[dcache.scala:299:31]
  assign io_resp_0_3 = io_resp_0_3_REG;	// @[dcache.scala:299:31]
  assign io_resp_0_4 = io_resp_0_4_REG;	// @[dcache.scala:299:31]
  assign io_resp_0_5 = io_resp_0_5_REG;	// @[dcache.scala:299:31]
  assign io_resp_0_6 = io_resp_0_6_REG;	// @[dcache.scala:299:31]
  assign io_resp_0_7 = io_resp_0_7_REG;	// @[dcache.scala:299:31]
endmodule

