// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

module TLBroadcast(
  input         clock,
                reset,
                auto_in_a_valid,
  input  [2:0]  auto_in_a_bits_opcode,
                auto_in_a_bits_param,
                auto_in_a_bits_size,
  input  [5:0]  auto_in_a_bits_source,
  input  [31:0] auto_in_a_bits_address,
  input  [7:0]  auto_in_a_bits_mask,
  input  [63:0] auto_in_a_bits_data,
  input         auto_in_a_bits_corrupt,
                auto_in_b_ready,
                auto_in_c_valid,
  input  [2:0]  auto_in_c_bits_opcode,
                auto_in_c_bits_param,
                auto_in_c_bits_size,
  input  [5:0]  auto_in_c_bits_source,
  input  [31:0] auto_in_c_bits_address,
  input  [63:0] auto_in_c_bits_data,
  input         auto_in_c_bits_corrupt,
                auto_in_d_ready,
                auto_in_e_valid,
  input  [1:0]  auto_in_e_bits_sink,
  input         auto_out_a_ready,
                auto_out_d_valid,
  input  [2:0]  auto_out_d_bits_opcode,
  input  [1:0]  auto_out_d_bits_param,
  input  [2:0]  auto_out_d_bits_size,
  input  [7:0]  auto_out_d_bits_source,
  input         auto_out_d_bits_denied,
  input  [63:0] auto_out_d_bits_data,
  input         auto_out_d_bits_corrupt,
  output        auto_in_a_ready,
                auto_in_b_valid,
  output [1:0]  auto_in_b_bits_param,
  output [31:0] auto_in_b_bits_address,
  output        auto_in_c_ready,
                auto_in_d_valid,
  output [2:0]  auto_in_d_bits_opcode,
  output [1:0]  auto_in_d_bits_param,
  output [2:0]  auto_in_d_bits_size,
  output [5:0]  auto_in_d_bits_source,
  output [1:0]  auto_in_d_bits_sink,
  output        auto_in_d_bits_denied,
  output [63:0] auto_in_d_bits_data,
  output        auto_in_d_bits_corrupt,
                auto_out_a_valid,
  output [2:0]  auto_out_a_bits_opcode,
                auto_out_a_bits_param,
                auto_out_a_bits_size,
  output [7:0]  auto_out_a_bits_source,
  output [31:0] auto_out_a_bits_address,
  output [7:0]  auto_out_a_bits_mask,
  output [63:0] auto_out_a_bits_data,
  output        auto_out_d_ready
);

  reg  [2:0]  counter_2;	// @[Edges.scala:228:27]
  reg         REG;	// @[Broadcast.scala:216:31]
  wire        out_3_ready;	// @[Arbiter.scala:123:31]
  wire        out_1_ready;	// @[Arbiter.scala:123:31]
  wire        out_ready;	// @[Arbiter.scala:123:31]
  wire        bundleIn_0_c_ready;	// @[Broadcast.scala:185:32]
  wire [2:0]  out_1_bits_opcode;	// @[Broadcast.scala:131:21, :132:24, :133:30]
  wire [5:0]  out_1_bits_source;	// @[Broadcast.scala:131:21]
  wire        out_1_earlyValid;	// @[Broadcast.scala:130:48]
  wire        _TLBroadcastTracker_3_io_in_a_ready;	// @[Broadcast.scala:108:15]
  wire        _TLBroadcastTracker_3_io_out_a_valid;	// @[Broadcast.scala:108:15]
  wire [2:0]  _TLBroadcastTracker_3_io_out_a_bits_opcode;	// @[Broadcast.scala:108:15]
  wire [2:0]  _TLBroadcastTracker_3_io_out_a_bits_param;	// @[Broadcast.scala:108:15]
  wire [2:0]  _TLBroadcastTracker_3_io_out_a_bits_size;	// @[Broadcast.scala:108:15]
  wire [7:0]  _TLBroadcastTracker_3_io_out_a_bits_source;	// @[Broadcast.scala:108:15]
  wire [31:0] _TLBroadcastTracker_3_io_out_a_bits_address;	// @[Broadcast.scala:108:15]
  wire [7:0]  _TLBroadcastTracker_3_io_out_a_bits_mask;	// @[Broadcast.scala:108:15]
  wire [63:0] _TLBroadcastTracker_3_io_out_a_bits_data;	// @[Broadcast.scala:108:15]
  wire [5:0]  _TLBroadcastTracker_3_io_source;	// @[Broadcast.scala:108:15]
  wire [25:0] _TLBroadcastTracker_3_io_line;	// @[Broadcast.scala:108:15]
  wire        _TLBroadcastTracker_3_io_idle;	// @[Broadcast.scala:108:15]
  wire        _TLBroadcastTracker_3_io_need_d;	// @[Broadcast.scala:108:15]
  wire        _TLBroadcastTracker_2_io_in_a_ready;	// @[Broadcast.scala:108:15]
  wire        _TLBroadcastTracker_2_io_out_a_valid;	// @[Broadcast.scala:108:15]
  wire [2:0]  _TLBroadcastTracker_2_io_out_a_bits_opcode;	// @[Broadcast.scala:108:15]
  wire [2:0]  _TLBroadcastTracker_2_io_out_a_bits_param;	// @[Broadcast.scala:108:15]
  wire [2:0]  _TLBroadcastTracker_2_io_out_a_bits_size;	// @[Broadcast.scala:108:15]
  wire [7:0]  _TLBroadcastTracker_2_io_out_a_bits_source;	// @[Broadcast.scala:108:15]
  wire [31:0] _TLBroadcastTracker_2_io_out_a_bits_address;	// @[Broadcast.scala:108:15]
  wire [7:0]  _TLBroadcastTracker_2_io_out_a_bits_mask;	// @[Broadcast.scala:108:15]
  wire [63:0] _TLBroadcastTracker_2_io_out_a_bits_data;	// @[Broadcast.scala:108:15]
  wire [5:0]  _TLBroadcastTracker_2_io_source;	// @[Broadcast.scala:108:15]
  wire [25:0] _TLBroadcastTracker_2_io_line;	// @[Broadcast.scala:108:15]
  wire        _TLBroadcastTracker_2_io_idle;	// @[Broadcast.scala:108:15]
  wire        _TLBroadcastTracker_2_io_need_d;	// @[Broadcast.scala:108:15]
  wire        _TLBroadcastTracker_1_io_in_a_ready;	// @[Broadcast.scala:108:15]
  wire        _TLBroadcastTracker_1_io_out_a_valid;	// @[Broadcast.scala:108:15]
  wire [2:0]  _TLBroadcastTracker_1_io_out_a_bits_opcode;	// @[Broadcast.scala:108:15]
  wire [2:0]  _TLBroadcastTracker_1_io_out_a_bits_param;	// @[Broadcast.scala:108:15]
  wire [2:0]  _TLBroadcastTracker_1_io_out_a_bits_size;	// @[Broadcast.scala:108:15]
  wire [7:0]  _TLBroadcastTracker_1_io_out_a_bits_source;	// @[Broadcast.scala:108:15]
  wire [31:0] _TLBroadcastTracker_1_io_out_a_bits_address;	// @[Broadcast.scala:108:15]
  wire [7:0]  _TLBroadcastTracker_1_io_out_a_bits_mask;	// @[Broadcast.scala:108:15]
  wire [63:0] _TLBroadcastTracker_1_io_out_a_bits_data;	// @[Broadcast.scala:108:15]
  wire [5:0]  _TLBroadcastTracker_1_io_source;	// @[Broadcast.scala:108:15]
  wire [25:0] _TLBroadcastTracker_1_io_line;	// @[Broadcast.scala:108:15]
  wire        _TLBroadcastTracker_1_io_idle;	// @[Broadcast.scala:108:15]
  wire        _TLBroadcastTracker_1_io_need_d;	// @[Broadcast.scala:108:15]
  wire        _TLBroadcastTracker_io_in_a_ready;	// @[Broadcast.scala:108:15]
  wire        _TLBroadcastTracker_io_out_a_valid;	// @[Broadcast.scala:108:15]
  wire [2:0]  _TLBroadcastTracker_io_out_a_bits_opcode;	// @[Broadcast.scala:108:15]
  wire [2:0]  _TLBroadcastTracker_io_out_a_bits_param;	// @[Broadcast.scala:108:15]
  wire [2:0]  _TLBroadcastTracker_io_out_a_bits_size;	// @[Broadcast.scala:108:15]
  wire [7:0]  _TLBroadcastTracker_io_out_a_bits_source;	// @[Broadcast.scala:108:15]
  wire [31:0] _TLBroadcastTracker_io_out_a_bits_address;	// @[Broadcast.scala:108:15]
  wire [7:0]  _TLBroadcastTracker_io_out_a_bits_mask;	// @[Broadcast.scala:108:15]
  wire [63:0] _TLBroadcastTracker_io_out_a_bits_data;	// @[Broadcast.scala:108:15]
  wire [5:0]  _TLBroadcastTracker_io_source;	// @[Broadcast.scala:108:15]
  wire [25:0] _TLBroadcastTracker_io_line;	// @[Broadcast.scala:108:15]
  wire        _TLBroadcastTracker_io_idle;	// @[Broadcast.scala:108:15]
  wire        _TLBroadcastTracker_io_need_d;	// @[Broadcast.scala:108:15]
  wire        _BroadcastFilter_io_request_ready;	// @[Broadcast.scala:100:26]
  wire        _BroadcastFilter_io_response_valid;	// @[Broadcast.scala:100:26]
  wire [1:0]  _BroadcastFilter_io_response_bits_mshr;	// @[Broadcast.scala:100:26]
  wire [31:0] _BroadcastFilter_io_response_bits_address;	// @[Broadcast.scala:100:26]
  wire        _BroadcastFilter_io_response_bits_allocOH;	// @[Broadcast.scala:100:26]
  wire        _BroadcastFilter_io_response_bits_needT;	// @[Broadcast.scala:100:26]
  wire        _T_14 = auto_out_d_bits_source[7:6] == 2'h1;	// @[Broadcast.scala:119:37, :120:27, :134:51]
  wire        _T_82 = out_1_ready & out_1_earlyValid;	// @[Arbiter.scala:123:31, Broadcast.scala:130:48, Decoupled.scala:51:35]
  wire [12:0] _GEN = {10'h0, auto_out_d_bits_size};	// @[package.scala:235:71]
  wire [12:0] _beats1_decode_T_1 = 13'h3F << _GEN;	// @[package.scala:235:71]
  reg  [2:0]  counter;	// @[Edges.scala:228:27]
  wire        first = counter == 3'h0;	// @[Edges.scala:228:27, :230:25]
  wire        last = counter == 3'h1 | (out_1_bits_opcode[0] ? ~(_beats1_decode_T_1[5:3]) : 3'h0) == 3'h0;	// @[Broadcast.scala:131:21, :132:24, :133:30, :168:34, Edges.scala:105:36, :220:14, :228:27, :231:{25,37,47}, package.scala:235:{46,71,76}]
  wire [3:0]  _T_24 = {_TLBroadcastTracker_3_io_need_d & _TLBroadcastTracker_3_io_source == out_1_bits_source, _TLBroadcastTracker_2_io_need_d & _TLBroadcastTracker_2_io_source == out_1_bits_source, _TLBroadcastTracker_1_io_need_d & _TLBroadcastTracker_1_io_source == out_1_bits_source, _TLBroadcastTracker_io_need_d & _TLBroadcastTracker_io_source == out_1_bits_source};	// @[Broadcast.scala:108:15, :124:{62,74,102}, :131:21]
  reg  [3:0]  r;	// @[Reg.scala:19:16]
  wire [3:0]  _T_25 = first ? _T_24 : r;	// @[Broadcast.scala:124:102, Edges.scala:230:25, Reg.scala:19:16, package.scala:80:42]
  wire        x1_d_ready = out_1_ready | _T_14;	// @[Arbiter.scala:123:31, Broadcast.scala:120:27, :129:50]
  assign out_1_earlyValid = auto_out_d_valid & ~_T_14;	// @[Broadcast.scala:120:27, :126:31, :130:48]
  assign out_1_bits_source = auto_out_d_bits_source[5:0];	// @[Broadcast.scala:131:21]
  assign out_1_bits_opcode = auto_out_d_bits_source[7] ? (auto_out_d_bits_opcode[0] ? 3'h5 : 3'h6) : auto_out_d_bits_opcode;	// @[Broadcast.scala:119:37, :131:21, :132:{19,24}, :133:{30,36}, Edges.scala:105:36]
  wire        _T_56 = auto_out_d_bits_opcode[0] | ~(auto_out_d_bits_source[7]);	// @[Broadcast.scala:119:37, :132:19, :141:{34,37}, Edges.scala:105:36]
  wire        _T_86 = x1_d_ready & auto_out_d_valid;	// @[Broadcast.scala:129:50, Decoupled.scala:51:35]
  wire        _T_110 = auto_in_c_bits_opcode == 3'h4;	// @[Broadcast.scala:159:45]
  wire        _T_111 = auto_in_c_bits_opcode == 3'h5;	// @[Broadcast.scala:133:36, :160:45]
  wire        _T_113 = auto_in_c_bits_opcode == 3'h6;	// @[Broadcast.scala:133:36, :162:45]
  wire        _T_115 = _TLBroadcastTracker_io_line == auto_in_c_bits_address[31:6];	// @[Broadcast.scala:108:15, :163:{55,78}]
  wire        _T_117 = _TLBroadcastTracker_1_io_line == auto_in_c_bits_address[31:6];	// @[Broadcast.scala:108:15, :163:{55,78}]
  wire        _T_119 = _TLBroadcastTracker_2_io_line == auto_in_c_bits_address[31:6];	// @[Broadcast.scala:108:15, :163:{55,78}]
  wire        _T_121 = _TLBroadcastTracker_3_io_line == auto_in_c_bits_address[31:6];	// @[Broadcast.scala:108:15, :163:{55,78}]
  wire        _T_193 = bundleIn_0_c_ready & auto_in_c_valid;	// @[Broadcast.scala:185:32, Decoupled.scala:51:35]
  wire        _T_187 = _T_110 | _T_111;	// @[Broadcast.scala:159:45, :160:45, :171:52]
  wire        _T_197 = auto_in_c_bits_param == 3'h0;	// @[Broadcast.scala:178:27, Edges.scala:228:27]
  wire        _T_190 = auto_in_c_bits_param == 3'h4;	// @[Broadcast.scala:159:45, :179:27]
  assign bundleIn_0_c_ready = _T_110 | (_T_113 ? out_ready : out_3_ready);	// @[Arbiter.scala:123:31, Broadcast.scala:159:45, :162:45, :185:{32,38}]
  wire        winnerQual_0 = auto_in_c_valid & _T_113;	// @[Broadcast.scala:162:45, :193:79]
  wire        winnerQual_1_0 = auto_in_c_valid & (_T_111 | (&auto_in_c_bits_opcode));	// @[Broadcast.scala:160:45, :161:45, :198:{35,54}]
  wire        _a_mask_T = auto_in_c_bits_size > 3'h2;	// @[Misc.scala:205:21, Mux.scala:81:61]
  wire        a_mask_size = auto_in_c_bits_size[1:0] == 2'h2;	// @[Broadcast.scala:196:25, Misc.scala:208:26, OneHot.scala:63:49]
  wire        a_mask_acc = _a_mask_T | a_mask_size & ~(auto_in_c_bits_address[2]);	// @[Misc.scala:205:21, :208:26, :209:26, :210:20, :214:{29,38}]
  wire        a_mask_acc_1 = _a_mask_T | a_mask_size & auto_in_c_bits_address[2];	// @[Misc.scala:205:21, :208:26, :209:26, :214:{29,38}]
  wire        a_mask_size_1 = auto_in_c_bits_size[1:0] == 2'h1;	// @[Broadcast.scala:134:51, Misc.scala:208:26, OneHot.scala:63:49]
  wire        a_mask_eq_2 = ~(auto_in_c_bits_address[2]) & ~(auto_in_c_bits_address[1]);	// @[Misc.scala:209:26, :210:20, :213:27]
  wire        a_mask_acc_2 = a_mask_acc | a_mask_size_1 & a_mask_eq_2;	// @[Misc.scala:208:26, :213:27, :214:{29,38}]
  wire        a_mask_eq_3 = ~(auto_in_c_bits_address[2]) & auto_in_c_bits_address[1];	// @[Misc.scala:209:26, :210:20, :213:27]
  wire        a_mask_acc_3 = a_mask_acc | a_mask_size_1 & a_mask_eq_3;	// @[Misc.scala:208:26, :213:27, :214:{29,38}]
  wire        a_mask_eq_4 = auto_in_c_bits_address[2] & ~(auto_in_c_bits_address[1]);	// @[Misc.scala:209:26, :210:20, :213:27]
  wire        a_mask_acc_4 = a_mask_acc_1 | a_mask_size_1 & a_mask_eq_4;	// @[Misc.scala:208:26, :213:27, :214:{29,38}]
  wire        a_mask_eq_5 = auto_in_c_bits_address[2] & auto_in_c_bits_address[1];	// @[Misc.scala:209:26, :213:27]
  wire        a_mask_acc_5 = a_mask_acc_1 | a_mask_size_1 & a_mask_eq_5;	// @[Misc.scala:208:26, :213:27, :214:{29,38}]
  reg  [2:0]  beatsLeft;	// @[Arbiter.scala:87:30]
  wire        idle = beatsLeft == 3'h0;	// @[Arbiter.scala:87:30, :88:28, Edges.scala:228:27]
  wire        earlyWinner_1 = ~winnerQual_0 & out_1_earlyValid;	// @[Arbiter.scala:16:61, :97:79, Broadcast.scala:130:48, :193:79]
  wire        _sink_ACancel_earlyValid_T = winnerQual_0 | out_1_earlyValid;	// @[Arbiter.scala:107:36, Broadcast.scala:130:48, :193:79]
  reg         state_0;	// @[Arbiter.scala:116:26]
  reg         state_1;	// @[Arbiter.scala:116:26]
  wire        muxStateEarly_0 = idle ? winnerQual_0 : state_0;	// @[Arbiter.scala:88:28, :116:26, :117:30, Broadcast.scala:193:79]
  wire        muxStateEarly_1 = idle ? earlyWinner_1 : state_1;	// @[Arbiter.scala:88:28, :97:79, :116:26, :117:30]
  assign out_ready = auto_in_d_ready & (idle | state_0);	// @[Arbiter.scala:88:28, :116:26, :121:24, :123:31]
  assign out_1_ready = auto_in_d_ready & (idle ? ~winnerQual_0 : state_1);	// @[Arbiter.scala:16:61, :88:28, :116:26, :121:24, :123:31, Broadcast.scala:193:79]
  wire        out_2_valid = idle ? _sink_ACancel_earlyValid_T : state_0 & winnerQual_0 | state_1 & out_1_earlyValid;	// @[Arbiter.scala:88:28, :107:36, :116:26, :125:29, Broadcast.scala:130:48, :193:79, Mux.scala:27:73]
  wire        out_2_bits_corrupt = muxStateEarly_1 & auto_out_d_bits_corrupt;	// @[Arbiter.scala:117:30, Mux.scala:27:73]
  wire        out_2_bits_denied = muxStateEarly_1 & auto_out_d_bits_denied;	// @[Arbiter.scala:117:30, Mux.scala:27:73]
  wire [1:0]  out_2_bits_sink = muxStateEarly_1 ? {|(_T_25[3:2]), _T_25[3] | _T_25[1]} : 2'h0;	// @[Arbiter.scala:117:30, Broadcast.scala:134:51, Cat.scala:33:92, Mux.scala:27:73, OneHot.scala:30:18, :31:18, :32:{14,28}, package.scala:80:42]
  wire [5:0]  out_2_bits_source = (muxStateEarly_0 ? auto_in_c_bits_source : 6'h0) | (muxStateEarly_1 ? out_1_bits_source : 6'h0);	// @[Arbiter.scala:117:30, Broadcast.scala:131:21, Mux.scala:27:73]
  wire [2:0]  out_2_bits_size = (muxStateEarly_0 ? auto_in_c_bits_size : 3'h0) | (muxStateEarly_1 ? auto_out_d_bits_size : 3'h0);	// @[Arbiter.scala:117:30, Edges.scala:228:27, Mux.scala:27:73]
  wire [1:0]  out_2_bits_param = muxStateEarly_1 ? (auto_out_d_bits_source[7] ? (auto_out_d_bits_opcode[0] ? {1'h0, ~(auto_out_d_bits_source[6])} : 2'h0) : auto_out_d_bits_param) : 2'h0;	// @[Arbiter.scala:117:30, Broadcast.scala:119:37, :131:21, :132:{19,24}, :134:{30,36,51,58}, Edges.scala:105:36, Mux.scala:27:73]
  wire [2:0]  out_2_bits_opcode = (muxStateEarly_0 ? 3'h6 : 3'h0) | (muxStateEarly_1 ? out_1_bits_opcode : 3'h0);	// @[Arbiter.scala:117:30, Broadcast.scala:131:21, :132:24, :133:{30,36}, Edges.scala:228:27, Mux.scala:27:73]
  reg  [2:0]  beatsLeft_1;	// @[Arbiter.scala:87:30]
  wire        idle_1 = beatsLeft_1 == 3'h0;	// @[Arbiter.scala:87:30, :88:28, Edges.scala:228:27]
  wire        _GEN_0 = _TLBroadcastTracker_io_out_a_valid | winnerQual_1_0;	// @[Broadcast.scala:108:15, :198:35, package.scala:245:43]
  wire        _GEN_1 = _TLBroadcastTracker_2_io_out_a_valid | _TLBroadcastTracker_1_io_out_a_valid | _GEN_0;	// @[Broadcast.scala:108:15, package.scala:245:43]
  wire        _GEN_2 = _TLBroadcastTracker_1_io_out_a_valid | _TLBroadcastTracker_io_out_a_valid | winnerQual_1_0;	// @[Broadcast.scala:108:15, :198:35, package.scala:245:43]
  wire        earlyWinner_1_1 = ~winnerQual_1_0 & _TLBroadcastTracker_io_out_a_valid;	// @[Arbiter.scala:16:61, :97:79, Broadcast.scala:108:15, :198:35]
  wire        earlyWinner_1_2 = ~_GEN_0 & _TLBroadcastTracker_1_io_out_a_valid;	// @[Arbiter.scala:16:61, :97:79, Broadcast.scala:108:15, package.scala:245:43]
  wire        earlyWinner_1_3 = ~_GEN_2 & _TLBroadcastTracker_2_io_out_a_valid;	// @[Arbiter.scala:16:61, :97:79, Broadcast.scala:108:15, package.scala:245:43]
  wire        earlyWinner_1_4 = ~_GEN_1 & _TLBroadcastTracker_3_io_out_a_valid;	// @[Arbiter.scala:16:61, :97:79, Broadcast.scala:108:15, package.scala:245:43]
  wire        _sink_ACancel_earlyValid_T_5 = winnerQual_1_0 | _TLBroadcastTracker_io_out_a_valid;	// @[Arbiter.scala:107:36, Broadcast.scala:108:15, :198:35]
  reg         state_1_0;	// @[Arbiter.scala:116:26]
  reg         state_1_1;	// @[Arbiter.scala:116:26]
  reg         state_1_2;	// @[Arbiter.scala:116:26]
  reg         state_1_3;	// @[Arbiter.scala:116:26]
  reg         state_1_4;	// @[Arbiter.scala:116:26]
  wire        muxStateEarly_1_0 = idle_1 ? winnerQual_1_0 : state_1_0;	// @[Arbiter.scala:88:28, :116:26, :117:30, Broadcast.scala:198:35]
  wire        muxStateEarly_1_1 = idle_1 ? earlyWinner_1_1 : state_1_1;	// @[Arbiter.scala:88:28, :97:79, :116:26, :117:30]
  wire        muxStateEarly_1_2 = idle_1 ? earlyWinner_1_2 : state_1_2;	// @[Arbiter.scala:88:28, :97:79, :116:26, :117:30]
  wire        muxStateEarly_1_3 = idle_1 ? earlyWinner_1_3 : state_1_3;	// @[Arbiter.scala:88:28, :97:79, :116:26, :117:30]
  wire        muxStateEarly_1_4 = idle_1 ? earlyWinner_1_4 : state_1_4;	// @[Arbiter.scala:88:28, :97:79, :116:26, :117:30]
  assign out_3_ready = auto_out_a_ready & (idle_1 | state_1_0);	// @[Arbiter.scala:88:28, :116:26, :121:24, :123:31]
  wire        out_8_valid = idle_1 ? _sink_ACancel_earlyValid_T_5 | _TLBroadcastTracker_1_io_out_a_valid | _TLBroadcastTracker_2_io_out_a_valid | _TLBroadcastTracker_3_io_out_a_valid : state_1_0 & winnerQual_1_0 | state_1_1 & _TLBroadcastTracker_io_out_a_valid | state_1_2 & _TLBroadcastTracker_1_io_out_a_valid | state_1_3 & _TLBroadcastTracker_2_io_out_a_valid | state_1_4 & _TLBroadcastTracker_3_io_out_a_valid;	// @[Arbiter.scala:88:28, :107:36, :116:26, :125:{29,56}, Broadcast.scala:108:15, :198:35, Mux.scala:27:73]
  reg  [25:0] REG_1;	// @[Broadcast.scala:217:27]
  reg  [1:0]  REG_2;	// @[Broadcast.scala:218:28]
  wire [31:0] bundleIn_0_b_bits_b_address = {REG_1, 6'h0};	// @[Broadcast.scala:217:27, :226:46, Mux.scala:27:73]
  wire        _WIRE_31_0 = _TLBroadcastTracker_io_line == auto_in_a_bits_address[31:6];	// @[Broadcast.scala:108:15, :237:{62,84}]
  wire        _WIRE_31_1 = _TLBroadcastTracker_1_io_line == auto_in_a_bits_address[31:6];	// @[Broadcast.scala:108:15, :237:{62,84}]
  wire        _WIRE_31_2 = _TLBroadcastTracker_2_io_line == auto_in_a_bits_address[31:6];	// @[Broadcast.scala:108:15, :237:{62,84}]
  wire        _WIRE_31_3 = _TLBroadcastTracker_3_io_line == auto_in_a_bits_address[31:6];	// @[Broadcast.scala:108:15, :237:{62,84}]
  wire [3:0]  _GEN_3 = (|{_WIRE_31_3, _WIRE_31_2, _WIRE_31_1, _WIRE_31_0}) ? {_WIRE_31_3, _WIRE_31_2, _WIRE_31_1, _WIRE_31_0} : {_TLBroadcastTracker_3_io_idle, _TLBroadcastTracker_2_io_idle, _TLBroadcastTracker_1_io_idle, _TLBroadcastTracker_io_idle} & {~(_TLBroadcastTracker_2_io_idle | _TLBroadcastTracker_1_io_idle | _TLBroadcastTracker_io_idle), ~(_TLBroadcastTracker_1_io_idle | _TLBroadcastTracker_io_idle), ~_TLBroadcastTracker_io_idle, 1'h1};	// @[Broadcast.scala:108:15, :237:{62,100}, :238:40, :239:{39,41,64}, :240:30, package.scala:245:43]
  wire [3:0]  _GEN_4 = _GEN_3 & {_TLBroadcastTracker_3_io_in_a_ready, _TLBroadcastTracker_2_io_in_a_ready, _TLBroadcastTracker_1_io_in_a_ready, _TLBroadcastTracker_io_in_a_ready};	// @[Broadcast.scala:108:15, :240:30, :242:41]
  wire        bundleIn_0_a_ready = ((|counter_2) | _BroadcastFilter_io_request_ready) & (|_GEN_4);	// @[Broadcast.scala:100:26, :242:{41,58}, :244:{31,59}, Edges.scala:228:27, :230:25]
  wire        _T_506 = ~REG & _BroadcastFilter_io_response_valid;	// @[Broadcast.scala:100:26, :216:31, :260:35, Decoupled.scala:51:35]
  wire [12:0] _decode_T_5 = 13'h3F << _GEN;	// @[package.scala:235:71]
  wire [12:0] _decode_T_25 = 13'h3F << _TLBroadcastTracker_3_io_out_a_bits_size;	// @[Broadcast.scala:108:15, package.scala:235:71]
  wire [12:0] _decode_T_21 = 13'h3F << _TLBroadcastTracker_2_io_out_a_bits_size;	// @[Broadcast.scala:108:15, package.scala:235:71]
  wire [12:0] _decode_T_17 = 13'h3F << _TLBroadcastTracker_1_io_out_a_bits_size;	// @[Broadcast.scala:108:15, package.scala:235:71]
  wire [12:0] _decode_T_13 = 13'h3F << _TLBroadcastTracker_io_out_a_bits_size;	// @[Broadcast.scala:108:15, package.scala:235:71]
  wire [12:0] _decode_T_9 = 13'h3F << auto_in_c_bits_size;	// @[package.scala:235:71]
  wire [12:0] _beats1_decode_T_9 = 13'h3F << auto_in_a_bits_size;	// @[package.scala:235:71]
  wire        winnerQual_1 = ~winnerQual_0 & out_1_earlyValid;	// @[Arbiter.scala:16:61, :98:79, Broadcast.scala:130:48, :193:79]
  wire        winnerQual_1_1 = ~winnerQual_1_0 & _TLBroadcastTracker_io_out_a_valid;	// @[Arbiter.scala:16:61, :98:79, Broadcast.scala:108:15, :198:35]
  wire        winnerQual_1_2 = ~_GEN_0 & _TLBroadcastTracker_1_io_out_a_valid;	// @[Arbiter.scala:16:61, :98:79, Broadcast.scala:108:15, package.scala:245:43]
  wire        winnerQual_1_3 = ~_GEN_2 & _TLBroadcastTracker_2_io_out_a_valid;	// @[Arbiter.scala:16:61, :98:79, Broadcast.scala:108:15, package.scala:245:43]
  wire        winnerQual_1_4 = ~_GEN_1 & _TLBroadcastTracker_3_io_out_a_valid;	// @[Arbiter.scala:16:61, :98:79, Broadcast.scala:108:15, package.scala:245:43]
  always @(posedge clock) begin
    if (reset) begin
      counter <= 3'h0;	// @[Edges.scala:228:27]
      beatsLeft <= 3'h0;	// @[Arbiter.scala:87:30, Edges.scala:228:27]
      state_0 <= 1'h0;	// @[Arbiter.scala:116:26]
      state_1 <= 1'h0;	// @[Arbiter.scala:116:26]
      beatsLeft_1 <= 3'h0;	// @[Arbiter.scala:87:30, Edges.scala:228:27]
      state_1_0 <= 1'h0;	// @[Arbiter.scala:116:26]
      state_1_1 <= 1'h0;	// @[Arbiter.scala:116:26]
      state_1_2 <= 1'h0;	// @[Arbiter.scala:116:26]
      state_1_3 <= 1'h0;	// @[Arbiter.scala:116:26]
      state_1_4 <= 1'h0;	// @[Arbiter.scala:116:26]
      REG <= 1'h0;	// @[Broadcast.scala:216:31]
      counter_2 <= 3'h0;	// @[Edges.scala:228:27]
    end
    else begin
      if (_T_82) begin	// @[Decoupled.scala:51:35]
        if (first) begin	// @[Edges.scala:230:25]
          if (out_1_bits_opcode[0])	// @[Broadcast.scala:131:21, :132:24, :133:30, Edges.scala:105:36]
            counter <= ~(_beats1_decode_T_1[5:3]);	// @[Edges.scala:228:27, package.scala:235:{46,71,76}]
          else	// @[Edges.scala:105:36]
            counter <= 3'h0;	// @[Edges.scala:228:27]
        end
        else	// @[Edges.scala:230:25]
          counter <= counter - 3'h1;	// @[Edges.scala:228:27, :229:28]
      end
      if (idle & auto_in_d_ready) begin	// @[Arbiter.scala:88:28, :89:24]
        if (winnerQual_1 & out_1_bits_opcode[0])	// @[Arbiter.scala:98:79, :111:73, Broadcast.scala:131:21, :132:24, :133:30, Edges.scala:105:36, :220:14]
          beatsLeft <= ~(_decode_T_5[5:3]);	// @[Arbiter.scala:87:30, package.scala:235:{46,71,76}]
        else	// @[Arbiter.scala:111:73, Edges.scala:220:14]
          beatsLeft <= 3'h0;	// @[Arbiter.scala:87:30, Edges.scala:228:27]
      end
      else	// @[Arbiter.scala:89:24]
        beatsLeft <= beatsLeft - {2'h0, auto_in_d_ready & out_2_valid};	// @[Arbiter.scala:87:30, :113:52, :125:29, Broadcast.scala:134:51, ReadyValidCancel.scala:49:33]
      if (idle) begin	// @[Arbiter.scala:88:28]
        state_0 <= winnerQual_0;	// @[Arbiter.scala:116:26, Broadcast.scala:193:79]
        state_1 <= winnerQual_1;	// @[Arbiter.scala:98:79, :116:26]
      end
      if (idle_1 & auto_out_a_ready)	// @[Arbiter.scala:88:28, :89:24]
        beatsLeft_1 <= (winnerQual_1_0 ? ~(_decode_T_9[5:3]) : 3'h0) | (winnerQual_1_1 & ~(_TLBroadcastTracker_io_out_a_bits_opcode[2]) ? ~(_decode_T_13[5:3]) : 3'h0) | (winnerQual_1_2 & ~(_TLBroadcastTracker_1_io_out_a_bits_opcode[2]) ? ~(_decode_T_17[5:3]) : 3'h0) | (winnerQual_1_3 & ~(_TLBroadcastTracker_2_io_out_a_bits_opcode[2]) ? ~(_decode_T_21[5:3]) : 3'h0) | (winnerQual_1_4 & ~(_TLBroadcastTracker_3_io_out_a_bits_opcode[2]) ? ~(_decode_T_25[5:3]) : 3'h0);	// @[Arbiter.scala:87:30, :98:79, :111:73, :112:44, Broadcast.scala:108:15, :198:35, Edges.scala:91:{28,37}, :220:14, :228:27, package.scala:235:{46,71,76}]
      else	// @[Arbiter.scala:89:24]
        beatsLeft_1 <= beatsLeft_1 - {2'h0, auto_out_a_ready & out_8_valid};	// @[Arbiter.scala:87:30, :113:52, :125:29, Broadcast.scala:134:51, ReadyValidCancel.scala:49:33]
      if (idle_1) begin	// @[Arbiter.scala:88:28]
        state_1_0 <= winnerQual_1_0;	// @[Arbiter.scala:116:26, Broadcast.scala:198:35]
        state_1_1 <= winnerQual_1_1;	// @[Arbiter.scala:98:79, :116:26]
        state_1_2 <= winnerQual_1_2;	// @[Arbiter.scala:98:79, :116:26]
        state_1_3 <= winnerQual_1_3;	// @[Arbiter.scala:98:79, :116:26]
        state_1_4 <= winnerQual_1_4;	// @[Arbiter.scala:98:79, :116:26]
      end
      if (_T_506)	// @[Decoupled.scala:51:35]
        REG <= ~_BroadcastFilter_io_response_bits_allocOH;	// @[Broadcast.scala:100:26, :216:31, :258:54]
      else	// @[Decoupled.scala:51:35]
        REG <= (~(auto_in_b_ready & REG) | ~REG) & REG;	// @[Broadcast.scala:216:31, :228:{26,39,55}, Decoupled.scala:51:35]
      if (bundleIn_0_a_ready & auto_in_a_valid) begin	// @[Broadcast.scala:244:59, Decoupled.scala:51:35]
        if (|counter_2)	// @[Edges.scala:228:27, :230:25]
          counter_2 <= counter_2 - 3'h1;	// @[Edges.scala:228:27, :229:28]
        else if (auto_in_a_bits_opcode[2])	// @[Edges.scala:91:37]
          counter_2 <= 3'h0;	// @[Edges.scala:228:27]
        else	// @[Edges.scala:91:37]
          counter_2 <= ~(_beats1_decode_T_9[5:3]);	// @[Edges.scala:228:27, package.scala:235:{46,71,76}]
      end
    end
    if (first)	// @[Edges.scala:230:25]
      r <= _T_24;	// @[Broadcast.scala:124:102, Reg.scala:19:16]
    if (_T_506) begin	// @[Decoupled.scala:51:35]
      REG_1 <= _BroadcastFilter_io_response_bits_address[31:6];	// @[Broadcast.scala:100:26, :217:27, :263:56]
      if (_BroadcastFilter_io_response_bits_needT)	// @[Broadcast.scala:100:26]
        REG_2 <= 2'h2;	// @[Broadcast.scala:196:25, :218:28]
      else	// @[Broadcast.scala:100:26]
        REG_2 <= 2'h1;	// @[Broadcast.scala:134:51, :218:28]
    end
  end // always @(posedge)
  `ifndef SYNTHESIS
    wire         prefixOR_2 = winnerQual_1_0 | earlyWinner_1_1;	// @[Arbiter.scala:97:79, :104:53, Broadcast.scala:198:35]
    wire         prefixOR_3 = prefixOR_2 | earlyWinner_1_2;	// @[Arbiter.scala:97:79, :104:53]
    wire         _T_305 = winnerQual_1_0 | _TLBroadcastTracker_io_out_a_valid;	// @[Arbiter.scala:108:36, Broadcast.scala:108:15, :198:35]
    always @(posedge clock) begin	// @[Broadcast.scala:126:14]
      if (~reset & ~(~auto_out_d_valid | ~_T_14 | auto_out_d_bits_opcode == 3'h0)) begin	// @[Broadcast.scala:120:27, :126:{14,15,31,39,60}, Edges.scala:228:27]
        if (`ASSERT_VERBOSE_COND_)	// @[Broadcast.scala:126:14]
          $error("Assertion failed\n    at Broadcast.scala:126 assert (!out.d.valid || !d_drop || out.d.bits.opcode === TLMessages.AccessAck)\n");	// @[Broadcast.scala:126:14]
        if (`STOP_COND_)	// @[Broadcast.scala:126:14]
          $fatal;	// @[Broadcast.scala:126:14]
      end
      if (~reset & ~(~out_1_earlyValid | (|_T_25) | out_1_bits_opcode == 3'h6)) begin	// @[Broadcast.scala:130:48, :131:21, :132:24, :133:{30,36}, :138:{14,15,31,47,75}, package.scala:80:42]
        if (`ASSERT_VERBOSE_COND_)	// @[Broadcast.scala:138:14]
          $error("Assertion failed\n    at Broadcast.scala:138 assert (!d_normal.valid || (d_trackerOH.orR || d_normal.bits.opcode === TLMessages.ReleaseAck))\n");	// @[Broadcast.scala:138:14]
        if (`STOP_COND_)	// @[Broadcast.scala:138:14]
          $fatal;	// @[Broadcast.scala:138:14]
      end
      if (~reset & ~(~winnerQual_0 | ~earlyWinner_1)) begin	// @[Arbiter.scala:97:79, :105:{13,61,64,67}, Broadcast.scala:193:79]
        if (`ASSERT_VERBOSE_COND_)	// @[Arbiter.scala:105:13]
          $error("Assertion failed\n    at Arbiter.scala:105 assert((prefixOR zip earlyWinner) map { case (p,w) => !p || !w } reduce {_ && _})\n");	// @[Arbiter.scala:105:13]
        if (`STOP_COND_)	// @[Arbiter.scala:105:13]
          $fatal;	// @[Arbiter.scala:105:13]
      end
      if (~reset & ~(~_sink_ACancel_earlyValid_T | winnerQual_0 | earlyWinner_1)) begin	// @[Arbiter.scala:97:79, :107:{14,15,36,41}, Broadcast.scala:193:79]
        if (`ASSERT_VERBOSE_COND_)	// @[Arbiter.scala:107:14]
          $error("Assertion failed\n    at Arbiter.scala:107 assert (!earlyValids.reduce(_||_) || earlyWinner.reduce(_||_))\n");	// @[Arbiter.scala:107:14]
        if (`STOP_COND_)	// @[Arbiter.scala:107:14]
          $fatal;	// @[Arbiter.scala:107:14]
      end
      if (~reset & ~((~winnerQual_1_0 | ~earlyWinner_1_1) & (~prefixOR_2 | ~earlyWinner_1_2) & (~prefixOR_3 | ~earlyWinner_1_3) & (~(prefixOR_3 | earlyWinner_1_3) | ~earlyWinner_1_4))) begin	// @[Arbiter.scala:97:79, :104:53, :105:{13,61,64,67,82}, Broadcast.scala:198:35]
        if (`ASSERT_VERBOSE_COND_)	// @[Arbiter.scala:105:13]
          $error("Assertion failed\n    at Arbiter.scala:105 assert((prefixOR zip earlyWinner) map { case (p,w) => !p || !w } reduce {_ && _})\n");	// @[Arbiter.scala:105:13]
        if (`STOP_COND_)	// @[Arbiter.scala:105:13]
          $fatal;	// @[Arbiter.scala:105:13]
      end
      if (~reset & ~(~(_sink_ACancel_earlyValid_T_5 | _TLBroadcastTracker_1_io_out_a_valid | _TLBroadcastTracker_2_io_out_a_valid | _TLBroadcastTracker_3_io_out_a_valid) | winnerQual_1_0 | earlyWinner_1_1 | earlyWinner_1_2 | earlyWinner_1_3 | earlyWinner_1_4)) begin	// @[Arbiter.scala:97:79, :107:{14,15,36,41}, Broadcast.scala:108:15, :198:35]
        if (`ASSERT_VERBOSE_COND_)	// @[Arbiter.scala:107:14]
          $error("Assertion failed\n    at Arbiter.scala:107 assert (!earlyValids.reduce(_||_) || earlyWinner.reduce(_||_))\n");	// @[Arbiter.scala:107:14]
        if (`STOP_COND_)	// @[Arbiter.scala:107:14]
          $fatal;	// @[Arbiter.scala:107:14]
      end
      if (~reset & ~(~(_T_305 | _TLBroadcastTracker_1_io_out_a_valid | _TLBroadcastTracker_2_io_out_a_valid | _TLBroadcastTracker_3_io_out_a_valid) | _T_305 | _TLBroadcastTracker_1_io_out_a_valid | _TLBroadcastTracker_2_io_out_a_valid | _TLBroadcastTracker_3_io_out_a_valid)) begin	// @[Arbiter.scala:108:{14,15,36,41}, Broadcast.scala:108:15]
        if (`ASSERT_VERBOSE_COND_)	// @[Arbiter.scala:108:14]
          $error("Assertion failed\n    at Arbiter.scala:108 assert (!validQuals .reduce(_||_) || validQuals .reduce(_||_))\n");	// @[Arbiter.scala:108:14]
        if (`STOP_COND_)	// @[Arbiter.scala:108:14]
          $fatal;	// @[Arbiter.scala:108:14]
      end
    end // always @(posedge)
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM_0;
    logic [31:0] _RANDOM_1;
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        _RANDOM_0 = `RANDOM;
        _RANDOM_1 = `RANDOM;
        counter = _RANDOM_0[2:0];	// @[Edges.scala:228:27]
        r = _RANDOM_0[6:3];	// @[Edges.scala:228:27, Reg.scala:19:16]
        beatsLeft = _RANDOM_0[12:10];	// @[Arbiter.scala:87:30, Edges.scala:228:27]
        state_0 = _RANDOM_0[13];	// @[Arbiter.scala:116:26, Edges.scala:228:27]
        state_1 = _RANDOM_0[14];	// @[Arbiter.scala:116:26, Edges.scala:228:27]
        beatsLeft_1 = _RANDOM_0[17:15];	// @[Arbiter.scala:87:30, Edges.scala:228:27]
        state_1_0 = _RANDOM_0[18];	// @[Arbiter.scala:116:26, Edges.scala:228:27]
        state_1_1 = _RANDOM_0[19];	// @[Arbiter.scala:116:26, Edges.scala:228:27]
        state_1_2 = _RANDOM_0[20];	// @[Arbiter.scala:116:26, Edges.scala:228:27]
        state_1_3 = _RANDOM_0[21];	// @[Arbiter.scala:116:26, Edges.scala:228:27]
        state_1_4 = _RANDOM_0[22];	// @[Arbiter.scala:116:26, Edges.scala:228:27]
        REG = _RANDOM_0[23];	// @[Broadcast.scala:216:31, Edges.scala:228:27]
        REG_1 = {_RANDOM_0[31:24], _RANDOM_1[17:0]};	// @[Broadcast.scala:217:27, Edges.scala:228:27]
        REG_2 = _RANDOM_1[19:18];	// @[Broadcast.scala:217:27, :218:28]
        counter_2 = _RANDOM_1[22:20];	// @[Broadcast.scala:217:27, Edges.scala:228:27]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // not def SYNTHESIS
  TLMonitor_39 monitor (	// @[Nodes.scala:24:25]
    .clock                (clock),
    .reset                (reset),
    .io_in_a_ready        (bundleIn_0_a_ready),	// @[Broadcast.scala:244:59]
    .io_in_a_valid        (auto_in_a_valid),
    .io_in_a_bits_opcode  (auto_in_a_bits_opcode),
    .io_in_a_bits_param   (auto_in_a_bits_param),
    .io_in_a_bits_size    (auto_in_a_bits_size),
    .io_in_a_bits_source  (auto_in_a_bits_source),
    .io_in_a_bits_address (auto_in_a_bits_address),
    .io_in_a_bits_mask    (auto_in_a_bits_mask),
    .io_in_a_bits_corrupt (auto_in_a_bits_corrupt),
    .io_in_b_valid        (REG),	// @[Broadcast.scala:216:31]
    .io_in_b_bits_param   (REG_2),	// @[Broadcast.scala:218:28]
    .io_in_b_bits_address (bundleIn_0_b_bits_b_address),	// @[Broadcast.scala:226:46]
    .io_in_c_ready        (bundleIn_0_c_ready),	// @[Broadcast.scala:185:32]
    .io_in_c_valid        (auto_in_c_valid),
    .io_in_c_bits_opcode  (auto_in_c_bits_opcode),
    .io_in_c_bits_param   (auto_in_c_bits_param),
    .io_in_c_bits_size    (auto_in_c_bits_size),
    .io_in_c_bits_source  (auto_in_c_bits_source),
    .io_in_c_bits_address (auto_in_c_bits_address),
    .io_in_c_bits_corrupt (auto_in_c_bits_corrupt),
    .io_in_d_ready        (auto_in_d_ready),
    .io_in_d_valid        (out_2_valid),	// @[Arbiter.scala:125:29]
    .io_in_d_bits_opcode  (out_2_bits_opcode),	// @[Mux.scala:27:73]
    .io_in_d_bits_param   (out_2_bits_param),	// @[Mux.scala:27:73]
    .io_in_d_bits_size    (out_2_bits_size),	// @[Mux.scala:27:73]
    .io_in_d_bits_source  (out_2_bits_source),	// @[Mux.scala:27:73]
    .io_in_d_bits_sink    (out_2_bits_sink),	// @[Mux.scala:27:73]
    .io_in_d_bits_denied  (out_2_bits_denied),	// @[Mux.scala:27:73]
    .io_in_d_bits_corrupt (out_2_bits_corrupt),	// @[Mux.scala:27:73]
    .io_in_e_valid        (auto_in_e_valid),
    .io_in_e_bits_sink    (auto_in_e_bits_sink)
  );
  BroadcastFilter BroadcastFilter (	// @[Broadcast.scala:100:26]
    .io_request_valid         (auto_in_a_valid & ~(|counter_2) & (|_GEN_4)),	// @[Broadcast.scala:242:{41,58}, :251:56, Edges.scala:228:27, :230:25]
    .io_request_bits_mshr     ({|(_GEN_3[3:2]), _GEN_3[3] | _GEN_3[1]}),	// @[Broadcast.scala:240:30, :252:38, OneHot.scala:30:18, :31:18, :32:{14,28}]
    .io_request_bits_address  (auto_in_a_bits_address),
    .io_request_bits_allocOH  (auto_in_a_bits_source[5:4] == 2'h0 & auto_in_a_bits_source[3:0] < 4'h9),	// @[Broadcast.scala:134:51, Parameters.scala:52:64, :54:{10,32}, :56:50, :57:20]
    .io_request_bits_needT    ((&auto_in_a_bits_opcode) | auto_in_a_bits_opcode == 3'h6 ? auto_in_a_bits_param == 3'h2 | auto_in_a_bits_param == 3'h1 : auto_in_a_bits_opcode == 3'h5 ? auto_in_a_bits_param == 3'h1 : auto_in_a_bits_opcode != 3'h4),	// @[Broadcast.scala:133:36, :159:45, :168:34, Mux.scala:81:{58,61}]
    .io_response_ready        (~REG),	// @[Broadcast.scala:216:31, :260:35]
    .io_request_ready         (_BroadcastFilter_io_request_ready),
    .io_response_valid        (_BroadcastFilter_io_response_valid),
    .io_response_bits_mshr    (_BroadcastFilter_io_response_bits_mshr),
    .io_response_bits_address (_BroadcastFilter_io_response_bits_address),
    .io_response_bits_allocOH (_BroadcastFilter_io_response_bits_allocOH),
    .io_response_bits_needT   (_BroadcastFilter_io_response_bits_needT)
  );
  TLBroadcastTracker TLBroadcastTracker (	// @[Broadcast.scala:108:15]
    .clock                 (clock),
    .reset                 (reset),
    .io_in_a_first         (~(|counter_2)),	// @[Edges.scala:228:27, :230:25]
    .io_in_a_valid         (auto_in_a_valid & _GEN_3[0] & ((|counter_2) | _BroadcastFilter_io_request_ready)),	// @[Broadcast.scala:100:26, :240:30, :245:35, :246:{46,59}, Edges.scala:228:27, :230:25]
    .io_in_a_bits_opcode   (auto_in_a_bits_opcode),
    .io_in_a_bits_param    (auto_in_a_bits_param),
    .io_in_a_bits_size     (auto_in_a_bits_size),
    .io_in_a_bits_source   (auto_in_a_bits_source),
    .io_in_a_bits_address  (auto_in_a_bits_address),
    .io_in_a_bits_mask     (auto_in_a_bits_mask),
    .io_in_a_bits_data     (auto_in_a_bits_data),
    .io_out_a_ready        (auto_out_a_ready & (idle_1 ? ~winnerQual_1_0 : state_1_1)),	// @[Arbiter.scala:16:61, :88:28, :116:26, :121:24, :123:31, Broadcast.scala:198:35]
    .io_probe_valid        (_T_506 & _BroadcastFilter_io_response_bits_mshr == 2'h0),	// @[Broadcast.scala:100:26, :134:51, :270:85, :273:58, Decoupled.scala:51:35]
    .io_probe_bits_count   (~_BroadcastFilter_io_response_bits_allocOH),	// @[Broadcast.scala:100:26, :258:54]
    .io_probenack          (_T_193 & _T_110 & _T_115),	// @[Broadcast.scala:159:45, :163:55, :176:56, Decoupled.scala:51:35]
    .io_probedack          (_T_25[0] & _T_86 & _T_14),	// @[Broadcast.scala:120:27, :142:33, :144:53, Decoupled.scala:51:35, package.scala:80:42]
    .io_probesack          (_T_193 & _T_115 & _T_187 & (_T_197 | _T_190)),	// @[Broadcast.scala:163:55, :171:52, :177:86, :178:{27,50}, :179:27, Decoupled.scala:51:35]
    .io_d_last             (_T_25[0] & _T_82 & _T_56 & last),	// @[Broadcast.scala:141:34, :142:33, :143:67, Decoupled.scala:51:35, Edges.scala:231:37, package.scala:80:42]
    .io_e_last             (auto_in_e_bits_sink == 2'h0 & auto_in_e_valid),	// @[Broadcast.scala:113:46, :114:34, :134:51]
    .io_in_a_ready         (_TLBroadcastTracker_io_in_a_ready),
    .io_out_a_valid        (_TLBroadcastTracker_io_out_a_valid),
    .io_out_a_bits_opcode  (_TLBroadcastTracker_io_out_a_bits_opcode),
    .io_out_a_bits_param   (_TLBroadcastTracker_io_out_a_bits_param),
    .io_out_a_bits_size    (_TLBroadcastTracker_io_out_a_bits_size),
    .io_out_a_bits_source  (_TLBroadcastTracker_io_out_a_bits_source),
    .io_out_a_bits_address (_TLBroadcastTracker_io_out_a_bits_address),
    .io_out_a_bits_mask    (_TLBroadcastTracker_io_out_a_bits_mask),
    .io_out_a_bits_data    (_TLBroadcastTracker_io_out_a_bits_data),
    .io_source             (_TLBroadcastTracker_io_source),
    .io_line               (_TLBroadcastTracker_io_line),
    .io_idle               (_TLBroadcastTracker_io_idle),
    .io_need_d             (_TLBroadcastTracker_io_need_d)
  );
  TLBroadcastTracker_1 TLBroadcastTracker_1 (	// @[Broadcast.scala:108:15]
    .clock                 (clock),
    .reset                 (reset),
    .io_in_a_first         (~(|counter_2)),	// @[Edges.scala:228:27, :230:25]
    .io_in_a_valid         (auto_in_a_valid & _GEN_3[1] & ((|counter_2) | _BroadcastFilter_io_request_ready)),	// @[Broadcast.scala:100:26, :240:30, :245:35, :246:{46,59}, Edges.scala:228:27, :230:25]
    .io_in_a_bits_opcode   (auto_in_a_bits_opcode),
    .io_in_a_bits_param    (auto_in_a_bits_param),
    .io_in_a_bits_size     (auto_in_a_bits_size),
    .io_in_a_bits_source   (auto_in_a_bits_source),
    .io_in_a_bits_address  (auto_in_a_bits_address),
    .io_in_a_bits_mask     (auto_in_a_bits_mask),
    .io_in_a_bits_data     (auto_in_a_bits_data),
    .io_out_a_ready        (auto_out_a_ready & (idle_1 ? ~_GEN_0 : state_1_2)),	// @[Arbiter.scala:16:61, :88:28, :116:26, :121:24, :123:31, package.scala:245:43]
    .io_probe_valid        (_T_506 & _BroadcastFilter_io_response_bits_mshr == 2'h1),	// @[Broadcast.scala:100:26, :134:51, :270:85, :273:58, Decoupled.scala:51:35]
    .io_probe_bits_count   (~_BroadcastFilter_io_response_bits_allocOH),	// @[Broadcast.scala:100:26, :258:54]
    .io_probenack          (_T_193 & _T_110 & _T_117),	// @[Broadcast.scala:159:45, :163:55, :176:56, Decoupled.scala:51:35]
    .io_probedack          (_T_25[1] & _T_86 & _T_14),	// @[Broadcast.scala:120:27, :142:33, :144:53, Decoupled.scala:51:35, package.scala:80:42]
    .io_probesack          (_T_193 & _T_117 & _T_187 & (_T_197 | _T_190)),	// @[Broadcast.scala:163:55, :171:52, :177:86, :178:{27,50}, :179:27, Decoupled.scala:51:35]
    .io_d_last             (_T_25[1] & _T_82 & _T_56 & last),	// @[Broadcast.scala:141:34, :142:33, :143:67, Decoupled.scala:51:35, Edges.scala:231:37, package.scala:80:42]
    .io_e_last             (auto_in_e_bits_sink == 2'h1 & auto_in_e_valid),	// @[Broadcast.scala:113:46, :114:34, :134:51]
    .io_in_a_ready         (_TLBroadcastTracker_1_io_in_a_ready),
    .io_out_a_valid        (_TLBroadcastTracker_1_io_out_a_valid),
    .io_out_a_bits_opcode  (_TLBroadcastTracker_1_io_out_a_bits_opcode),
    .io_out_a_bits_param   (_TLBroadcastTracker_1_io_out_a_bits_param),
    .io_out_a_bits_size    (_TLBroadcastTracker_1_io_out_a_bits_size),
    .io_out_a_bits_source  (_TLBroadcastTracker_1_io_out_a_bits_source),
    .io_out_a_bits_address (_TLBroadcastTracker_1_io_out_a_bits_address),
    .io_out_a_bits_mask    (_TLBroadcastTracker_1_io_out_a_bits_mask),
    .io_out_a_bits_data    (_TLBroadcastTracker_1_io_out_a_bits_data),
    .io_source             (_TLBroadcastTracker_1_io_source),
    .io_line               (_TLBroadcastTracker_1_io_line),
    .io_idle               (_TLBroadcastTracker_1_io_idle),
    .io_need_d             (_TLBroadcastTracker_1_io_need_d)
  );
  TLBroadcastTracker_2 TLBroadcastTracker_2 (	// @[Broadcast.scala:108:15]
    .clock                 (clock),
    .reset                 (reset),
    .io_in_a_first         (~(|counter_2)),	// @[Edges.scala:228:27, :230:25]
    .io_in_a_valid         (auto_in_a_valid & _GEN_3[2] & ((|counter_2) | _BroadcastFilter_io_request_ready)),	// @[Broadcast.scala:100:26, :240:30, :245:35, :246:{46,59}, Edges.scala:228:27, :230:25]
    .io_in_a_bits_opcode   (auto_in_a_bits_opcode),
    .io_in_a_bits_param    (auto_in_a_bits_param),
    .io_in_a_bits_size     (auto_in_a_bits_size),
    .io_in_a_bits_source   (auto_in_a_bits_source),
    .io_in_a_bits_address  (auto_in_a_bits_address),
    .io_in_a_bits_mask     (auto_in_a_bits_mask),
    .io_in_a_bits_data     (auto_in_a_bits_data),
    .io_out_a_ready        (auto_out_a_ready & (idle_1 ? ~_GEN_2 : state_1_3)),	// @[Arbiter.scala:16:61, :88:28, :116:26, :121:24, :123:31, package.scala:245:43]
    .io_probe_valid        (_T_506 & _BroadcastFilter_io_response_bits_mshr == 2'h2),	// @[Broadcast.scala:100:26, :196:25, :270:85, :273:58, Decoupled.scala:51:35]
    .io_probe_bits_count   (~_BroadcastFilter_io_response_bits_allocOH),	// @[Broadcast.scala:100:26, :258:54]
    .io_probenack          (_T_193 & _T_110 & _T_119),	// @[Broadcast.scala:159:45, :163:55, :176:56, Decoupled.scala:51:35]
    .io_probedack          (_T_25[2] & _T_86 & _T_14),	// @[Broadcast.scala:120:27, :142:33, :144:53, Decoupled.scala:51:35, package.scala:80:42]
    .io_probesack          (_T_193 & _T_119 & _T_187 & (_T_197 | _T_190)),	// @[Broadcast.scala:163:55, :171:52, :177:86, :178:{27,50}, :179:27, Decoupled.scala:51:35]
    .io_d_last             (_T_25[2] & _T_82 & _T_56 & last),	// @[Broadcast.scala:141:34, :142:33, :143:67, Decoupled.scala:51:35, Edges.scala:231:37, package.scala:80:42]
    .io_e_last             (auto_in_e_bits_sink == 2'h2 & auto_in_e_valid),	// @[Broadcast.scala:113:46, :114:34, :196:25]
    .io_in_a_ready         (_TLBroadcastTracker_2_io_in_a_ready),
    .io_out_a_valid        (_TLBroadcastTracker_2_io_out_a_valid),
    .io_out_a_bits_opcode  (_TLBroadcastTracker_2_io_out_a_bits_opcode),
    .io_out_a_bits_param   (_TLBroadcastTracker_2_io_out_a_bits_param),
    .io_out_a_bits_size    (_TLBroadcastTracker_2_io_out_a_bits_size),
    .io_out_a_bits_source  (_TLBroadcastTracker_2_io_out_a_bits_source),
    .io_out_a_bits_address (_TLBroadcastTracker_2_io_out_a_bits_address),
    .io_out_a_bits_mask    (_TLBroadcastTracker_2_io_out_a_bits_mask),
    .io_out_a_bits_data    (_TLBroadcastTracker_2_io_out_a_bits_data),
    .io_source             (_TLBroadcastTracker_2_io_source),
    .io_line               (_TLBroadcastTracker_2_io_line),
    .io_idle               (_TLBroadcastTracker_2_io_idle),
    .io_need_d             (_TLBroadcastTracker_2_io_need_d)
  );
  TLBroadcastTracker_3 TLBroadcastTracker_3 (	// @[Broadcast.scala:108:15]
    .clock                 (clock),
    .reset                 (reset),
    .io_in_a_first         (~(|counter_2)),	// @[Edges.scala:228:27, :230:25]
    .io_in_a_valid         (auto_in_a_valid & _GEN_3[3] & ((|counter_2) | _BroadcastFilter_io_request_ready)),	// @[Broadcast.scala:100:26, :240:30, :245:35, :246:{46,59}, Edges.scala:228:27, :230:25]
    .io_in_a_bits_opcode   (auto_in_a_bits_opcode),
    .io_in_a_bits_param    (auto_in_a_bits_param),
    .io_in_a_bits_size     (auto_in_a_bits_size),
    .io_in_a_bits_source   (auto_in_a_bits_source),
    .io_in_a_bits_address  (auto_in_a_bits_address),
    .io_in_a_bits_mask     (auto_in_a_bits_mask),
    .io_in_a_bits_data     (auto_in_a_bits_data),
    .io_out_a_ready        (auto_out_a_ready & (idle_1 ? ~_GEN_1 : state_1_4)),	// @[Arbiter.scala:16:61, :88:28, :116:26, :121:24, :123:31, package.scala:245:43]
    .io_probe_valid        (_T_506 & (&_BroadcastFilter_io_response_bits_mshr)),	// @[Broadcast.scala:100:26, :270:85, :273:58, Decoupled.scala:51:35]
    .io_probe_bits_count   (~_BroadcastFilter_io_response_bits_allocOH),	// @[Broadcast.scala:100:26, :258:54]
    .io_probenack          (_T_193 & _T_110 & _T_121),	// @[Broadcast.scala:159:45, :163:55, :176:56, Decoupled.scala:51:35]
    .io_probedack          (_T_25[3] & _T_86 & _T_14),	// @[Broadcast.scala:120:27, :142:33, :144:53, Decoupled.scala:51:35, package.scala:80:42]
    .io_probesack          (_T_193 & _T_121 & _T_187 & (_T_197 | _T_190)),	// @[Broadcast.scala:163:55, :171:52, :177:86, :178:{27,50}, :179:27, Decoupled.scala:51:35]
    .io_d_last             (_T_25[3] & _T_82 & _T_56 & last),	// @[Broadcast.scala:141:34, :142:33, :143:67, Decoupled.scala:51:35, Edges.scala:231:37, package.scala:80:42]
    .io_e_last             ((&auto_in_e_bits_sink) & auto_in_e_valid),	// @[Broadcast.scala:113:46, :114:34]
    .io_in_a_ready         (_TLBroadcastTracker_3_io_in_a_ready),
    .io_out_a_valid        (_TLBroadcastTracker_3_io_out_a_valid),
    .io_out_a_bits_opcode  (_TLBroadcastTracker_3_io_out_a_bits_opcode),
    .io_out_a_bits_param   (_TLBroadcastTracker_3_io_out_a_bits_param),
    .io_out_a_bits_size    (_TLBroadcastTracker_3_io_out_a_bits_size),
    .io_out_a_bits_source  (_TLBroadcastTracker_3_io_out_a_bits_source),
    .io_out_a_bits_address (_TLBroadcastTracker_3_io_out_a_bits_address),
    .io_out_a_bits_mask    (_TLBroadcastTracker_3_io_out_a_bits_mask),
    .io_out_a_bits_data    (_TLBroadcastTracker_3_io_out_a_bits_data),
    .io_source             (_TLBroadcastTracker_3_io_source),
    .io_line               (_TLBroadcastTracker_3_io_line),
    .io_idle               (_TLBroadcastTracker_3_io_idle),
    .io_need_d             (_TLBroadcastTracker_3_io_need_d)
  );
  assign auto_in_a_ready = bundleIn_0_a_ready;	// @[Broadcast.scala:244:59]
  assign auto_in_b_valid = REG;	// @[Broadcast.scala:216:31]
  assign auto_in_b_bits_param = REG_2;	// @[Broadcast.scala:218:28]
  assign auto_in_b_bits_address = bundleIn_0_b_bits_b_address;	// @[Broadcast.scala:226:46]
  assign auto_in_c_ready = bundleIn_0_c_ready;	// @[Broadcast.scala:185:32]
  assign auto_in_d_valid = out_2_valid;	// @[Arbiter.scala:125:29]
  assign auto_in_d_bits_opcode = out_2_bits_opcode;	// @[Mux.scala:27:73]
  assign auto_in_d_bits_param = out_2_bits_param;	// @[Mux.scala:27:73]
  assign auto_in_d_bits_size = out_2_bits_size;	// @[Mux.scala:27:73]
  assign auto_in_d_bits_source = out_2_bits_source;	// @[Mux.scala:27:73]
  assign auto_in_d_bits_sink = out_2_bits_sink;	// @[Mux.scala:27:73]
  assign auto_in_d_bits_denied = out_2_bits_denied;	// @[Mux.scala:27:73]
  assign auto_in_d_bits_data = muxStateEarly_1 ? auto_out_d_bits_data : 64'h0;	// @[Arbiter.scala:117:30, Bundles.scala:259:74, Mux.scala:27:73]
  assign auto_in_d_bits_corrupt = out_2_bits_corrupt;	// @[Mux.scala:27:73]
  assign auto_out_a_valid = out_8_valid;	// @[Arbiter.scala:125:29]
  assign auto_out_a_bits_opcode = (muxStateEarly_1_1 ? _TLBroadcastTracker_io_out_a_bits_opcode : 3'h0) | (muxStateEarly_1_2 ? _TLBroadcastTracker_1_io_out_a_bits_opcode : 3'h0) | (muxStateEarly_1_3 ? _TLBroadcastTracker_2_io_out_a_bits_opcode : 3'h0) | (muxStateEarly_1_4 ? _TLBroadcastTracker_3_io_out_a_bits_opcode : 3'h0);	// @[Arbiter.scala:117:30, Broadcast.scala:108:15, Edges.scala:228:27, Mux.scala:27:73]
  assign auto_out_a_bits_param = (muxStateEarly_1_1 ? _TLBroadcastTracker_io_out_a_bits_param : 3'h0) | (muxStateEarly_1_2 ? _TLBroadcastTracker_1_io_out_a_bits_param : 3'h0) | (muxStateEarly_1_3 ? _TLBroadcastTracker_2_io_out_a_bits_param : 3'h0) | (muxStateEarly_1_4 ? _TLBroadcastTracker_3_io_out_a_bits_param : 3'h0);	// @[Arbiter.scala:117:30, Broadcast.scala:108:15, Edges.scala:228:27, Mux.scala:27:73]
  assign auto_out_a_bits_size = (muxStateEarly_1_0 ? auto_in_c_bits_size : 3'h0) | (muxStateEarly_1_1 ? _TLBroadcastTracker_io_out_a_bits_size : 3'h0) | (muxStateEarly_1_2 ? _TLBroadcastTracker_1_io_out_a_bits_size : 3'h0) | (muxStateEarly_1_3 ? _TLBroadcastTracker_2_io_out_a_bits_size : 3'h0) | (muxStateEarly_1_4 ? _TLBroadcastTracker_3_io_out_a_bits_size : 3'h0);	// @[Arbiter.scala:117:30, Broadcast.scala:108:15, Edges.scala:228:27, Mux.scala:27:73]
  assign auto_out_a_bits_source = (muxStateEarly_1_0 ? {(&auto_in_c_bits_opcode) ? 2'h2 : 2'h1, (&auto_in_c_bits_opcode) ? auto_in_c_bits_source : (_T_115 ? _TLBroadcastTracker_io_source : 6'h0) | (_T_117 ? _TLBroadcastTracker_1_io_source : 6'h0) | (_T_119 ? _TLBroadcastTracker_2_io_source : 6'h0) | (_T_121 ? _TLBroadcastTracker_3_io_source : 6'h0)} : 8'h0) | (muxStateEarly_1_1 ? _TLBroadcastTracker_io_out_a_bits_source : 8'h0) | (muxStateEarly_1_2 ? _TLBroadcastTracker_1_io_out_a_bits_source : 8'h0) | (muxStateEarly_1_3 ? _TLBroadcastTracker_2_io_out_a_bits_source : 8'h0) | (muxStateEarly_1_4 ? _TLBroadcastTracker_3_io_out_a_bits_source : 8'h0);	// @[Arbiter.scala:117:30, Broadcast.scala:108:15, :134:51, :161:45, :163:55, :196:25, :197:25, Bundles.scala:259:74, Cat.scala:33:92, Mux.scala:27:73]
  assign auto_out_a_bits_address = (muxStateEarly_1_0 ? auto_in_c_bits_address : 32'h0) | (muxStateEarly_1_1 ? _TLBroadcastTracker_io_out_a_bits_address : 32'h0) | (muxStateEarly_1_2 ? _TLBroadcastTracker_1_io_out_a_bits_address : 32'h0) | (muxStateEarly_1_3 ? _TLBroadcastTracker_2_io_out_a_bits_address : 32'h0) | (muxStateEarly_1_4 ? _TLBroadcastTracker_3_io_out_a_bits_address : 32'h0);	// @[Arbiter.scala:117:30, Broadcast.scala:108:15, Bundles.scala:259:74, Mux.scala:27:73]
  assign auto_out_a_bits_mask = (muxStateEarly_1_0 ? {a_mask_acc_5 | a_mask_eq_5 & auto_in_c_bits_address[0], a_mask_acc_5 | a_mask_eq_5 & ~(auto_in_c_bits_address[0]), a_mask_acc_4 | a_mask_eq_4 & auto_in_c_bits_address[0], a_mask_acc_4 | a_mask_eq_4 & ~(auto_in_c_bits_address[0]), a_mask_acc_3 | a_mask_eq_3 & auto_in_c_bits_address[0], a_mask_acc_3 | a_mask_eq_3 & ~(auto_in_c_bits_address[0]), a_mask_acc_2 | a_mask_eq_2 & auto_in_c_bits_address[0], a_mask_acc_2 | a_mask_eq_2 & ~(auto_in_c_bits_address[0])} : 8'h0) | (muxStateEarly_1_1 ? _TLBroadcastTracker_io_out_a_bits_mask : 8'h0) | (muxStateEarly_1_2 ? _TLBroadcastTracker_1_io_out_a_bits_mask : 8'h0) | (muxStateEarly_1_3 ? _TLBroadcastTracker_2_io_out_a_bits_mask : 8'h0) | (muxStateEarly_1_4 ? _TLBroadcastTracker_3_io_out_a_bits_mask : 8'h0);	// @[Arbiter.scala:117:30, Broadcast.scala:108:15, Bundles.scala:259:74, Cat.scala:33:92, Misc.scala:209:26, :210:20, :213:27, :214:29, Mux.scala:27:73]
  assign auto_out_a_bits_data = (muxStateEarly_1_0 ? auto_in_c_bits_data : 64'h0) | (muxStateEarly_1_1 ? _TLBroadcastTracker_io_out_a_bits_data : 64'h0) | (muxStateEarly_1_2 ? _TLBroadcastTracker_1_io_out_a_bits_data : 64'h0) | (muxStateEarly_1_3 ? _TLBroadcastTracker_2_io_out_a_bits_data : 64'h0) | (muxStateEarly_1_4 ? _TLBroadcastTracker_3_io_out_a_bits_data : 64'h0);	// @[Arbiter.scala:117:30, Broadcast.scala:108:15, Bundles.scala:259:74, Mux.scala:27:73]
  assign auto_out_d_ready = x1_d_ready;	// @[Broadcast.scala:129:50]
endmodule

