// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

module TLBroadcastTracker(
  input         clock,
                reset,
                io_in_a_first,
                io_in_a_valid,
  input  [2:0]  io_in_a_bits_opcode,
                io_in_a_bits_param,
                io_in_a_bits_size,
  input  [5:0]  io_in_a_bits_source,
  input  [31:0] io_in_a_bits_address,
  input  [7:0]  io_in_a_bits_mask,
  input  [63:0] io_in_a_bits_data,
  input         io_out_a_ready,
                io_probe_valid,
                io_probe_bits_count,
                io_probenack,
                io_probedack,
                io_probesack,
                io_d_last,
                io_e_last,
  output        io_in_a_ready,
                io_out_a_valid,
  output [2:0]  io_out_a_bits_opcode,
                io_out_a_bits_param,
                io_out_a_bits_size,
  output [7:0]  io_out_a_bits_source,
  output [31:0] io_out_a_bits_address,
  output [7:0]  io_out_a_bits_mask,
  output [63:0] io_out_a_bits_data,
  output [5:0]  io_source,
  output [25:0] io_line,
  output        io_idle,
                io_need_d
);

  wire        _io_in_a_ready_output;	// @[Broadcast.scala:486:45]
  wire        _o_data_io_enq_ready;	// @[Decoupled.scala:375:21]
  wire        _o_data_io_deq_valid;	// @[Decoupled.scala:375:21]
  reg         got_e;	// @[Broadcast.scala:424:24]
  reg         sent_d;	// @[Broadcast.scala:425:24]
  reg         shared;	// @[Broadcast.scala:426:20]
  reg  [2:0]  opcode;	// @[Broadcast.scala:427:20]
  reg  [2:0]  param;	// @[Broadcast.scala:428:20]
  reg  [2:0]  size;	// @[Broadcast.scala:429:20]
  reg  [5:0]  source;	// @[Broadcast.scala:430:20]
  reg  [31:0] address;	// @[Broadcast.scala:433:24]
  reg         count;	// @[Broadcast.scala:434:20]
  wire        idle = got_e & sent_d;	// @[Broadcast.scala:424:24, :425:24, :436:23]
  wire        _T_1 = _io_in_a_ready_output & io_in_a_valid & io_in_a_first;	// @[Broadcast.scala:438:24, :486:45]
  wire        _T_13 = io_probenack | io_probedack;	// @[Broadcast.scala:468:22]
  assign _io_in_a_ready_output = (idle | ~io_in_a_first) & _o_data_io_enq_ready;	// @[Broadcast.scala:436:23, :486:{26,29,45}, Decoupled.scala:375:21]
  wire        acquire = opcode == 3'h6 | (&opcode);	// @[Broadcast.scala:427:20, :442:36, :492:{24,52,62}]
  always @(posedge clock) begin
    if (reset) begin
      got_e <= 1'h1;	// @[Broadcast.scala:424:24]
      sent_d <= 1'h1;	// @[Broadcast.scala:425:24]
      address <= 32'h0;	// @[Broadcast.scala:433:24]
    end
    else begin
      got_e <= io_e_last | (_T_1 ? io_in_a_bits_opcode != 3'h6 & io_in_a_bits_opcode != 3'h7 : got_e);	// @[Broadcast.scala:424:24, :438:{24,42}, :442:{13,36,64,87}, :463:20, :465:11]
      sent_d <= io_d_last | ~_T_1 & sent_d;	// @[Broadcast.scala:425:24, :438:{24,42}, :440:13, :459:20, :461:12]
      if (_T_1)	// @[Broadcast.scala:438:24]
        address <= io_in_a_bits_address;	// @[Broadcast.scala:433:24]
    end
    if (io_probesack)
      shared <= 1'h1;	// @[Broadcast.scala:426:20]
    else
      shared <= ~_T_1 & shared;	// @[Broadcast.scala:425:24, :426:20, :438:{24,42}, :440:13, :441:13]
    if (_T_1) begin	// @[Broadcast.scala:438:24]
      opcode <= io_in_a_bits_opcode;	// @[Broadcast.scala:427:20]
      param <= io_in_a_bits_param;	// @[Broadcast.scala:428:20]
      size <= io_in_a_bits_size;	// @[Broadcast.scala:429:20]
      source <= io_in_a_bits_source;	// @[Broadcast.scala:430:20]
    end
    if (_T_13)	// @[Broadcast.scala:468:22]
      count <= count - ~(io_probenack & io_probedack);	// @[Broadcast.scala:434:20, :470:{20,25,39}]
    else if (io_probe_valid)
      count <= io_probe_bits_count;	// @[Broadcast.scala:434:20]
    else
      count <= _T_1 | count;	// @[Broadcast.scala:434:20, :438:{24,42}, :450:13]
  end // always @(posedge)
  `ifndef SYNTHESIS
    always @(posedge clock) begin	// @[Broadcast.scala:439:12]
      if (_T_1 & ~reset & ~idle) begin	// @[Broadcast.scala:436:23, :438:24, :439:12]
        if (`ASSERT_VERBOSE_COND_)	// @[Broadcast.scala:439:12]
          $error("Assertion failed\n    at Broadcast.scala:439 assert (idle)\n");	// @[Broadcast.scala:439:12]
        if (`STOP_COND_)	// @[Broadcast.scala:439:12]
          $fatal;	// @[Broadcast.scala:439:12]
      end
      if (io_d_last & ~reset & sent_d) begin	// @[Broadcast.scala:425:24, :460:12]
        if (`ASSERT_VERBOSE_COND_)	// @[Broadcast.scala:460:12]
          $error("Assertion failed\n    at Broadcast.scala:460 assert (!sent_d)\n");	// @[Broadcast.scala:460:12]
        if (`STOP_COND_)	// @[Broadcast.scala:460:12]
          $fatal;	// @[Broadcast.scala:460:12]
      end
      if (io_e_last & ~reset & got_e) begin	// @[Broadcast.scala:424:24, :464:12]
        if (`ASSERT_VERBOSE_COND_)	// @[Broadcast.scala:464:12]
          $error("Assertion failed\n    at Broadcast.scala:464 assert (!got_e)\n");	// @[Broadcast.scala:464:12]
        if (`STOP_COND_)	// @[Broadcast.scala:464:12]
          $fatal;	// @[Broadcast.scala:464:12]
      end
      if (_T_13 & ~reset & ~count) begin	// @[Broadcast.scala:434:20, :468:22, :469:12]
        if (`ASSERT_VERBOSE_COND_)	// @[Broadcast.scala:469:12]
          $error("Assertion failed\n    at Broadcast.scala:469 assert (count > 0.U)\n");	// @[Broadcast.scala:469:12]
        if (`STOP_COND_)	// @[Broadcast.scala:469:12]
          $fatal;	// @[Broadcast.scala:469:12]
      end
    end // always @(posedge)
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM_0;
    logic [31:0] _RANDOM_1;
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        _RANDOM_0 = `RANDOM;
        _RANDOM_1 = `RANDOM;
        got_e = _RANDOM_0[0];	// @[Broadcast.scala:424:24]
        sent_d = _RANDOM_0[1];	// @[Broadcast.scala:424:24, :425:24]
        shared = _RANDOM_0[2];	// @[Broadcast.scala:424:24, :426:20]
        opcode = _RANDOM_0[5:3];	// @[Broadcast.scala:424:24, :427:20]
        param = _RANDOM_0[8:6];	// @[Broadcast.scala:424:24, :428:20]
        size = _RANDOM_0[11:9];	// @[Broadcast.scala:424:24, :429:20]
        source = _RANDOM_0[17:12];	// @[Broadcast.scala:424:24, :430:20]
        address = {_RANDOM_0[31:18], _RANDOM_1[17:0]};	// @[Broadcast.scala:424:24, :433:24]
        count = _RANDOM_1[18];	// @[Broadcast.scala:433:24, :434:20]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // not def SYNTHESIS
  Queue_19 o_data (	// @[Decoupled.scala:375:21]
    .clock            (clock),
    .reset            (reset),
    .io_enq_valid     ((idle | ~io_in_a_first) & io_in_a_valid),	// @[Broadcast.scala:436:23, :486:29, :487:{25,44}]
    .io_enq_bits_mask (io_in_a_bits_mask),
    .io_enq_bits_data (io_in_a_bits_data),
    .io_deq_ready     (io_out_a_ready & ~count),	// @[Broadcast.scala:434:20, :491:26, :496:34]
    .io_enq_ready     (_o_data_io_enq_ready),
    .io_deq_valid     (_o_data_io_deq_valid),
    .io_deq_bits_mask (io_out_a_bits_mask),
    .io_deq_bits_data (io_out_a_bits_data)
  );
  assign io_in_a_ready = _io_in_a_ready_output;	// @[Broadcast.scala:486:45]
  assign io_out_a_valid = _o_data_io_deq_valid & ~count;	// @[Broadcast.scala:434:20, :491:26, :497:34, Decoupled.scala:375:21]
  assign io_out_a_bits_opcode = acquire ? 3'h4 : opcode;	// @[Broadcast.scala:427:20, :492:52, :498:31]
  assign io_out_a_bits_param = acquire ? 3'h0 : param;	// @[Broadcast.scala:428:20, :492:52, :499:31]
  assign io_out_a_bits_size = size;	// @[Broadcast.scala:429:20]
  assign io_out_a_bits_source = {acquire ? {1'h1, ~shared} : 2'h0, source};	// @[Broadcast.scala:426:20, :430:20, :492:52, :494:22, :501:35, Cat.scala:33:92]
  assign io_out_a_bits_address = address;	// @[Broadcast.scala:433:24]
  assign io_source = source;	// @[Broadcast.scala:430:20]
  assign io_line = address[31:6];	// @[Broadcast.scala:433:24, :480:22]
  assign io_idle = idle;	// @[Broadcast.scala:436:23]
  assign io_need_d = ~sent_d;	// @[Broadcast.scala:425:24, :478:16]
endmodule

