// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

module TLMonitor_44(
  input        clock,
               reset,
               io_in_a_ready,
               io_in_a_valid,
  input [2:0]  io_in_a_bits_opcode,
               io_in_a_bits_param,
  input [1:0]  io_in_a_bits_size,
  input [10:0] io_in_a_bits_source,
  input [27:0] io_in_a_bits_address,
  input [7:0]  io_in_a_bits_mask,
  input        io_in_a_bits_corrupt,
               io_in_d_ready,
               io_in_d_valid,
  input [2:0]  io_in_d_bits_opcode,
  input [1:0]  io_in_d_bits_size,
  input [10:0] io_in_d_bits_source
);

  wire [31:0]    _plusarg_reader_1_out;	// @[PlusArg.scala:80:11]
  wire [31:0]    _plusarg_reader_out;	// @[PlusArg.scala:80:11]
  wire           a_first_done = io_in_a_ready & io_in_a_valid;	// @[Decoupled.scala:51:35]
  reg  [1039:0]  inflight;	// @[Monitor.scala:611:27]
  reg  [4159:0]  inflight_opcodes;	// @[Monitor.scala:613:35]
  reg  [4159:0]  inflight_sizes;	// @[Monitor.scala:615:33]
  wire [2047:0]  _GEN = {2037'h0, io_in_a_bits_source};	// @[OneHot.scala:57:35]
  wire           d_release_ack = io_in_d_bits_opcode == 3'h6;	// @[Monitor.scala:81:25, :670:46]
  wire [2047:0]  _GEN_0 = {2037'h0, io_in_d_bits_source};	// @[OneHot.scala:57:35]
  reg  [31:0]    watchdog;	// @[Monitor.scala:706:27]
  wire           d_first_done = io_in_d_ready & io_in_d_valid;	// @[Decoupled.scala:51:35]
  wire           _T_613 = d_first_done & ~d_release_ack;	// @[Decoupled.scala:51:35, Monitor.scala:670:46, :671:74, :675:72]
  wire [16398:0] _GEN_1 = {16386'h0, io_in_d_bits_source, 2'h0};	// @[Monitor.scala:677:76, OneHot.scala:64:12]
  wire [2047:0]  _d_clr_T = 2048'h1 << _GEN_0;	// @[OneHot.scala:57:35]
  wire [2047:0]  _a_set_T = 2048'h1 << _GEN;	// @[OneHot.scala:57:35]
  wire [16398:0] _d_opcodes_clr_T_5 = 16399'hF << _GEN_1;	// @[Monitor.scala:677:76]
  wire [16386:0] _a_opcodes_set_T_1 = {16383'h0, a_first_done ? {io_in_a_bits_opcode, 1'h1} : 4'h0} << {16374'h0, io_in_a_bits_source, 2'h0};	// @[Decoupled.scala:51:35, Monitor.scala:42:11, :632:35, :643:40, :652:72, :654:{28,53}, :656:54, OneHot.scala:64:12]
  wire [16398:0] _d_sizes_clr_T_5 = 16399'hF << _GEN_1;	// @[Monitor.scala:677:76, :678:74]
  wire [16385:0] _a_sizes_set_T_1 = {16383'h0, a_first_done ? {io_in_a_bits_size, 1'h1} : 3'h0} << {16373'h0, io_in_a_bits_source, 2'h0};	// @[Decoupled.scala:51:35, Misc.scala:201:34, Monitor.scala:42:11, :645:38, :652:72, :655:{28,51}, :656:54, :657:52, OneHot.scala:64:12]
  always @(posedge clock) begin
    if (reset) begin
      inflight <= 1040'h0;	// @[Monitor.scala:611:27, :723:35]
      inflight_opcodes <= 4160'h0;	// @[Monitor.scala:613:35, :725:35]
      inflight_sizes <= 4160'h0;	// @[Monitor.scala:615:33, :725:35]
      watchdog <= 32'h0;	// @[Monitor.scala:706:27]
    end
    else begin
      inflight <= (inflight | (a_first_done ? _a_set_T[1039:0] : 1040'h0)) & ~(_T_613 ? _d_clr_T[1039:0] : 1040'h0);	// @[Decoupled.scala:51:35, Monitor.scala:611:27, :623:34, :652:72, :653:28, :661:34, :675:{72,91}, :676:21, :702:{27,36,38}, :723:35, OneHot.scala:57:35]
      inflight_opcodes <= (inflight_opcodes | (a_first_done ? _a_opcodes_set_T_1[4159:0] : 4160'h0)) & ~(_T_613 ? _d_opcodes_clr_T_5[4159:0] : 4160'h0);	// @[Decoupled.scala:51:35, Monitor.scala:613:35, :627:33, :652:72, :656:{28,54}, :665:33, :675:{72,91}, :677:{21,76}, :703:{43,60,62}, :725:35]
      inflight_sizes <= (inflight_sizes | (a_first_done ? _a_sizes_set_T_1[4159:0] : 4160'h0)) & ~(_T_613 ? _d_sizes_clr_T_5[4159:0] : 4160'h0);	// @[Decoupled.scala:51:35, Monitor.scala:615:33, :629:31, :652:72, :657:{28,52}, :667:31, :675:{72,91}, :678:{21,74}, :704:{39,54,56}, :725:35]
      if (a_first_done | d_first_done)	// @[Decoupled.scala:51:35, Monitor.scala:712:27]
        watchdog <= 32'h0;	// @[Monitor.scala:706:27]
      else	// @[Monitor.scala:712:27]
        watchdog <= watchdog + 32'h1;	// @[Monitor.scala:706:27, :711:26]
    end
  end // always @(posedge)
  `ifndef SYNTHESIS
    wire  [7:0][2:0] _GEN_2 = '{3'h4, 3'h5, 3'h2, 3'h1, 3'h1, 3'h1, 3'h0, 3'h0};	// @[Monitor.scala:686:39]
    wire  [7:0][2:0] _GEN_3 = '{3'h4, 3'h4, 3'h2, 3'h1, 3'h1, 3'h1, 3'h0, 3'h0};	// @[Monitor.scala:685:38]
    wire  [5:0]      _is_aligned_mask_T_1 = 6'h7 << io_in_a_bits_size;	// @[package.scala:235:71]
    wire  [2:0]      _GEN_4 = io_in_a_bits_address[2:0] & ~(_is_aligned_mask_T_1[2:0]);	// @[Edges.scala:20:16, package.scala:235:{46,71,76}]
    wire             mask_size = io_in_a_bits_size == 2'h2;	// @[Misc.scala:208:26, OneHot.scala:64:12]
    wire             mask_acc = (&io_in_a_bits_size) | mask_size & ~(io_in_a_bits_address[2]);	// @[Misc.scala:205:21, :208:26, :209:26, :210:20, :214:{29,38}]
    wire             mask_acc_1 = (&io_in_a_bits_size) | mask_size & io_in_a_bits_address[2];	// @[Misc.scala:205:21, :208:26, :209:26, :214:{29,38}]
    wire             mask_size_1 = io_in_a_bits_size == 2'h1;	// @[Misc.scala:208:26, OneHot.scala:64:12]
    wire             mask_eq_2 = ~(io_in_a_bits_address[2]) & ~(io_in_a_bits_address[1]);	// @[Misc.scala:209:26, :210:20, :213:27]
    wire             mask_acc_2 = mask_acc | mask_size_1 & mask_eq_2;	// @[Misc.scala:208:26, :213:27, :214:{29,38}]
    wire             mask_eq_3 = ~(io_in_a_bits_address[2]) & io_in_a_bits_address[1];	// @[Misc.scala:209:26, :210:20, :213:27]
    wire             mask_acc_3 = mask_acc | mask_size_1 & mask_eq_3;	// @[Misc.scala:208:26, :213:27, :214:{29,38}]
    wire             mask_eq_4 = io_in_a_bits_address[2] & ~(io_in_a_bits_address[1]);	// @[Misc.scala:209:26, :210:20, :213:27]
    wire             mask_acc_4 = mask_acc_1 | mask_size_1 & mask_eq_4;	// @[Misc.scala:208:26, :213:27, :214:{29,38}]
    wire             mask_eq_5 = io_in_a_bits_address[2] & io_in_a_bits_address[1];	// @[Misc.scala:209:26, :213:27]
    wire             mask_acc_5 = mask_acc_1 | mask_size_1 & mask_eq_5;	// @[Misc.scala:208:26, :213:27, :214:{29,38}]
    wire  [7:0]      mask = {mask_acc_5 | mask_eq_5 & io_in_a_bits_address[0], mask_acc_5 | mask_eq_5 & ~(io_in_a_bits_address[0]), mask_acc_4 | mask_eq_4 & io_in_a_bits_address[0], mask_acc_4 | mask_eq_4 & ~(io_in_a_bits_address[0]), mask_acc_3 | mask_eq_3 & io_in_a_bits_address[0], mask_acc_3 | mask_eq_3 & ~(io_in_a_bits_address[0]), mask_acc_2 | mask_eq_2 & io_in_a_bits_address[0], mask_acc_2 | mask_eq_2 & ~(io_in_a_bits_address[0])};	// @[Cat.scala:33:92, Misc.scala:209:26, :210:20, :213:27, :214:29]
    wire             _GEN_5 = io_in_a_valid & io_in_a_bits_opcode == 3'h6;	// @[Monitor.scala:81:{25,54}]
    wire             _GEN_6 = io_in_a_bits_source > 11'h40F;	// @[Parameters.scala:57:20]
    wire             _GEN_7 = io_in_a_bits_param > 3'h2;	// @[Bundles.scala:111:27, Monitor.scala:640:42]
    wire             _GEN_8 = io_in_a_valid & (&io_in_a_bits_opcode);	// @[Monitor.scala:92:{25,53}]
    wire             _GEN_9 = io_in_a_valid & io_in_a_bits_opcode == 3'h4;	// @[Monitor.scala:104:{25,45}]
    wire             _GEN_10 = io_in_a_bits_mask != mask;	// @[Cat.scala:33:92, Monitor.scala:110:30]
    wire             _GEN_11 = io_in_a_valid & io_in_a_bits_opcode == 3'h0;	// @[Misc.scala:201:34, Monitor.scala:114:{25,53}]
    wire             _GEN_12 = io_in_a_valid & io_in_a_bits_opcode == 3'h1;	// @[Misc.scala:201:81, Monitor.scala:122:{25,56}]
    wire             _GEN_13 = io_in_a_valid & io_in_a_bits_opcode == 3'h2;	// @[Monitor.scala:130:{25,56}, :640:42]
    wire             _GEN_14 = io_in_a_valid & io_in_a_bits_opcode == 3'h3;	// @[Bundles.scala:148:30, Monitor.scala:138:{25,53}]
    wire             _GEN_15 = io_in_a_valid & io_in_a_bits_opcode == 3'h5;	// @[Monitor.scala:146:{25,46}]
    wire             _GEN_16 = io_in_d_valid & io_in_d_bits_opcode == 3'h6;	// @[Monitor.scala:81:25, :310:{25,52}]
    wire             _GEN_17 = io_in_d_bits_source > 11'h40F;	// @[Parameters.scala:57:20]
    wire             _GEN_18 = io_in_d_bits_size != 2'h3;	// @[Misc.scala:205:21, Monitor.scala:312:27]
    wire             _GEN_19 = io_in_d_valid & io_in_d_bits_opcode == 3'h4;	// @[Monitor.scala:104:25, :318:{25,47}]
    wire             _GEN_20 = io_in_d_valid & io_in_d_bits_opcode == 3'h5;	// @[Monitor.scala:146:25, :328:{25,51}]
    wire  [4159:0]   _GEN_21 = {4147'h0, io_in_d_bits_source, 2'h0};	// @[Monitor.scala:634:44, OneHot.scala:64:12]
    wire  [4159:0]   _a_opcode_lookup_T_1 = inflight_opcodes >> _GEN_21;	// @[Monitor.scala:613:35, :634:44]
    wire  [2047:0]   _a_set_wo_ready_T = 2048'h1 << _GEN;	// @[OneHot.scala:57:35]
    wire  [1039:0]   a_set_wo_ready = io_in_a_valid ? _a_set_wo_ready_T[1039:0] : 1040'h0;	// @[Monitor.scala:624:34, :648:71, :649:22, :723:35, OneHot.scala:57:35]
    wire             _T_617 = io_in_d_valid & ~d_release_ack;	// @[Monitor.scala:670:46, :671:74, :680:71]
    wire             same_cycle_resp = io_in_a_valid & io_in_a_bits_source == io_in_d_bits_source;	// @[Monitor.scala:681:{88,113}]
    wire  [1039:0]   _GEN_22 = {1029'h0, io_in_d_bits_source};	// @[Monitor.scala:658:26, :682:25]
    wire             _GEN_23 = _T_617 & same_cycle_resp;	// @[Monitor.scala:680:71, :681:88, :684:30]
    wire             _GEN_24 = _T_617 & ~same_cycle_resp;	// @[Monitor.scala:680:71, :681:88, :684:30]
    wire  [3:0]      _GEN_25 = {2'h0, io_in_d_bits_size};	// @[Monitor.scala:691:36, OneHot.scala:64:12]
    wire             _T_703 = io_in_d_valid & d_release_ack;	// @[Monitor.scala:670:46, :791:71]
    wire  [1039:0]   _T_599 = inflight >> io_in_a_bits_source;	// @[Monitor.scala:611:27, :658:26]
    wire  [1039:0]   _T_618 = inflight >> _GEN_22;	// @[Monitor.scala:611:27, :682:25]
    wire  [4159:0]   _a_size_lookup_T_1 = inflight_sizes >> _GEN_21;	// @[Monitor.scala:615:33, :634:44, :638:40]
    wire  [2047:0]   _d_clr_wo_ready_T = 2048'h1 << _GEN_0;	// @[OneHot.scala:57:35]
    wire  [1039:0]   _T_704 = 1040'h0 >> _GEN_22;	// @[Monitor.scala:682:25, :723:35, :793:25]
    wire  [4159:0]   _c_size_lookup_T_1 = 4160'h0 >> _GEN_21;	// @[Monitor.scala:634:44, :725:35, :747:42]
    always @(posedge clock) begin	// @[Monitor.scala:42:11]
      if (_GEN_5 & ~reset) begin	// @[Monitor.scala:42:11, :81:54]
        if (`ASSERT_VERBOSE_COND_)	// @[Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel carries AcquireBlock type which is unexpected using diplomatic parameters (connected at Plic.scala:363:15)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[Monitor.scala:42:11]
        if (`STOP_COND_)	// @[Monitor.scala:42:11]
          $fatal;	// @[Monitor.scala:42:11]
      end
      if (_GEN_5 & ~reset) begin	// @[Monitor.scala:42:11, :81:54]
        if (`ASSERT_VERBOSE_COND_)	// @[Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel carries AcquireBlock from a client which does not support Probe (connected at Plic.scala:363:15)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[Monitor.scala:42:11]
        if (`STOP_COND_)	// @[Monitor.scala:42:11]
          $fatal;	// @[Monitor.scala:42:11]
      end
      if (_GEN_5 & ~reset & _GEN_6) begin	// @[Monitor.scala:42:11, :81:54, Parameters.scala:57:20]
        if (`ASSERT_VERBOSE_COND_)	// @[Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel AcquireBlock carries invalid source ID (connected at Plic.scala:363:15)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[Monitor.scala:42:11]
        if (`STOP_COND_)	// @[Monitor.scala:42:11]
          $fatal;	// @[Monitor.scala:42:11]
      end
      if (_GEN_5 & ~reset & ~(&io_in_a_bits_size)) begin	// @[Misc.scala:205:21, Monitor.scala:42:11, :81:54]
        if (`ASSERT_VERBOSE_COND_)	// @[Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel AcquireBlock smaller than a beat (connected at Plic.scala:363:15)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[Monitor.scala:42:11]
        if (`STOP_COND_)	// @[Monitor.scala:42:11]
          $fatal;	// @[Monitor.scala:42:11]
      end
      if (_GEN_5 & ~reset & (|_GEN_4)) begin	// @[Edges.scala:20:{16,24}, Monitor.scala:42:11, :81:54]
        if (`ASSERT_VERBOSE_COND_)	// @[Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel AcquireBlock address not aligned to size (connected at Plic.scala:363:15)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[Monitor.scala:42:11]
        if (`STOP_COND_)	// @[Monitor.scala:42:11]
          $fatal;	// @[Monitor.scala:42:11]
      end
      if (_GEN_5 & ~reset & _GEN_7) begin	// @[Bundles.scala:111:27, Monitor.scala:42:11, :81:54]
        if (`ASSERT_VERBOSE_COND_)	// @[Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel AcquireBlock carries invalid grow param (connected at Plic.scala:363:15)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[Monitor.scala:42:11]
        if (`STOP_COND_)	// @[Monitor.scala:42:11]
          $fatal;	// @[Monitor.scala:42:11]
      end
      if (_GEN_5 & ~reset & io_in_a_bits_mask != 8'hFF) begin	// @[Monitor.scala:42:11, :81:54, :88:{18,31}]
        if (`ASSERT_VERBOSE_COND_)	// @[Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel AcquireBlock contains invalid mask (connected at Plic.scala:363:15)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[Monitor.scala:42:11]
        if (`STOP_COND_)	// @[Monitor.scala:42:11]
          $fatal;	// @[Monitor.scala:42:11]
      end
      if (_GEN_5 & ~reset & io_in_a_bits_corrupt) begin	// @[Monitor.scala:42:11, :81:54]
        if (`ASSERT_VERBOSE_COND_)	// @[Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel AcquireBlock is corrupt (connected at Plic.scala:363:15)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[Monitor.scala:42:11]
        if (`STOP_COND_)	// @[Monitor.scala:42:11]
          $fatal;	// @[Monitor.scala:42:11]
      end
      if (_GEN_8 & ~reset) begin	// @[Monitor.scala:42:11, :92:53]
        if (`ASSERT_VERBOSE_COND_)	// @[Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel carries AcquirePerm type which is unexpected using diplomatic parameters (connected at Plic.scala:363:15)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[Monitor.scala:42:11]
        if (`STOP_COND_)	// @[Monitor.scala:42:11]
          $fatal;	// @[Monitor.scala:42:11]
      end
      if (_GEN_8 & ~reset) begin	// @[Monitor.scala:42:11, :92:53]
        if (`ASSERT_VERBOSE_COND_)	// @[Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel carries AcquirePerm from a client which does not support Probe (connected at Plic.scala:363:15)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[Monitor.scala:42:11]
        if (`STOP_COND_)	// @[Monitor.scala:42:11]
          $fatal;	// @[Monitor.scala:42:11]
      end
      if (_GEN_8 & ~reset & _GEN_6) begin	// @[Monitor.scala:42:11, :92:53, Parameters.scala:57:20]
        if (`ASSERT_VERBOSE_COND_)	// @[Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel AcquirePerm carries invalid source ID (connected at Plic.scala:363:15)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[Monitor.scala:42:11]
        if (`STOP_COND_)	// @[Monitor.scala:42:11]
          $fatal;	// @[Monitor.scala:42:11]
      end
      if (_GEN_8 & ~reset & ~(&io_in_a_bits_size)) begin	// @[Misc.scala:205:21, Monitor.scala:42:11, :92:53]
        if (`ASSERT_VERBOSE_COND_)	// @[Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel AcquirePerm smaller than a beat (connected at Plic.scala:363:15)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[Monitor.scala:42:11]
        if (`STOP_COND_)	// @[Monitor.scala:42:11]
          $fatal;	// @[Monitor.scala:42:11]
      end
      if (_GEN_8 & ~reset & (|_GEN_4)) begin	// @[Edges.scala:20:{16,24}, Monitor.scala:42:11, :92:53]
        if (`ASSERT_VERBOSE_COND_)	// @[Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel AcquirePerm address not aligned to size (connected at Plic.scala:363:15)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[Monitor.scala:42:11]
        if (`STOP_COND_)	// @[Monitor.scala:42:11]
          $fatal;	// @[Monitor.scala:42:11]
      end
      if (_GEN_8 & ~reset & _GEN_7) begin	// @[Bundles.scala:111:27, Monitor.scala:42:11, :92:53]
        if (`ASSERT_VERBOSE_COND_)	// @[Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel AcquirePerm carries invalid grow param (connected at Plic.scala:363:15)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[Monitor.scala:42:11]
        if (`STOP_COND_)	// @[Monitor.scala:42:11]
          $fatal;	// @[Monitor.scala:42:11]
      end
      if (_GEN_8 & ~reset & io_in_a_bits_param == 3'h0) begin	// @[Misc.scala:201:34, Monitor.scala:42:11, :92:53, :99:31]
        if (`ASSERT_VERBOSE_COND_)	// @[Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel AcquirePerm requests NtoB (connected at Plic.scala:363:15)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[Monitor.scala:42:11]
        if (`STOP_COND_)	// @[Monitor.scala:42:11]
          $fatal;	// @[Monitor.scala:42:11]
      end
      if (_GEN_8 & ~reset & io_in_a_bits_mask != 8'hFF) begin	// @[Monitor.scala:42:11, :88:18, :92:53, :100:31]
        if (`ASSERT_VERBOSE_COND_)	// @[Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel AcquirePerm contains invalid mask (connected at Plic.scala:363:15)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[Monitor.scala:42:11]
        if (`STOP_COND_)	// @[Monitor.scala:42:11]
          $fatal;	// @[Monitor.scala:42:11]
      end
      if (_GEN_8 & ~reset & io_in_a_bits_corrupt) begin	// @[Monitor.scala:42:11, :92:53]
        if (`ASSERT_VERBOSE_COND_)	// @[Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel AcquirePerm is corrupt (connected at Plic.scala:363:15)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[Monitor.scala:42:11]
        if (`STOP_COND_)	// @[Monitor.scala:42:11]
          $fatal;	// @[Monitor.scala:42:11]
      end
      if (_GEN_9 & ~reset & _GEN_6) begin	// @[Monitor.scala:42:11, :104:45, Parameters.scala:57:20]
        if (`ASSERT_VERBOSE_COND_)	// @[Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel carries Get type which master claims it can't emit (connected at Plic.scala:363:15)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[Monitor.scala:42:11]
        if (`STOP_COND_)	// @[Monitor.scala:42:11]
          $fatal;	// @[Monitor.scala:42:11]
      end
      if (_GEN_9 & ~reset & io_in_a_bits_address[27:26] != 2'h3) begin	// @[Misc.scala:205:21, Monitor.scala:42:11, :104:45, Parameters.scala:137:65]
        if (`ASSERT_VERBOSE_COND_)	// @[Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel carries Get type which slave claims it can't support (connected at Plic.scala:363:15)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[Monitor.scala:42:11]
        if (`STOP_COND_)	// @[Monitor.scala:42:11]
          $fatal;	// @[Monitor.scala:42:11]
      end
      if (_GEN_9 & ~reset & _GEN_6) begin	// @[Monitor.scala:42:11, :104:45, Parameters.scala:57:20]
        if (`ASSERT_VERBOSE_COND_)	// @[Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel Get carries invalid source ID (connected at Plic.scala:363:15)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[Monitor.scala:42:11]
        if (`STOP_COND_)	// @[Monitor.scala:42:11]
          $fatal;	// @[Monitor.scala:42:11]
      end
      if (_GEN_9 & ~reset & (|_GEN_4)) begin	// @[Edges.scala:20:{16,24}, Monitor.scala:42:11, :104:45]
        if (`ASSERT_VERBOSE_COND_)	// @[Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel Get address not aligned to size (connected at Plic.scala:363:15)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[Monitor.scala:42:11]
        if (`STOP_COND_)	// @[Monitor.scala:42:11]
          $fatal;	// @[Monitor.scala:42:11]
      end
      if (_GEN_9 & ~reset & (|io_in_a_bits_param)) begin	// @[Monitor.scala:42:11, :104:45, :109:31]
        if (`ASSERT_VERBOSE_COND_)	// @[Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel Get carries invalid param (connected at Plic.scala:363:15)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[Monitor.scala:42:11]
        if (`STOP_COND_)	// @[Monitor.scala:42:11]
          $fatal;	// @[Monitor.scala:42:11]
      end
      if (_GEN_9 & ~reset & _GEN_10) begin	// @[Monitor.scala:42:11, :104:45, :110:30]
        if (`ASSERT_VERBOSE_COND_)	// @[Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel Get contains invalid mask (connected at Plic.scala:363:15)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[Monitor.scala:42:11]
        if (`STOP_COND_)	// @[Monitor.scala:42:11]
          $fatal;	// @[Monitor.scala:42:11]
      end
      if (_GEN_9 & ~reset & io_in_a_bits_corrupt) begin	// @[Monitor.scala:42:11, :104:45]
        if (`ASSERT_VERBOSE_COND_)	// @[Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel Get is corrupt (connected at Plic.scala:363:15)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[Monitor.scala:42:11]
        if (`STOP_COND_)	// @[Monitor.scala:42:11]
          $fatal;	// @[Monitor.scala:42:11]
      end
      if (_GEN_11 & ~reset & ~(io_in_a_bits_source < 11'h410 & (&(io_in_a_bits_address[27:26])))) begin	// @[Monitor.scala:42:11, :114:53, :115:71, Parameters.scala:57:20, :137:65]
        if (`ASSERT_VERBOSE_COND_)	// @[Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel carries PutFull type which is unexpected using diplomatic parameters (connected at Plic.scala:363:15)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[Monitor.scala:42:11]
        if (`STOP_COND_)	// @[Monitor.scala:42:11]
          $fatal;	// @[Monitor.scala:42:11]
      end
      if (_GEN_11 & ~reset & _GEN_6) begin	// @[Monitor.scala:42:11, :114:53, Parameters.scala:57:20]
        if (`ASSERT_VERBOSE_COND_)	// @[Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel PutFull carries invalid source ID (connected at Plic.scala:363:15)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[Monitor.scala:42:11]
        if (`STOP_COND_)	// @[Monitor.scala:42:11]
          $fatal;	// @[Monitor.scala:42:11]
      end
      if (_GEN_11 & ~reset & (|_GEN_4)) begin	// @[Edges.scala:20:{16,24}, Monitor.scala:42:11, :114:53]
        if (`ASSERT_VERBOSE_COND_)	// @[Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel PutFull address not aligned to size (connected at Plic.scala:363:15)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[Monitor.scala:42:11]
        if (`STOP_COND_)	// @[Monitor.scala:42:11]
          $fatal;	// @[Monitor.scala:42:11]
      end
      if (_GEN_11 & ~reset & (|io_in_a_bits_param)) begin	// @[Monitor.scala:42:11, :114:53, :118:31]
        if (`ASSERT_VERBOSE_COND_)	// @[Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel PutFull carries invalid param (connected at Plic.scala:363:15)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[Monitor.scala:42:11]
        if (`STOP_COND_)	// @[Monitor.scala:42:11]
          $fatal;	// @[Monitor.scala:42:11]
      end
      if (_GEN_11 & ~reset & _GEN_10) begin	// @[Monitor.scala:42:11, :110:30, :114:53]
        if (`ASSERT_VERBOSE_COND_)	// @[Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel PutFull contains invalid mask (connected at Plic.scala:363:15)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[Monitor.scala:42:11]
        if (`STOP_COND_)	// @[Monitor.scala:42:11]
          $fatal;	// @[Monitor.scala:42:11]
      end
      if (_GEN_12 & ~reset & ~(io_in_a_bits_source < 11'h410 & (&(io_in_a_bits_address[27:26])))) begin	// @[Monitor.scala:42:11, :122:56, :123:74, Parameters.scala:57:20, :137:65]
        if (`ASSERT_VERBOSE_COND_)	// @[Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel carries PutPartial type which is unexpected using diplomatic parameters (connected at Plic.scala:363:15)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[Monitor.scala:42:11]
        if (`STOP_COND_)	// @[Monitor.scala:42:11]
          $fatal;	// @[Monitor.scala:42:11]
      end
      if (_GEN_12 & ~reset & _GEN_6) begin	// @[Monitor.scala:42:11, :122:56, Parameters.scala:57:20]
        if (`ASSERT_VERBOSE_COND_)	// @[Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel PutPartial carries invalid source ID (connected at Plic.scala:363:15)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[Monitor.scala:42:11]
        if (`STOP_COND_)	// @[Monitor.scala:42:11]
          $fatal;	// @[Monitor.scala:42:11]
      end
      if (_GEN_12 & ~reset & (|_GEN_4)) begin	// @[Edges.scala:20:{16,24}, Monitor.scala:42:11, :122:56]
        if (`ASSERT_VERBOSE_COND_)	// @[Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel PutPartial address not aligned to size (connected at Plic.scala:363:15)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[Monitor.scala:42:11]
        if (`STOP_COND_)	// @[Monitor.scala:42:11]
          $fatal;	// @[Monitor.scala:42:11]
      end
      if (_GEN_12 & ~reset & (|io_in_a_bits_param)) begin	// @[Monitor.scala:42:11, :122:56, :126:31]
        if (`ASSERT_VERBOSE_COND_)	// @[Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel PutPartial carries invalid param (connected at Plic.scala:363:15)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[Monitor.scala:42:11]
        if (`STOP_COND_)	// @[Monitor.scala:42:11]
          $fatal;	// @[Monitor.scala:42:11]
      end
      if (_GEN_12 & ~reset & (|(io_in_a_bits_mask & ~mask))) begin	// @[Cat.scala:33:92, Monitor.scala:42:11, :122:56, :127:{31,33,40}]
        if (`ASSERT_VERBOSE_COND_)	// @[Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel PutPartial contains invalid mask (connected at Plic.scala:363:15)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[Monitor.scala:42:11]
        if (`STOP_COND_)	// @[Monitor.scala:42:11]
          $fatal;	// @[Monitor.scala:42:11]
      end
      if (_GEN_13 & ~reset) begin	// @[Monitor.scala:42:11, :130:56]
        if (`ASSERT_VERBOSE_COND_)	// @[Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel carries Arithmetic type which is unexpected using diplomatic parameters (connected at Plic.scala:363:15)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[Monitor.scala:42:11]
        if (`STOP_COND_)	// @[Monitor.scala:42:11]
          $fatal;	// @[Monitor.scala:42:11]
      end
      if (_GEN_13 & ~reset & _GEN_6) begin	// @[Monitor.scala:42:11, :130:56, Parameters.scala:57:20]
        if (`ASSERT_VERBOSE_COND_)	// @[Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel Arithmetic carries invalid source ID (connected at Plic.scala:363:15)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[Monitor.scala:42:11]
        if (`STOP_COND_)	// @[Monitor.scala:42:11]
          $fatal;	// @[Monitor.scala:42:11]
      end
      if (_GEN_13 & ~reset & (|_GEN_4)) begin	// @[Edges.scala:20:{16,24}, Monitor.scala:42:11, :130:56]
        if (`ASSERT_VERBOSE_COND_)	// @[Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel Arithmetic address not aligned to size (connected at Plic.scala:363:15)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[Monitor.scala:42:11]
        if (`STOP_COND_)	// @[Monitor.scala:42:11]
          $fatal;	// @[Monitor.scala:42:11]
      end
      if (_GEN_13 & ~reset & io_in_a_bits_param > 3'h4) begin	// @[Bundles.scala:141:33, Monitor.scala:42:11, :104:25, :130:56]
        if (`ASSERT_VERBOSE_COND_)	// @[Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel Arithmetic carries invalid opcode param (connected at Plic.scala:363:15)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[Monitor.scala:42:11]
        if (`STOP_COND_)	// @[Monitor.scala:42:11]
          $fatal;	// @[Monitor.scala:42:11]
      end
      if (_GEN_13 & ~reset & _GEN_10) begin	// @[Monitor.scala:42:11, :110:30, :130:56]
        if (`ASSERT_VERBOSE_COND_)	// @[Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel Arithmetic contains invalid mask (connected at Plic.scala:363:15)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[Monitor.scala:42:11]
        if (`STOP_COND_)	// @[Monitor.scala:42:11]
          $fatal;	// @[Monitor.scala:42:11]
      end
      if (_GEN_14 & ~reset) begin	// @[Monitor.scala:42:11, :138:53]
        if (`ASSERT_VERBOSE_COND_)	// @[Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel carries Logical type which is unexpected using diplomatic parameters (connected at Plic.scala:363:15)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[Monitor.scala:42:11]
        if (`STOP_COND_)	// @[Monitor.scala:42:11]
          $fatal;	// @[Monitor.scala:42:11]
      end
      if (_GEN_14 & ~reset & _GEN_6) begin	// @[Monitor.scala:42:11, :138:53, Parameters.scala:57:20]
        if (`ASSERT_VERBOSE_COND_)	// @[Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel Logical carries invalid source ID (connected at Plic.scala:363:15)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[Monitor.scala:42:11]
        if (`STOP_COND_)	// @[Monitor.scala:42:11]
          $fatal;	// @[Monitor.scala:42:11]
      end
      if (_GEN_14 & ~reset & (|_GEN_4)) begin	// @[Edges.scala:20:{16,24}, Monitor.scala:42:11, :138:53]
        if (`ASSERT_VERBOSE_COND_)	// @[Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel Logical address not aligned to size (connected at Plic.scala:363:15)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[Monitor.scala:42:11]
        if (`STOP_COND_)	// @[Monitor.scala:42:11]
          $fatal;	// @[Monitor.scala:42:11]
      end
      if (_GEN_14 & ~reset & io_in_a_bits_param[2]) begin	// @[Bundles.scala:148:30, Monitor.scala:42:11, :138:53]
        if (`ASSERT_VERBOSE_COND_)	// @[Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel Logical carries invalid opcode param (connected at Plic.scala:363:15)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[Monitor.scala:42:11]
        if (`STOP_COND_)	// @[Monitor.scala:42:11]
          $fatal;	// @[Monitor.scala:42:11]
      end
      if (_GEN_14 & ~reset & _GEN_10) begin	// @[Monitor.scala:42:11, :110:30, :138:53]
        if (`ASSERT_VERBOSE_COND_)	// @[Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel Logical contains invalid mask (connected at Plic.scala:363:15)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[Monitor.scala:42:11]
        if (`STOP_COND_)	// @[Monitor.scala:42:11]
          $fatal;	// @[Monitor.scala:42:11]
      end
      if (_GEN_15 & ~reset) begin	// @[Monitor.scala:42:11, :146:46]
        if (`ASSERT_VERBOSE_COND_)	// @[Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel carries Hint type which is unexpected using diplomatic parameters (connected at Plic.scala:363:15)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[Monitor.scala:42:11]
        if (`STOP_COND_)	// @[Monitor.scala:42:11]
          $fatal;	// @[Monitor.scala:42:11]
      end
      if (_GEN_15 & ~reset & _GEN_6) begin	// @[Monitor.scala:42:11, :146:46, Parameters.scala:57:20]
        if (`ASSERT_VERBOSE_COND_)	// @[Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel Hint carries invalid source ID (connected at Plic.scala:363:15)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[Monitor.scala:42:11]
        if (`STOP_COND_)	// @[Monitor.scala:42:11]
          $fatal;	// @[Monitor.scala:42:11]
      end
      if (_GEN_15 & ~reset & (|_GEN_4)) begin	// @[Edges.scala:20:{16,24}, Monitor.scala:42:11, :146:46]
        if (`ASSERT_VERBOSE_COND_)	// @[Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel Hint address not aligned to size (connected at Plic.scala:363:15)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[Monitor.scala:42:11]
        if (`STOP_COND_)	// @[Monitor.scala:42:11]
          $fatal;	// @[Monitor.scala:42:11]
      end
      if (_GEN_15 & ~reset & (|(io_in_a_bits_param[2:1]))) begin	// @[Bundles.scala:161:28, Monitor.scala:42:11, :146:46]
        if (`ASSERT_VERBOSE_COND_)	// @[Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel Hint carries invalid opcode param (connected at Plic.scala:363:15)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[Monitor.scala:42:11]
        if (`STOP_COND_)	// @[Monitor.scala:42:11]
          $fatal;	// @[Monitor.scala:42:11]
      end
      if (_GEN_15 & ~reset & _GEN_10) begin	// @[Monitor.scala:42:11, :110:30, :146:46]
        if (`ASSERT_VERBOSE_COND_)	// @[Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel Hint contains invalid mask (connected at Plic.scala:363:15)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[Monitor.scala:42:11]
        if (`STOP_COND_)	// @[Monitor.scala:42:11]
          $fatal;	// @[Monitor.scala:42:11]
      end
      if (_GEN_15 & ~reset & io_in_a_bits_corrupt) begin	// @[Monitor.scala:42:11, :146:46]
        if (`ASSERT_VERBOSE_COND_)	// @[Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel Hint is corrupt (connected at Plic.scala:363:15)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[Monitor.scala:42:11]
        if (`STOP_COND_)	// @[Monitor.scala:42:11]
          $fatal;	// @[Monitor.scala:42:11]
      end
      if (io_in_d_valid & ~reset & (&io_in_d_bits_opcode)) begin	// @[Bundles.scala:45:24, Monitor.scala:49:11]
        if (`ASSERT_VERBOSE_COND_)	// @[Monitor.scala:49:11]
          $error("Assertion failed: 'D' channel has invalid opcode (connected at Plic.scala:363:15)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[Monitor.scala:49:11]
        if (`STOP_COND_)	// @[Monitor.scala:49:11]
          $fatal;	// @[Monitor.scala:49:11]
      end
      if (_GEN_16 & ~reset & _GEN_17) begin	// @[Monitor.scala:49:11, :310:52, Parameters.scala:57:20]
        if (`ASSERT_VERBOSE_COND_)	// @[Monitor.scala:49:11]
          $error("Assertion failed: 'D' channel ReleaseAck carries invalid source ID (connected at Plic.scala:363:15)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[Monitor.scala:49:11]
        if (`STOP_COND_)	// @[Monitor.scala:49:11]
          $fatal;	// @[Monitor.scala:49:11]
      end
      if (_GEN_16 & ~reset & _GEN_18) begin	// @[Monitor.scala:49:11, :310:52, :312:27]
        if (`ASSERT_VERBOSE_COND_)	// @[Monitor.scala:49:11]
          $error("Assertion failed: 'D' channel ReleaseAck smaller than a beat (connected at Plic.scala:363:15)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[Monitor.scala:49:11]
        if (`STOP_COND_)	// @[Monitor.scala:49:11]
          $fatal;	// @[Monitor.scala:49:11]
      end
      if (_GEN_19 & ~reset & _GEN_17) begin	// @[Monitor.scala:49:11, :318:47, Parameters.scala:57:20]
        if (`ASSERT_VERBOSE_COND_)	// @[Monitor.scala:49:11]
          $error("Assertion failed: 'D' channel Grant carries invalid source ID (connected at Plic.scala:363:15)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[Monitor.scala:49:11]
        if (`STOP_COND_)	// @[Monitor.scala:49:11]
          $fatal;	// @[Monitor.scala:49:11]
      end
      if (_GEN_19 & ~reset) begin	// @[Monitor.scala:49:11, :318:47]
        if (`ASSERT_VERBOSE_COND_)	// @[Monitor.scala:49:11]
          $error("Assertion failed: 'D' channel Grant carries invalid sink ID (connected at Plic.scala:363:15)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[Monitor.scala:49:11]
        if (`STOP_COND_)	// @[Monitor.scala:49:11]
          $fatal;	// @[Monitor.scala:49:11]
      end
      if (_GEN_19 & ~reset & _GEN_18) begin	// @[Monitor.scala:49:11, :312:27, :318:47]
        if (`ASSERT_VERBOSE_COND_)	// @[Monitor.scala:49:11]
          $error("Assertion failed: 'D' channel Grant smaller than a beat (connected at Plic.scala:363:15)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[Monitor.scala:49:11]
        if (`STOP_COND_)	// @[Monitor.scala:49:11]
          $fatal;	// @[Monitor.scala:49:11]
      end
      if (_GEN_20 & ~reset & _GEN_17) begin	// @[Monitor.scala:49:11, :328:51, Parameters.scala:57:20]
        if (`ASSERT_VERBOSE_COND_)	// @[Monitor.scala:49:11]
          $error("Assertion failed: 'D' channel GrantData carries invalid source ID (connected at Plic.scala:363:15)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[Monitor.scala:49:11]
        if (`STOP_COND_)	// @[Monitor.scala:49:11]
          $fatal;	// @[Monitor.scala:49:11]
      end
      if (_GEN_20 & ~reset) begin	// @[Monitor.scala:49:11, :328:51]
        if (`ASSERT_VERBOSE_COND_)	// @[Monitor.scala:49:11]
          $error("Assertion failed: 'D' channel GrantData carries invalid sink ID (connected at Plic.scala:363:15)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[Monitor.scala:49:11]
        if (`STOP_COND_)	// @[Monitor.scala:49:11]
          $fatal;	// @[Monitor.scala:49:11]
      end
      if (_GEN_20 & ~reset & _GEN_18) begin	// @[Monitor.scala:49:11, :312:27, :328:51]
        if (`ASSERT_VERBOSE_COND_)	// @[Monitor.scala:49:11]
          $error("Assertion failed: 'D' channel GrantData smaller than a beat (connected at Plic.scala:363:15)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[Monitor.scala:49:11]
        if (`STOP_COND_)	// @[Monitor.scala:49:11]
          $fatal;	// @[Monitor.scala:49:11]
      end
      if (io_in_d_valid & io_in_d_bits_opcode == 3'h0 & ~reset & _GEN_17) begin	// @[Misc.scala:201:34, Monitor.scala:49:11, :338:25, Parameters.scala:57:20]
        if (`ASSERT_VERBOSE_COND_)	// @[Monitor.scala:49:11]
          $error("Assertion failed: 'D' channel AccessAck carries invalid source ID (connected at Plic.scala:363:15)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[Monitor.scala:49:11]
        if (`STOP_COND_)	// @[Monitor.scala:49:11]
          $fatal;	// @[Monitor.scala:49:11]
      end
      if (io_in_d_valid & io_in_d_bits_opcode == 3'h1 & ~reset & _GEN_17) begin	// @[Misc.scala:201:81, Monitor.scala:49:11, :346:25, Parameters.scala:57:20]
        if (`ASSERT_VERBOSE_COND_)	// @[Monitor.scala:49:11]
          $error("Assertion failed: 'D' channel AccessAckData carries invalid source ID (connected at Plic.scala:363:15)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[Monitor.scala:49:11]
        if (`STOP_COND_)	// @[Monitor.scala:49:11]
          $fatal;	// @[Monitor.scala:49:11]
      end
      if (io_in_d_valid & io_in_d_bits_opcode == 3'h2 & ~reset & _GEN_17) begin	// @[Monitor.scala:49:11, :354:25, :640:42, Parameters.scala:57:20]
        if (`ASSERT_VERBOSE_COND_)	// @[Monitor.scala:49:11]
          $error("Assertion failed: 'D' channel HintAck carries invalid source ID (connected at Plic.scala:363:15)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[Monitor.scala:49:11]
        if (`STOP_COND_)	// @[Monitor.scala:49:11]
          $fatal;	// @[Monitor.scala:49:11]
      end
      if (a_first_done & ~reset & _T_599[0]) begin	// @[Decoupled.scala:51:35, Monitor.scala:42:11, :658:26]
        if (`ASSERT_VERBOSE_COND_)	// @[Monitor.scala:42:11]
          $error("Assertion failed: 'A' channel re-used a source ID (connected at Plic.scala:363:15)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[Monitor.scala:42:11]
        if (`STOP_COND_)	// @[Monitor.scala:42:11]
          $fatal;	// @[Monitor.scala:42:11]
      end
      if (_T_617 & ~reset & ~(_T_618[0] | same_cycle_resp)) begin	// @[Monitor.scala:49:11, :680:71, :681:88, :682:{25,49}]
        if (`ASSERT_VERBOSE_COND_)	// @[Monitor.scala:49:11]
          $error("Assertion failed: 'D' channel acknowledged for nothing inflight (connected at Plic.scala:363:15)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[Monitor.scala:49:11]
        if (`STOP_COND_)	// @[Monitor.scala:49:11]
          $fatal;	// @[Monitor.scala:49:11]
      end
      if (_GEN_23 & ~reset & ~(io_in_d_bits_opcode == _GEN_3[io_in_a_bits_opcode] | io_in_d_bits_opcode == _GEN_2[io_in_a_bits_opcode])) begin	// @[Monitor.scala:49:11, :684:30, :685:{38,77}, :686:39]
        if (`ASSERT_VERBOSE_COND_)	// @[Monitor.scala:49:11]
          $error("Assertion failed: 'D' channel contains improper opcode response (connected at Plic.scala:363:15)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[Monitor.scala:49:11]
        if (`STOP_COND_)	// @[Monitor.scala:49:11]
          $fatal;	// @[Monitor.scala:49:11]
      end
      if (_GEN_23 & ~reset & io_in_a_bits_size != io_in_d_bits_size) begin	// @[Monitor.scala:49:11, :684:30, :687:36]
        if (`ASSERT_VERBOSE_COND_)	// @[Monitor.scala:49:11]
          $error("Assertion failed: 'D' channel contains improper response size (connected at Plic.scala:363:15)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[Monitor.scala:49:11]
        if (`STOP_COND_)	// @[Monitor.scala:49:11]
          $fatal;	// @[Monitor.scala:49:11]
      end
      if (_GEN_24 & ~reset & ~(io_in_d_bits_opcode == _GEN_3[_a_opcode_lookup_T_1[3:1]] | io_in_d_bits_opcode == _GEN_2[_a_opcode_lookup_T_1[3:1]])) begin	// @[Monitor.scala:49:11, :634:44, :684:30, :685:38, :686:39, :689:{38,72}, :690:38]
        if (`ASSERT_VERBOSE_COND_)	// @[Monitor.scala:49:11]
          $error("Assertion failed: 'D' channel contains improper opcode response (connected at Plic.scala:363:15)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[Monitor.scala:49:11]
        if (`STOP_COND_)	// @[Monitor.scala:49:11]
          $fatal;	// @[Monitor.scala:49:11]
      end
      if (_GEN_24 & ~reset & _GEN_25 != {1'h0, _a_size_lookup_T_1[3:1]}) begin	// @[Monitor.scala:49:11, :638:{19,40}, :684:30, :691:36]
        if (`ASSERT_VERBOSE_COND_)	// @[Monitor.scala:49:11]
          $error("Assertion failed: 'D' channel contains improper response size (connected at Plic.scala:363:15)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[Monitor.scala:49:11]
        if (`STOP_COND_)	// @[Monitor.scala:49:11]
          $fatal;	// @[Monitor.scala:49:11]
      end
      if (io_in_d_valid & io_in_a_valid & io_in_a_bits_source == io_in_d_bits_source & ~d_release_ack & ~reset & ~(~io_in_d_ready | io_in_a_ready)) begin	// @[Monitor.scala:49:11, :670:46, :671:74, :694:90, :695:{15,32}]
        if (`ASSERT_VERBOSE_COND_)	// @[Monitor.scala:49:11]
          $error("Assertion failed: ready check\n    at Monitor.scala:49 assert(cond, message)\n");	// @[Monitor.scala:49:11]
        if (`STOP_COND_)	// @[Monitor.scala:49:11]
          $fatal;	// @[Monitor.scala:49:11]
      end
      if (~reset & ~(a_set_wo_ready != (io_in_d_valid & ~d_release_ack ? _d_clr_wo_ready_T[1039:0] : 1040'h0) | a_set_wo_ready == 1040'h0)) begin	// @[Monitor.scala:49:11, :624:34, :648:71, :649:22, :662:34, :670:46, :671:{71,74,90}, :672:22, :699:{29,48,67}, :723:35, OneHot.scala:57:35]
        if (`ASSERT_VERBOSE_COND_)	// @[Monitor.scala:49:11]
          $error("Assertion failed: 'A' and 'D' concurrent, despite minlatency 1 (connected at Plic.scala:363:15)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[Monitor.scala:49:11]
        if (`STOP_COND_)	// @[Monitor.scala:49:11]
          $fatal;	// @[Monitor.scala:49:11]
      end
      if (~reset & ~(inflight == 1040'h0 | _plusarg_reader_out == 32'h0 | watchdog < _plusarg_reader_out)) begin	// @[Monitor.scala:42:11, :611:27, :706:27, :709:{26,39,47,59}, :723:35, PlusArg.scala:80:11]
        if (`ASSERT_VERBOSE_COND_)	// @[Monitor.scala:42:11]
          $error("Assertion failed: TileLink timeout expired (connected at Plic.scala:363:15)\n    at Monitor.scala:42 assert(cond, message)\n");	// @[Monitor.scala:42:11]
        if (`STOP_COND_)	// @[Monitor.scala:42:11]
          $fatal;	// @[Monitor.scala:42:11]
      end
      if (_T_703 & ~reset & ~(_T_704[0])) begin	// @[Monitor.scala:49:11, :791:71, :793:25]
        if (`ASSERT_VERBOSE_COND_)	// @[Monitor.scala:49:11]
          $error("Assertion failed: 'D' channel acknowledged for nothing inflight (connected at Plic.scala:363:15)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[Monitor.scala:49:11]
        if (`STOP_COND_)	// @[Monitor.scala:49:11]
          $fatal;	// @[Monitor.scala:49:11]
      end
      if (_T_703 & ~reset & _GEN_25 != {1'h0, _c_size_lookup_T_1[3:1]}) begin	// @[Monitor.scala:49:11, :691:36, :747:{21,42}, :791:71, :797:36]
        if (`ASSERT_VERBOSE_COND_)	// @[Monitor.scala:49:11]
          $error("Assertion failed: 'D' channel contains improper response size (connected at Plic.scala:363:15)\n    at Monitor.scala:49 assert(cond, message)\n");	// @[Monitor.scala:49:11]
        if (`STOP_COND_)	// @[Monitor.scala:49:11]
          $fatal;	// @[Monitor.scala:49:11]
      end
    end // always @(posedge)
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0]     _RANDOM_0;
    logic [31:0]     _RANDOM_1;
    logic [31:0]     _RANDOM_2;
    logic [31:0]     _RANDOM_3;
    logic [31:0]     _RANDOM_4;
    logic [31:0]     _RANDOM_5;
    logic [31:0]     _RANDOM_6;
    logic [31:0]     _RANDOM_7;
    logic [31:0]     _RANDOM_8;
    logic [31:0]     _RANDOM_9;
    logic [31:0]     _RANDOM_10;
    logic [31:0]     _RANDOM_11;
    logic [31:0]     _RANDOM_12;
    logic [31:0]     _RANDOM_13;
    logic [31:0]     _RANDOM_14;
    logic [31:0]     _RANDOM_15;
    logic [31:0]     _RANDOM_16;
    logic [31:0]     _RANDOM_17;
    logic [31:0]     _RANDOM_18;
    logic [31:0]     _RANDOM_19;
    logic [31:0]     _RANDOM_20;
    logic [31:0]     _RANDOM_21;
    logic [31:0]     _RANDOM_22;
    logic [31:0]     _RANDOM_23;
    logic [31:0]     _RANDOM_24;
    logic [31:0]     _RANDOM_25;
    logic [31:0]     _RANDOM_26;
    logic [31:0]     _RANDOM_27;
    logic [31:0]     _RANDOM_28;
    logic [31:0]     _RANDOM_29;
    logic [31:0]     _RANDOM_30;
    logic [31:0]     _RANDOM_31;
    logic [31:0]     _RANDOM_32;
    logic [31:0]     _RANDOM_33;
    logic [31:0]     _RANDOM_34;
    logic [31:0]     _RANDOM_35;
    logic [31:0]     _RANDOM_36;
    logic [31:0]     _RANDOM_37;
    logic [31:0]     _RANDOM_38;
    logic [31:0]     _RANDOM_39;
    logic [31:0]     _RANDOM_40;
    logic [31:0]     _RANDOM_41;
    logic [31:0]     _RANDOM_42;
    logic [31:0]     _RANDOM_43;
    logic [31:0]     _RANDOM_44;
    logic [31:0]     _RANDOM_45;
    logic [31:0]     _RANDOM_46;
    logic [31:0]     _RANDOM_47;
    logic [31:0]     _RANDOM_48;
    logic [31:0]     _RANDOM_49;
    logic [31:0]     _RANDOM_50;
    logic [31:0]     _RANDOM_51;
    logic [31:0]     _RANDOM_52;
    logic [31:0]     _RANDOM_53;
    logic [31:0]     _RANDOM_54;
    logic [31:0]     _RANDOM_55;
    logic [31:0]     _RANDOM_56;
    logic [31:0]     _RANDOM_57;
    logic [31:0]     _RANDOM_58;
    logic [31:0]     _RANDOM_59;
    logic [31:0]     _RANDOM_60;
    logic [31:0]     _RANDOM_61;
    logic [31:0]     _RANDOM_62;
    logic [31:0]     _RANDOM_63;
    logic [31:0]     _RANDOM_64;
    logic [31:0]     _RANDOM_65;
    logic [31:0]     _RANDOM_66;
    logic [31:0]     _RANDOM_67;
    logic [31:0]     _RANDOM_68;
    logic [31:0]     _RANDOM_69;
    logic [31:0]     _RANDOM_70;
    logic [31:0]     _RANDOM_71;
    logic [31:0]     _RANDOM_72;
    logic [31:0]     _RANDOM_73;
    logic [31:0]     _RANDOM_74;
    logic [31:0]     _RANDOM_75;
    logic [31:0]     _RANDOM_76;
    logic [31:0]     _RANDOM_77;
    logic [31:0]     _RANDOM_78;
    logic [31:0]     _RANDOM_79;
    logic [31:0]     _RANDOM_80;
    logic [31:0]     _RANDOM_81;
    logic [31:0]     _RANDOM_82;
    logic [31:0]     _RANDOM_83;
    logic [31:0]     _RANDOM_84;
    logic [31:0]     _RANDOM_85;
    logic [31:0]     _RANDOM_86;
    logic [31:0]     _RANDOM_87;
    logic [31:0]     _RANDOM_88;
    logic [31:0]     _RANDOM_89;
    logic [31:0]     _RANDOM_90;
    logic [31:0]     _RANDOM_91;
    logic [31:0]     _RANDOM_92;
    logic [31:0]     _RANDOM_93;
    logic [31:0]     _RANDOM_94;
    logic [31:0]     _RANDOM_95;
    logic [31:0]     _RANDOM_96;
    logic [31:0]     _RANDOM_97;
    logic [31:0]     _RANDOM_98;
    logic [31:0]     _RANDOM_99;
    logic [31:0]     _RANDOM_100;
    logic [31:0]     _RANDOM_101;
    logic [31:0]     _RANDOM_102;
    logic [31:0]     _RANDOM_103;
    logic [31:0]     _RANDOM_104;
    logic [31:0]     _RANDOM_105;
    logic [31:0]     _RANDOM_106;
    logic [31:0]     _RANDOM_107;
    logic [31:0]     _RANDOM_108;
    logic [31:0]     _RANDOM_109;
    logic [31:0]     _RANDOM_110;
    logic [31:0]     _RANDOM_111;
    logic [31:0]     _RANDOM_112;
    logic [31:0]     _RANDOM_113;
    logic [31:0]     _RANDOM_114;
    logic [31:0]     _RANDOM_115;
    logic [31:0]     _RANDOM_116;
    logic [31:0]     _RANDOM_117;
    logic [31:0]     _RANDOM_118;
    logic [31:0]     _RANDOM_119;
    logic [31:0]     _RANDOM_120;
    logic [31:0]     _RANDOM_121;
    logic [31:0]     _RANDOM_122;
    logic [31:0]     _RANDOM_123;
    logic [31:0]     _RANDOM_124;
    logic [31:0]     _RANDOM_125;
    logic [31:0]     _RANDOM_126;
    logic [31:0]     _RANDOM_127;
    logic [31:0]     _RANDOM_128;
    logic [31:0]     _RANDOM_129;
    logic [31:0]     _RANDOM_130;
    logic [31:0]     _RANDOM_131;
    logic [31:0]     _RANDOM_132;
    logic [31:0]     _RANDOM_133;
    logic [31:0]     _RANDOM_134;
    logic [31:0]     _RANDOM_135;
    logic [31:0]     _RANDOM_136;
    logic [31:0]     _RANDOM_137;
    logic [31:0]     _RANDOM_138;
    logic [31:0]     _RANDOM_139;
    logic [31:0]     _RANDOM_140;
    logic [31:0]     _RANDOM_141;
    logic [31:0]     _RANDOM_142;
    logic [31:0]     _RANDOM_143;
    logic [31:0]     _RANDOM_144;
    logic [31:0]     _RANDOM_145;
    logic [31:0]     _RANDOM_146;
    logic [31:0]     _RANDOM_147;
    logic [31:0]     _RANDOM_148;
    logic [31:0]     _RANDOM_149;
    logic [31:0]     _RANDOM_150;
    logic [31:0]     _RANDOM_151;
    logic [31:0]     _RANDOM_152;
    logic [31:0]     _RANDOM_153;
    logic [31:0]     _RANDOM_154;
    logic [31:0]     _RANDOM_155;
    logic [31:0]     _RANDOM_156;
    logic [31:0]     _RANDOM_157;
    logic [31:0]     _RANDOM_158;
    logic [31:0]     _RANDOM_159;
    logic [31:0]     _RANDOM_160;
    logic [31:0]     _RANDOM_161;
    logic [31:0]     _RANDOM_162;
    logic [31:0]     _RANDOM_163;
    logic [31:0]     _RANDOM_164;
    logic [31:0]     _RANDOM_165;
    logic [31:0]     _RANDOM_166;
    logic [31:0]     _RANDOM_167;
    logic [31:0]     _RANDOM_168;
    logic [31:0]     _RANDOM_169;
    logic [31:0]     _RANDOM_170;
    logic [31:0]     _RANDOM_171;
    logic [31:0]     _RANDOM_172;
    logic [31:0]     _RANDOM_173;
    logic [31:0]     _RANDOM_174;
    logic [31:0]     _RANDOM_175;
    logic [31:0]     _RANDOM_176;
    logic [31:0]     _RANDOM_177;
    logic [31:0]     _RANDOM_178;
    logic [31:0]     _RANDOM_179;
    logic [31:0]     _RANDOM_180;
    logic [31:0]     _RANDOM_181;
    logic [31:0]     _RANDOM_182;
    logic [31:0]     _RANDOM_183;
    logic [31:0]     _RANDOM_184;
    logic [31:0]     _RANDOM_185;
    logic [31:0]     _RANDOM_186;
    logic [31:0]     _RANDOM_187;
    logic [31:0]     _RANDOM_188;
    logic [31:0]     _RANDOM_189;
    logic [31:0]     _RANDOM_190;
    logic [31:0]     _RANDOM_191;
    logic [31:0]     _RANDOM_192;
    logic [31:0]     _RANDOM_193;
    logic [31:0]     _RANDOM_194;
    logic [31:0]     _RANDOM_195;
    logic [31:0]     _RANDOM_196;
    logic [31:0]     _RANDOM_197;
    logic [31:0]     _RANDOM_198;
    logic [31:0]     _RANDOM_199;
    logic [31:0]     _RANDOM_200;
    logic [31:0]     _RANDOM_201;
    logic [31:0]     _RANDOM_202;
    logic [31:0]     _RANDOM_203;
    logic [31:0]     _RANDOM_204;
    logic [31:0]     _RANDOM_205;
    logic [31:0]     _RANDOM_206;
    logic [31:0]     _RANDOM_207;
    logic [31:0]     _RANDOM_208;
    logic [31:0]     _RANDOM_209;
    logic [31:0]     _RANDOM_210;
    logic [31:0]     _RANDOM_211;
    logic [31:0]     _RANDOM_212;
    logic [31:0]     _RANDOM_213;
    logic [31:0]     _RANDOM_214;
    logic [31:0]     _RANDOM_215;
    logic [31:0]     _RANDOM_216;
    logic [31:0]     _RANDOM_217;
    logic [31:0]     _RANDOM_218;
    logic [31:0]     _RANDOM_219;
    logic [31:0]     _RANDOM_220;
    logic [31:0]     _RANDOM_221;
    logic [31:0]     _RANDOM_222;
    logic [31:0]     _RANDOM_223;
    logic [31:0]     _RANDOM_224;
    logic [31:0]     _RANDOM_225;
    logic [31:0]     _RANDOM_226;
    logic [31:0]     _RANDOM_227;
    logic [31:0]     _RANDOM_228;
    logic [31:0]     _RANDOM_229;
    logic [31:0]     _RANDOM_230;
    logic [31:0]     _RANDOM_231;
    logic [31:0]     _RANDOM_232;
    logic [31:0]     _RANDOM_233;
    logic [31:0]     _RANDOM_234;
    logic [31:0]     _RANDOM_235;
    logic [31:0]     _RANDOM_236;
    logic [31:0]     _RANDOM_237;
    logic [31:0]     _RANDOM_238;
    logic [31:0]     _RANDOM_239;
    logic [31:0]     _RANDOM_240;
    logic [31:0]     _RANDOM_241;
    logic [31:0]     _RANDOM_242;
    logic [31:0]     _RANDOM_243;
    logic [31:0]     _RANDOM_244;
    logic [31:0]     _RANDOM_245;
    logic [31:0]     _RANDOM_246;
    logic [31:0]     _RANDOM_247;
    logic [31:0]     _RANDOM_248;
    logic [31:0]     _RANDOM_249;
    logic [31:0]     _RANDOM_250;
    logic [31:0]     _RANDOM_251;
    logic [31:0]     _RANDOM_252;
    logic [31:0]     _RANDOM_253;
    logic [31:0]     _RANDOM_254;
    logic [31:0]     _RANDOM_255;
    logic [31:0]     _RANDOM_256;
    logic [31:0]     _RANDOM_257;
    logic [31:0]     _RANDOM_258;
    logic [31:0]     _RANDOM_259;
    logic [31:0]     _RANDOM_260;
    logic [31:0]     _RANDOM_261;
    logic [31:0]     _RANDOM_262;
    logic [31:0]     _RANDOM_263;
    logic [31:0]     _RANDOM_264;
    logic [31:0]     _RANDOM_265;
    logic [31:0]     _RANDOM_266;
    logic [31:0]     _RANDOM_267;
    logic [31:0]     _RANDOM_268;
    logic [31:0]     _RANDOM_269;
    logic [31:0]     _RANDOM_270;
    logic [31:0]     _RANDOM_271;
    logic [31:0]     _RANDOM_272;
    logic [31:0]     _RANDOM_273;
    logic [31:0]     _RANDOM_274;
    logic [31:0]     _RANDOM_275;
    logic [31:0]     _RANDOM_276;
    logic [31:0]     _RANDOM_277;
    logic [31:0]     _RANDOM_278;
    logic [31:0]     _RANDOM_279;
    logic [31:0]     _RANDOM_280;
    logic [31:0]     _RANDOM_281;
    logic [31:0]     _RANDOM_282;
    logic [31:0]     _RANDOM_283;
    logic [31:0]     _RANDOM_284;
    logic [31:0]     _RANDOM_285;
    logic [31:0]     _RANDOM_286;
    logic [31:0]     _RANDOM_287;
    logic [31:0]     _RANDOM_288;
    logic [31:0]     _RANDOM_289;
    logic [31:0]     _RANDOM_290;
    logic [31:0]     _RANDOM_291;
    logic [31:0]     _RANDOM_292;
    logic [31:0]     _RANDOM_293;
    logic [31:0]     _RANDOM_294;
    logic [31:0]     _RANDOM_295;
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        _RANDOM_0 = `RANDOM;
        _RANDOM_1 = `RANDOM;
        _RANDOM_2 = `RANDOM;
        _RANDOM_3 = `RANDOM;
        _RANDOM_4 = `RANDOM;
        _RANDOM_5 = `RANDOM;
        _RANDOM_6 = `RANDOM;
        _RANDOM_7 = `RANDOM;
        _RANDOM_8 = `RANDOM;
        _RANDOM_9 = `RANDOM;
        _RANDOM_10 = `RANDOM;
        _RANDOM_11 = `RANDOM;
        _RANDOM_12 = `RANDOM;
        _RANDOM_13 = `RANDOM;
        _RANDOM_14 = `RANDOM;
        _RANDOM_15 = `RANDOM;
        _RANDOM_16 = `RANDOM;
        _RANDOM_17 = `RANDOM;
        _RANDOM_18 = `RANDOM;
        _RANDOM_19 = `RANDOM;
        _RANDOM_20 = `RANDOM;
        _RANDOM_21 = `RANDOM;
        _RANDOM_22 = `RANDOM;
        _RANDOM_23 = `RANDOM;
        _RANDOM_24 = `RANDOM;
        _RANDOM_25 = `RANDOM;
        _RANDOM_26 = `RANDOM;
        _RANDOM_27 = `RANDOM;
        _RANDOM_28 = `RANDOM;
        _RANDOM_29 = `RANDOM;
        _RANDOM_30 = `RANDOM;
        _RANDOM_31 = `RANDOM;
        _RANDOM_32 = `RANDOM;
        _RANDOM_33 = `RANDOM;
        _RANDOM_34 = `RANDOM;
        _RANDOM_35 = `RANDOM;
        _RANDOM_36 = `RANDOM;
        _RANDOM_37 = `RANDOM;
        _RANDOM_38 = `RANDOM;
        _RANDOM_39 = `RANDOM;
        _RANDOM_40 = `RANDOM;
        _RANDOM_41 = `RANDOM;
        _RANDOM_42 = `RANDOM;
        _RANDOM_43 = `RANDOM;
        _RANDOM_44 = `RANDOM;
        _RANDOM_45 = `RANDOM;
        _RANDOM_46 = `RANDOM;
        _RANDOM_47 = `RANDOM;
        _RANDOM_48 = `RANDOM;
        _RANDOM_49 = `RANDOM;
        _RANDOM_50 = `RANDOM;
        _RANDOM_51 = `RANDOM;
        _RANDOM_52 = `RANDOM;
        _RANDOM_53 = `RANDOM;
        _RANDOM_54 = `RANDOM;
        _RANDOM_55 = `RANDOM;
        _RANDOM_56 = `RANDOM;
        _RANDOM_57 = `RANDOM;
        _RANDOM_58 = `RANDOM;
        _RANDOM_59 = `RANDOM;
        _RANDOM_60 = `RANDOM;
        _RANDOM_61 = `RANDOM;
        _RANDOM_62 = `RANDOM;
        _RANDOM_63 = `RANDOM;
        _RANDOM_64 = `RANDOM;
        _RANDOM_65 = `RANDOM;
        _RANDOM_66 = `RANDOM;
        _RANDOM_67 = `RANDOM;
        _RANDOM_68 = `RANDOM;
        _RANDOM_69 = `RANDOM;
        _RANDOM_70 = `RANDOM;
        _RANDOM_71 = `RANDOM;
        _RANDOM_72 = `RANDOM;
        _RANDOM_73 = `RANDOM;
        _RANDOM_74 = `RANDOM;
        _RANDOM_75 = `RANDOM;
        _RANDOM_76 = `RANDOM;
        _RANDOM_77 = `RANDOM;
        _RANDOM_78 = `RANDOM;
        _RANDOM_79 = `RANDOM;
        _RANDOM_80 = `RANDOM;
        _RANDOM_81 = `RANDOM;
        _RANDOM_82 = `RANDOM;
        _RANDOM_83 = `RANDOM;
        _RANDOM_84 = `RANDOM;
        _RANDOM_85 = `RANDOM;
        _RANDOM_86 = `RANDOM;
        _RANDOM_87 = `RANDOM;
        _RANDOM_88 = `RANDOM;
        _RANDOM_89 = `RANDOM;
        _RANDOM_90 = `RANDOM;
        _RANDOM_91 = `RANDOM;
        _RANDOM_92 = `RANDOM;
        _RANDOM_93 = `RANDOM;
        _RANDOM_94 = `RANDOM;
        _RANDOM_95 = `RANDOM;
        _RANDOM_96 = `RANDOM;
        _RANDOM_97 = `RANDOM;
        _RANDOM_98 = `RANDOM;
        _RANDOM_99 = `RANDOM;
        _RANDOM_100 = `RANDOM;
        _RANDOM_101 = `RANDOM;
        _RANDOM_102 = `RANDOM;
        _RANDOM_103 = `RANDOM;
        _RANDOM_104 = `RANDOM;
        _RANDOM_105 = `RANDOM;
        _RANDOM_106 = `RANDOM;
        _RANDOM_107 = `RANDOM;
        _RANDOM_108 = `RANDOM;
        _RANDOM_109 = `RANDOM;
        _RANDOM_110 = `RANDOM;
        _RANDOM_111 = `RANDOM;
        _RANDOM_112 = `RANDOM;
        _RANDOM_113 = `RANDOM;
        _RANDOM_114 = `RANDOM;
        _RANDOM_115 = `RANDOM;
        _RANDOM_116 = `RANDOM;
        _RANDOM_117 = `RANDOM;
        _RANDOM_118 = `RANDOM;
        _RANDOM_119 = `RANDOM;
        _RANDOM_120 = `RANDOM;
        _RANDOM_121 = `RANDOM;
        _RANDOM_122 = `RANDOM;
        _RANDOM_123 = `RANDOM;
        _RANDOM_124 = `RANDOM;
        _RANDOM_125 = `RANDOM;
        _RANDOM_126 = `RANDOM;
        _RANDOM_127 = `RANDOM;
        _RANDOM_128 = `RANDOM;
        _RANDOM_129 = `RANDOM;
        _RANDOM_130 = `RANDOM;
        _RANDOM_131 = `RANDOM;
        _RANDOM_132 = `RANDOM;
        _RANDOM_133 = `RANDOM;
        _RANDOM_134 = `RANDOM;
        _RANDOM_135 = `RANDOM;
        _RANDOM_136 = `RANDOM;
        _RANDOM_137 = `RANDOM;
        _RANDOM_138 = `RANDOM;
        _RANDOM_139 = `RANDOM;
        _RANDOM_140 = `RANDOM;
        _RANDOM_141 = `RANDOM;
        _RANDOM_142 = `RANDOM;
        _RANDOM_143 = `RANDOM;
        _RANDOM_144 = `RANDOM;
        _RANDOM_145 = `RANDOM;
        _RANDOM_146 = `RANDOM;
        _RANDOM_147 = `RANDOM;
        _RANDOM_148 = `RANDOM;
        _RANDOM_149 = `RANDOM;
        _RANDOM_150 = `RANDOM;
        _RANDOM_151 = `RANDOM;
        _RANDOM_152 = `RANDOM;
        _RANDOM_153 = `RANDOM;
        _RANDOM_154 = `RANDOM;
        _RANDOM_155 = `RANDOM;
        _RANDOM_156 = `RANDOM;
        _RANDOM_157 = `RANDOM;
        _RANDOM_158 = `RANDOM;
        _RANDOM_159 = `RANDOM;
        _RANDOM_160 = `RANDOM;
        _RANDOM_161 = `RANDOM;
        _RANDOM_162 = `RANDOM;
        _RANDOM_163 = `RANDOM;
        _RANDOM_164 = `RANDOM;
        _RANDOM_165 = `RANDOM;
        _RANDOM_166 = `RANDOM;
        _RANDOM_167 = `RANDOM;
        _RANDOM_168 = `RANDOM;
        _RANDOM_169 = `RANDOM;
        _RANDOM_170 = `RANDOM;
        _RANDOM_171 = `RANDOM;
        _RANDOM_172 = `RANDOM;
        _RANDOM_173 = `RANDOM;
        _RANDOM_174 = `RANDOM;
        _RANDOM_175 = `RANDOM;
        _RANDOM_176 = `RANDOM;
        _RANDOM_177 = `RANDOM;
        _RANDOM_178 = `RANDOM;
        _RANDOM_179 = `RANDOM;
        _RANDOM_180 = `RANDOM;
        _RANDOM_181 = `RANDOM;
        _RANDOM_182 = `RANDOM;
        _RANDOM_183 = `RANDOM;
        _RANDOM_184 = `RANDOM;
        _RANDOM_185 = `RANDOM;
        _RANDOM_186 = `RANDOM;
        _RANDOM_187 = `RANDOM;
        _RANDOM_188 = `RANDOM;
        _RANDOM_189 = `RANDOM;
        _RANDOM_190 = `RANDOM;
        _RANDOM_191 = `RANDOM;
        _RANDOM_192 = `RANDOM;
        _RANDOM_193 = `RANDOM;
        _RANDOM_194 = `RANDOM;
        _RANDOM_195 = `RANDOM;
        _RANDOM_196 = `RANDOM;
        _RANDOM_197 = `RANDOM;
        _RANDOM_198 = `RANDOM;
        _RANDOM_199 = `RANDOM;
        _RANDOM_200 = `RANDOM;
        _RANDOM_201 = `RANDOM;
        _RANDOM_202 = `RANDOM;
        _RANDOM_203 = `RANDOM;
        _RANDOM_204 = `RANDOM;
        _RANDOM_205 = `RANDOM;
        _RANDOM_206 = `RANDOM;
        _RANDOM_207 = `RANDOM;
        _RANDOM_208 = `RANDOM;
        _RANDOM_209 = `RANDOM;
        _RANDOM_210 = `RANDOM;
        _RANDOM_211 = `RANDOM;
        _RANDOM_212 = `RANDOM;
        _RANDOM_213 = `RANDOM;
        _RANDOM_214 = `RANDOM;
        _RANDOM_215 = `RANDOM;
        _RANDOM_216 = `RANDOM;
        _RANDOM_217 = `RANDOM;
        _RANDOM_218 = `RANDOM;
        _RANDOM_219 = `RANDOM;
        _RANDOM_220 = `RANDOM;
        _RANDOM_221 = `RANDOM;
        _RANDOM_222 = `RANDOM;
        _RANDOM_223 = `RANDOM;
        _RANDOM_224 = `RANDOM;
        _RANDOM_225 = `RANDOM;
        _RANDOM_226 = `RANDOM;
        _RANDOM_227 = `RANDOM;
        _RANDOM_228 = `RANDOM;
        _RANDOM_229 = `RANDOM;
        _RANDOM_230 = `RANDOM;
        _RANDOM_231 = `RANDOM;
        _RANDOM_232 = `RANDOM;
        _RANDOM_233 = `RANDOM;
        _RANDOM_234 = `RANDOM;
        _RANDOM_235 = `RANDOM;
        _RANDOM_236 = `RANDOM;
        _RANDOM_237 = `RANDOM;
        _RANDOM_238 = `RANDOM;
        _RANDOM_239 = `RANDOM;
        _RANDOM_240 = `RANDOM;
        _RANDOM_241 = `RANDOM;
        _RANDOM_242 = `RANDOM;
        _RANDOM_243 = `RANDOM;
        _RANDOM_244 = `RANDOM;
        _RANDOM_245 = `RANDOM;
        _RANDOM_246 = `RANDOM;
        _RANDOM_247 = `RANDOM;
        _RANDOM_248 = `RANDOM;
        _RANDOM_249 = `RANDOM;
        _RANDOM_250 = `RANDOM;
        _RANDOM_251 = `RANDOM;
        _RANDOM_252 = `RANDOM;
        _RANDOM_253 = `RANDOM;
        _RANDOM_254 = `RANDOM;
        _RANDOM_255 = `RANDOM;
        _RANDOM_256 = `RANDOM;
        _RANDOM_257 = `RANDOM;
        _RANDOM_258 = `RANDOM;
        _RANDOM_259 = `RANDOM;
        _RANDOM_260 = `RANDOM;
        _RANDOM_261 = `RANDOM;
        _RANDOM_262 = `RANDOM;
        _RANDOM_263 = `RANDOM;
        _RANDOM_264 = `RANDOM;
        _RANDOM_265 = `RANDOM;
        _RANDOM_266 = `RANDOM;
        _RANDOM_267 = `RANDOM;
        _RANDOM_268 = `RANDOM;
        _RANDOM_269 = `RANDOM;
        _RANDOM_270 = `RANDOM;
        _RANDOM_271 = `RANDOM;
        _RANDOM_272 = `RANDOM;
        _RANDOM_273 = `RANDOM;
        _RANDOM_274 = `RANDOM;
        _RANDOM_275 = `RANDOM;
        _RANDOM_276 = `RANDOM;
        _RANDOM_277 = `RANDOM;
        _RANDOM_278 = `RANDOM;
        _RANDOM_279 = `RANDOM;
        _RANDOM_280 = `RANDOM;
        _RANDOM_281 = `RANDOM;
        _RANDOM_282 = `RANDOM;
        _RANDOM_283 = `RANDOM;
        _RANDOM_284 = `RANDOM;
        _RANDOM_285 = `RANDOM;
        _RANDOM_286 = `RANDOM;
        _RANDOM_287 = `RANDOM;
        _RANDOM_288 = `RANDOM;
        _RANDOM_289 = `RANDOM;
        _RANDOM_290 = `RANDOM;
        _RANDOM_291 = `RANDOM;
        _RANDOM_292 = `RANDOM;
        _RANDOM_293 = `RANDOM;
        _RANDOM_294 = `RANDOM;
        _RANDOM_295 = `RANDOM;
        inflight = {_RANDOM_2[31:5], _RANDOM_3, _RANDOM_4, _RANDOM_5, _RANDOM_6, _RANDOM_7, _RANDOM_8, _RANDOM_9, _RANDOM_10, _RANDOM_11, _RANDOM_12, _RANDOM_13, _RANDOM_14, _RANDOM_15, _RANDOM_16, _RANDOM_17, _RANDOM_18, _RANDOM_19, _RANDOM_20, _RANDOM_21, _RANDOM_22, _RANDOM_23, _RANDOM_24, _RANDOM_25, _RANDOM_26, _RANDOM_27, _RANDOM_28, _RANDOM_29, _RANDOM_30, _RANDOM_31, _RANDOM_32, _RANDOM_33, _RANDOM_34[20:0]};	// @[Monitor.scala:611:27]
        inflight_opcodes = {_RANDOM_34[31:21], _RANDOM_35, _RANDOM_36, _RANDOM_37, _RANDOM_38, _RANDOM_39, _RANDOM_40, _RANDOM_41, _RANDOM_42, _RANDOM_43, _RANDOM_44, _RANDOM_45, _RANDOM_46, _RANDOM_47, _RANDOM_48, _RANDOM_49, _RANDOM_50, _RANDOM_51, _RANDOM_52, _RANDOM_53, _RANDOM_54, _RANDOM_55, _RANDOM_56, _RANDOM_57, _RANDOM_58, _RANDOM_59, _RANDOM_60, _RANDOM_61, _RANDOM_62, _RANDOM_63, _RANDOM_64, _RANDOM_65, _RANDOM_66, _RANDOM_67, _RANDOM_68, _RANDOM_69, _RANDOM_70, _RANDOM_71, _RANDOM_72, _RANDOM_73, _RANDOM_74, _RANDOM_75, _RANDOM_76, _RANDOM_77, _RANDOM_78, _RANDOM_79, _RANDOM_80, _RANDOM_81, _RANDOM_82, _RANDOM_83, _RANDOM_84, _RANDOM_85, _RANDOM_86, _RANDOM_87, _RANDOM_88, _RANDOM_89, _RANDOM_90, _RANDOM_91, _RANDOM_92, _RANDOM_93, _RANDOM_94, _RANDOM_95, _RANDOM_96, _RANDOM_97, _RANDOM_98, _RANDOM_99, _RANDOM_100, _RANDOM_101, _RANDOM_102, _RANDOM_103, _RANDOM_104, _RANDOM_105, _RANDOM_106, _RANDOM_107, _RANDOM_108, _RANDOM_109, _RANDOM_110, _RANDOM_111, _RANDOM_112, _RANDOM_113, _RANDOM_114, _RANDOM_115, _RANDOM_116, _RANDOM_117, _RANDOM_118, _RANDOM_119, _RANDOM_120, _RANDOM_121, _RANDOM_122, _RANDOM_123, _RANDOM_124, _RANDOM_125, _RANDOM_126, _RANDOM_127, _RANDOM_128, _RANDOM_129, _RANDOM_130, _RANDOM_131, _RANDOM_132, _RANDOM_133, _RANDOM_134, _RANDOM_135, _RANDOM_136, _RANDOM_137, _RANDOM_138, _RANDOM_139, _RANDOM_140, _RANDOM_141, _RANDOM_142, _RANDOM_143, _RANDOM_144, _RANDOM_145, _RANDOM_146, _RANDOM_147, _RANDOM_148, _RANDOM_149, _RANDOM_150, _RANDOM_151, _RANDOM_152, _RANDOM_153, _RANDOM_154, _RANDOM_155, _RANDOM_156, _RANDOM_157, _RANDOM_158, _RANDOM_159, _RANDOM_160, _RANDOM_161, _RANDOM_162, _RANDOM_163, _RANDOM_164[20:0]};	// @[Monitor.scala:611:27, :613:35]
        inflight_sizes = {_RANDOM_164[31:21], _RANDOM_165, _RANDOM_166, _RANDOM_167, _RANDOM_168, _RANDOM_169, _RANDOM_170, _RANDOM_171, _RANDOM_172, _RANDOM_173, _RANDOM_174, _RANDOM_175, _RANDOM_176, _RANDOM_177, _RANDOM_178, _RANDOM_179, _RANDOM_180, _RANDOM_181, _RANDOM_182, _RANDOM_183, _RANDOM_184, _RANDOM_185, _RANDOM_186, _RANDOM_187, _RANDOM_188, _RANDOM_189, _RANDOM_190, _RANDOM_191, _RANDOM_192, _RANDOM_193, _RANDOM_194, _RANDOM_195, _RANDOM_196, _RANDOM_197, _RANDOM_198, _RANDOM_199, _RANDOM_200, _RANDOM_201, _RANDOM_202, _RANDOM_203, _RANDOM_204, _RANDOM_205, _RANDOM_206, _RANDOM_207, _RANDOM_208, _RANDOM_209, _RANDOM_210, _RANDOM_211, _RANDOM_212, _RANDOM_213, _RANDOM_214, _RANDOM_215, _RANDOM_216, _RANDOM_217, _RANDOM_218, _RANDOM_219, _RANDOM_220, _RANDOM_221, _RANDOM_222, _RANDOM_223, _RANDOM_224, _RANDOM_225, _RANDOM_226, _RANDOM_227, _RANDOM_228, _RANDOM_229, _RANDOM_230, _RANDOM_231, _RANDOM_232, _RANDOM_233, _RANDOM_234, _RANDOM_235, _RANDOM_236, _RANDOM_237, _RANDOM_238, _RANDOM_239, _RANDOM_240, _RANDOM_241, _RANDOM_242, _RANDOM_243, _RANDOM_244, _RANDOM_245, _RANDOM_246, _RANDOM_247, _RANDOM_248, _RANDOM_249, _RANDOM_250, _RANDOM_251, _RANDOM_252, _RANDOM_253, _RANDOM_254, _RANDOM_255, _RANDOM_256, _RANDOM_257, _RANDOM_258, _RANDOM_259, _RANDOM_260, _RANDOM_261, _RANDOM_262, _RANDOM_263, _RANDOM_264, _RANDOM_265, _RANDOM_266, _RANDOM_267, _RANDOM_268, _RANDOM_269, _RANDOM_270, _RANDOM_271, _RANDOM_272, _RANDOM_273, _RANDOM_274, _RANDOM_275, _RANDOM_276, _RANDOM_277, _RANDOM_278, _RANDOM_279, _RANDOM_280, _RANDOM_281, _RANDOM_282, _RANDOM_283, _RANDOM_284, _RANDOM_285, _RANDOM_286, _RANDOM_287, _RANDOM_288, _RANDOM_289, _RANDOM_290, _RANDOM_291, _RANDOM_292, _RANDOM_293, _RANDOM_294[20:0]};	// @[Monitor.scala:613:35, :615:33]
        watchdog = {_RANDOM_294[31:23], _RANDOM_295[22:0]};	// @[Monitor.scala:615:33, :706:27]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // not def SYNTHESIS
  plusarg_reader #(
    .FORMAT("tilelink_timeout=%d"),
    .DEFAULT(0),
    .WIDTH(32)
  ) plusarg_reader (	// @[PlusArg.scala:80:11]
    .out (_plusarg_reader_out)
  );
  plusarg_reader #(
    .FORMAT("tilelink_timeout=%d"),
    .DEFAULT(0),
    .WIDTH(32)
  ) plusarg_reader_1 (	// @[PlusArg.scala:80:11]
    .out (_plusarg_reader_1_out)
  );
endmodule

